import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {io} from 'socket.io-client';
import {config as defaults} from '../src/config.js';
import {createApp} from '../src/app.js';
import {parseRange} from '../src/media.js';
import {keyboardSuggestion,parseLyrics,seal,unseal} from '../src/util.js';
import {sourceUrl,normalizeSpotify,normalizeYoutube,normalizeSoundcloud} from '../src/providers.js';
import {parseCSV} from '../src/library.js';
import {applyCommand,initialState} from '../src/rooms.js';
import pino from 'pino';
import {openStore} from '../src/store.js';

let service,base,dir,alice,bob,track,room;
const sockets=[];
async function request(route,{user,method='GET',body,headers={}}={}){const response=await fetch(base+route,{method,headers:{...(user?{Authorization:`Bearer ${user.token}`}:{ } ),...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});const type=response.headers.get('content-type');const data=type?.includes('application/json')?await response.json():Buffer.from(await response.arrayBuffer());return {status:response.status,data,headers:response.headers};}
function wav(seconds=2){const rate=8000,size=rate*seconds*2,b=Buffer.alloc(44+size);b.write('RIFF');b.writeUInt32LE(36+size,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(size,40);for(let n=0;n<rate*seconds;n++)b.writeInt16LE(Math.round(Math.sin(n*2*Math.PI*440/rate)*1000),44+n*2);return b;}
async function connect(user,deviceId){const session=await request('/api/auth/login',{method:'POST',headers:{'X-GlukWave-Client':'native','X-GlukWave-Device':deviceId},body:{email:user.user.email,password:'long-good-passphrase'}});assert.equal(session.status,200);const s=io(base,{auth:{token:session.data.token,deviceId,name:deviceId,kind:'web'},transports:['websocket'],reconnection:false});sockets.push(s);await new Promise((r,j)=>{s.once('connect',r);s.once('connect_error',j);});return s;}
async function socketAck(s,event,payload){return new Promise(resolve=>s.emit(event,payload,resolve));}
before(async()=>{await fs.mkdir(path.join(defaults.root,'work/qa'),{recursive:true});dir=await fs.mkdtemp(path.join(defaults.root,'work/qa/server-test-'));service=await createApp({...defaults,env:'test',storage:'sqlite',dataDir:dir,production:false,turnstileSecret:'',turnstileSiteKey:'',smtp:'',emailVerify:false,adminEmails:['alice@example.test'],spotify:{id:'',secret:''},google:{id:'',secret:''},soundcloud:{id:'',secret:''},soundcloudPublicSearch:false,youtubeKey:'',objectStorage:'local'},{log:pino({level:'silent'})});await new Promise(r=>service.server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${service.server.address().port}`;});
after(async()=>{for(const s of sockets)s.disconnect();await service.close();assert(path.resolve(dir).startsWith(path.resolve(defaults.root,'work/qa')+path.sep));await fs.rm(dir,{recursive:true,force:true,maxRetries:3,retryDelay:100});});

test('real registration, unique identities, protected roles and sessions',async()=>{const a=await request('/api/auth/register',{method:'POST',headers:{'X-GlukWave-Client':'native'},body:{email:'alice@example.test',username:'alice',password:'long-good-passphrase',displayName:'Alice'}});assert.equal(a.status,201);alice=a.data;assert.ok(alice.token);assert.equal(alice.user.role,'admin');assert.equal(alice.user.passwordHash,undefined);const b=await request('/api/auth/register',{method:'POST',headers:{'X-GlukWave-Client':'native'},body:{email:'bob@example.test',username:'bob',password:'long-good-passphrase',displayName:'Bob'}});assert.equal(b.status,201);bob=b.data;assert.equal(bob.user.role,'user');const duplicate=await request('/api/auth/register',{method:'POST',body:{email:'alice@example.test',username:'new_alice',password:'long-good-passphrase'}});assert.equal(duplicate.status,409);const injected=await request('/api/auth/register',{method:'POST',body:{email:'hacker@example.test',username:'hacker',password:'long-good-passphrase',role:'admin'}});assert.equal(injected.status,400);assert.equal((await request('/api/library')).status,401);assert.equal((await request('/api/admin/overview',{user:bob})).status,403);});
test('audio ingestion, protected streams and exact byte ranges',async()=>{const form=new FormData();form.append('file',new Blob([wav()],{type:'audio/wav'}),'test-tone.wav');form.append('title','Verification tone');form.append('artist','GlukWave QA');const r=await request('/api/tracks/upload',{user:alice,method:'POST',body:form});assert.equal(r.status,201,JSON.stringify(r.data));track=r.data.track;assert.ok(Math.abs(track.duration-2)<0.1);assert.equal(track.mediaKey,undefined);assert.equal((await request(`/api/media/${track.id}`)).status,404);assert.equal((await request(`/api/media/${track.id}`,{user:bob})).status,404);const slice=await request(`/api/media/${track.id}`,{user:alice,headers:{Range:'bytes=0-43'}});assert.equal(slice.status,206);assert.equal(slice.data.length,44);assert.equal(slice.data.subarray(0,4).toString(),'RIFF');assert.equal((await request(`/api/media/${track.id}`,{user:alice,headers:{Range:'bytes=999999-'}})).status,416);const malformed=new FormData();malformed.append('file',new Blob(['not music']),'fake.wav');assert.equal((await request('/api/tracks/upload',{user:alice,method:'POST',body:malformed})).status>=400,true);});
test('library mutations persist and public profiles hide private email',async()=>{assert.equal((await request(`/api/library/likes/${track.id}`,{user:alice,method:'PUT',body:{liked:true}})).status,200);const p=await request('/api/playlists',{user:alice,method:'POST',body:{name:'Real collection',trackIds:[track.id]}});assert.equal(p.status,201);assert.equal((await request(`/api/playlists/${p.data.playlist.id}`,{user:bob,method:'PATCH',body:{name:'stolen'}})).status,404);const library=await request('/api/library',{user:alice});assert.deepEqual(library.data.likedIds,[track.id]);assert.equal(library.data.tracks[0].id,track.id);assert.equal((await request(`/api/profile/${alice.user.id}`)).data.user.email,undefined);const comment=await request(`/api/tracks/${track.id}/comments`,{user:alice,method:'POST',body:{text:'Check at this second',position:1}});assert.equal(comment.status,201);assert.equal((await request(`/api/comments/${comment.data.comment.id}`,{user:bob,method:'DELETE'})).status,404);const lyrics=await request(`/api/tracks/${track.id}/lyrics`,{user:alice,method:'PUT',body:{text:'[00:00.20]First line\n[00:01.10]Second line'}});assert.equal(lyrics.status,200);assert.equal(lyrics.data.synchronized,true);assert.equal((await request('/api/search?q=ghbdtn')).data.suggestion,'привет');});
test('audio waveform respects private track access and serves measured PCM data',async()=>{
  assert.equal((await request(`/api/tracks/${track.id}/waveform`)).status,404);assert.equal((await request(`/api/tracks/${track.id}/waveform`,{user:bob})).status,404);
  const result=await request(`/api/tracks/${track.id}/waveform`,{user:alice});assert.equal(result.status,200);assert.equal(result.data.available,true);assert.equal(result.data.source,'decoded-pcm');assert.equal(result.data.duration,track.duration);assert.ok(result.data.samples.some(value=>value>0));assert.ok(result.data.samples.every(value=>value>=0&&value<=1));
  assert.equal(result.headers.get('Cache-Control'),'private, no-store');
});
test('external lyrics are personal and consumer integration messages contain no developer setup',async()=>{
  const external=normalizeYoutube({id:'lyricstest1',snippet:{title:'Lyrics isolation fixture',channelTitle:'QA'}});await service.ctx.persistTracks([external]);
  assert.equal((await request(`/api/tracks/${external.id}/lyrics`,{user:alice,method:'PUT',body:{text:'[00:01.00]Alice personal line'}})).status,200);
  assert.deepEqual((await request(`/api/tracks/${external.id}/lyrics`,{user:bob})).data.lines,[]);
  assert.equal((await request(`/api/tracks/${external.id}/lyrics`,{user:bob,method:'PUT',body:{text:'[00:02.00]Bob personal line'}})).status,200);
  assert.equal((await request(`/api/tracks/${external.id}/lyrics`,{user:alice})).data.lines[0].text,'Alice personal line');
  assert.deepEqual((await request(`/api/tracks/${external.id}/lyrics`)).data.lines,[]);
  const publicConfig=(await request('/api/config')).data;assert.ok(publicConfig.providers.every(provider=>!/(?:API|ключ|\.env)/i.test(provider.reason)));
  const unavailable=await request('/api/integrations/spotify/connect',{user:alice,method:'POST',body:{}});assert.equal(unavailable.status,503);assert.doesNotMatch(unavailable.data.error.message,/(?:API|ключ|\.env)/i);
  assert.ok((await request('/api/admin/overview',{user:alice})).data.integrations.some(provider=>/(?:API|ключ)/i.test(provider.reason)));
});
test('private SoundCloud OAuth metadata remains account-scoped and cannot enter public search',async()=>{
  const privateTrack=normalizeSoundcloud({urn:'soundcloud:tracks:private-fixture',title:'Private provider fixture',sharing:'private',permalink_url:'https://soundcloud.com/qa/private-fixture',user:{username:'QA'}});
  assert.equal(privateTrack.public,false);
  assert.deepEqual(await service.ctx.persistTracks([privateTrack]),[]);
  const [owned]=await service.ctx.persistTracks([privateTrack],{ownerId:alice.user.id});
  assert.equal((await request(`/api/tracks/${owned.id}`)).status,404);
  assert.equal((await request(`/api/tracks/${owned.id}`,{user:bob})).status,404);
  assert.equal((await request(`/api/tracks/${owned.id}`,{user:alice})).status,200);
  assert.equal((await request('/api/search?q=Private')).data.tracks.some(value=>value.id===owned.id),false);
  const [second]=await service.ctx.persistTracks([privateTrack],{ownerId:bob.user.id});
  assert.notEqual(second.id,owned.id);
  assert.equal((await request(`/api/tracks/${second.id}`,{user:bob})).status,200);
  assert.equal((await request('/api/tracks')).data.tracks.some(value=>value.id===owned.id||value.id===second.id),false);
});

test('rooms enforce controller permission, grant streams only while joined',async()=>{const created=await request('/api/rooms',{user:alice,method:'POST',body:{name:'Listening test'}});assert.equal(created.status,201);room=created.data.room;await request('/api/rooms/join',{user:bob,method:'POST',body:{inviteCode:room.inviteCode}});const a=await connect(alice,'alice-device'),b=await connect(bob,'bob-device');await socketAck(a,'room:join',{roomId:room.id});await socketAck(b,'room:join',{roomId:room.id});const denied=await socketAck(b,'room:command',{roomId:room.id,command:'track',trackId:track.id});assert.equal(denied.error.code,'ROOM_PERMISSION');const played=await socketAck(a,'room:command',{roomId:room.id,command:'track',trackId:track.id});assert.equal(played.ok,true);assert.equal(played.state.trackId,track.id);assert.equal((await request(`/api/media/${track.id}`,{user:bob})).status,200);assert.equal((await request(`/api/tracks/${track.id}`,{user:bob})).data.track.playback.offline,false);assert.equal((await request(`/api/media/${track.id}/download`,{user:bob})).status,404);assert.equal((await request(`/api/rooms/${room.id}/members/${bob.user.id}`,{user:alice,method:'PATCH',body:{canControl:true}})).status,200);assert.equal((await socketAck(b,'room:command',{roomId:room.id,command:'pause'})).state.playing,false);await request(`/api/rooms/${room.id}/leave`,{user:bob,method:'POST',body:{}});assert.equal((await request(`/api/media/${track.id}`,{user:bob})).status,404);assert.equal((await socketAck(b,'room:command',{roomId:room.id,command:'play'})).error.code,'ROOM_NOT_FOUND');});
test('device commands are scoped to owner and transfer rolls back on failure',async()=>{const source=await connect(alice,'source-device'),target=await connect(alice,'target-device');await socketAck(source,'device:state',{...initialState(),trackId:track.id,queue:[track.id],playing:true});source.on('device:command',(cmd,ack)=>ack({ok:true}));target.on('device:command',(cmd,ack)=>ack({error:{code:'PLAYBACK_FAILED',message:'Browser denied autoplay'}}));assert.equal((await request('/api/devices/command',{user:bob,method:'POST',body:{deviceId:'source-device',command:'pause'}})).status,409);const failed=await request('/api/devices/command',{user:alice,method:'POST',body:{deviceId:'target-device',fromDeviceId:'source-device',command:'transfer'}});assert.equal(failed.status,409);assert.equal(failed.data.error.code,'PLAYBACK_FAILED');});
test('QR/native challenges are pending, secret-bound and consumed exactly once',async()=>{const c=await request('/api/auth/qr',{method:'POST',body:{deviceName:'Test computer'}});assert.equal(c.status,201);assert.equal((await request(`/api/auth/qr/${c.data.id}?secret=wrong`)).status,404);assert.equal((await request(`/api/auth/qr/${c.data.id}?secret=${c.data.secret}`)).data.status,'pending');assert.equal((await request(`/api/auth/qr/${c.data.id}/approve`,{user:alice,method:'POST',body:{}})).status,200);const r=await request(`/api/auth/qr/${c.data.id}?secret=${c.data.secret}`,{headers:{'X-GlukWave-Client':'native'}});assert.equal(r.data.status,'approved');assert.equal(r.data.user.id,alice.user.id);assert.ok(r.headers.get('set-cookie').includes('HttpOnly'));assert.equal((await request(`/api/auth/qr/${c.data.id}?secret=${c.data.secret}`)).data.status,'expired');const n=await request('/api/auth/native',{method:'POST',body:{method:'email'}});assert.ok(n.data.url.includes('?native='));assert.equal((await request(`/api/auth/native/${n.data.id}/approve`,{user:alice,method:'POST',body:{secret:n.data.secret}})).status,200);assert.ok((await request(`/api/auth/native/${n.data.id}?secret=${n.data.secret}`)).data.token);});
test('password reset invalidates existing sessions and reset link replay',async()=>{await request('/api/auth/forgot',{method:'POST',body:{email:bob.user.email}});const files=await fs.readdir(path.join(dir,'mailbox')),mail=JSON.parse(await fs.readFile(path.join(dir,'mailbox',files[0]),'utf8')),token=new URL(mail.text.match(/https?:\/\/\S+/)[0]).searchParams.get('reset');const r=await request('/api/auth/reset',{method:'POST',body:{token,password:'new-secure-passphrase'}});assert.equal(r.status,200);assert.equal((await request('/api/library',{user:bob})).status,401);assert.equal((await request('/api/auth/reset',{method:'POST',body:{token,password:'another-passphrase'}})).status,400);const login=await request('/api/auth/login',{method:'POST',headers:{'X-GlukWave-Client':'native'},body:{email:bob.user.email,password:'new-secure-passphrase'}});assert.equal(login.status,200);});
test('provider unavailability, SSRF protections, parser and cryptographic invariants',async()=>{assert.equal((await request('/api/integrations/spotify/connect',{user:alice,method:'POST',body:{}})).status,503);assert.equal((await request('/api/tracks/resolve',{user:alice,method:'POST',body:{url:'https://127.0.0.1/secrets'}})).status,400);assert.throws(()=>sourceUrl('https://soundcloud.com.evil.test/name/track'));assert.throws(()=>sourceUrl('http://youtube.com/watch?v=abcdefghijk'));assert.deepEqual(parseRange('bytes=-10',100),{start:90,end:99});assert.equal(parseRange('bytes=0-1,4-5',100),false);assert.deepEqual(parseCSV('title,url\n"hello, world","https://example.test"'),[{title:'hello, world',url:'https://example.test'}]);assert.equal(parseLyrics('[00:01.20][00:04.10]Repeated').lines.length,2);const key='a'.repeat(64),sealed=seal({secret:'value'},key);assert.deepEqual(unseal(sealed,key),{secret:'value'});assert.throws(()=>unseal(sealed,'b'.repeat(64)));const state=applyCommand({...initialState(),trackId:'a',queue:['a','b'],playing:true,updatedAt:0},{command:'pause'},2000);assert.equal(state.position,2);assert.equal(state.playing,false);assert.equal(normalizeSpotify({id:'a',name:'x',album:{}}).playback.offline,false);});
test('playlist limits remain enforced under concurrent creation and import validates malformed rows',async()=>{
  const previous=await service.ctx.store.list('playlists',p=>p.ownerId===alice.user.id),keep=new Set(previous.map(p=>p.id));
  for(let n=previous.length;n<24;n++)await service.ctx.createPlaylist(alice.user.id,{name:`Quota verification ${n}`});
  const results=await Promise.all(Array.from({length:4},(_,n)=>request('/api/playlists',{user:alice,method:'POST',body:{name:`Parallel ${n}`}})));
  assert.equal(results.filter(r=>r.status===201).length,1);
  assert.equal(results.filter(r=>r.status===403).length,3);
  for(const p of await service.ctx.store.list('playlists',p=>p.ownerId===alice.user.id))if(!keep.has(p.id))await service.ctx.store.remove('playlists',p.id);
  await service.ctx.store.update('users',alice.user.id,user=>({...user,plan:'beta'}));
  const invalid=new FormData();invalid.append('file',new Blob(['{broken']),'broken.json');
  assert.equal((await request('/api/integrations/import-file',{user:alice,method:'POST',body:invalid})).status,400);
  const mixed=new FormData();mixed.append('file',new Blob([JSON.stringify([null,{title:'bad',url:1},{title:'Import verification',artist:'QA',url:'https://www.youtube.com/watch?v=abcdefghijk'}])]),'mixed.json');
  const imported=await request('/api/integrations/import-file',{user:alice,method:'POST',body:mixed});
  assert.equal(imported.status,201);assert.equal(imported.data.imported,1);assert.equal(imported.data.errors.length,2);
  const privateId=imported.data.playlist.trackIds[0];
  assert.equal((await request('/api/tracks')).data.tracks.some(t=>t.id===privateId),false);
  assert.equal((await request(`/api/tracks/${privateId}`)).status,404);
  const owned=await request('/api/tracks',{user:alice});assert.equal(owned.data.tracks.find(t=>t.id===track.id).playback.offline,true);
});
test('export imports cannot replace verified metadata in the shared catalog',async()=>{
  const verified=normalizeYoutube({id:'lmnopqrstuv',snippet:{title:'Provider verification fixture',channelTitle:'QA'}});
  await service.ctx.persistTracks([verified]);
  const file=new FormData();file.append('file',new Blob([JSON.stringify([{title:'Untrusted replacement',artist:'Another value',url:verified.sourceUrl}])]),'export.json');
  const imported=await request('/api/integrations/import-file',{user:alice,method:'POST',body:file});
  assert.equal(imported.status,201);assert.deepEqual(imported.data.playlist.trackIds,[verified.id]);
  assert.equal((await request(`/api/tracks/${verified.id}`)).data.track.title,verified.title);
});
test('durable store survives reopen and concurrent updates preserve every change',async()=>{await service.ctx.store.put('test','counter',{id:'counter',value:0});await Promise.all(Array.from({length:20},()=>service.ctx.store.update('test','counter',v=>({...v,value:v.value+1}))));assert.equal((await service.ctx.store.get('test','counter')).value,20);const reopened=await openStore({...defaults,storage:'sqlite',dataDir:dir});assert.equal((await reopened.get('test','counter')).value,20);await reopened.close();assert.equal((await request('/api/auth/logout',{user:alice,method:'POST',body:{}})).status,200);assert.equal((await request('/api/admin/overview',{user:alice})).status,401);});
