import express from 'express';
import Stripe from 'stripe';
import {asyncRoute,fail,id,now} from './util.js';

export function setupBillingWebhook(app,ctx){const {config,store}=ctx;const enabled=!!(config.stripe?.secret&&config.stripe?.webhook&&config.stripe?.price);ctx.billingEnabled=enabled;const stripe=enabled?new Stripe(config.stripe.secret,{maxNetworkRetries:2,timeout:12000}):null;ctx.stripe=stripe;
  const locks=new Map();
  async function synchronize(subscription,created){const uid=subscription.metadata?.userId;if(!uid)return;const work=async()=>{const u=await store.get('users',uid);if(!u)return;const existing=await store.get('billing',uid);if(existing&&existing.subscriptionId!==subscription.id&&existing.status==='active')return;if(existing&&existing.lastEventCreated>created)return;if(!subscription.items?.data.some(i=>i.price.id===config.stripe.price))return;const active=['active','trialing'].includes(subscription.status),record={id:uid,customerId:typeof subscription.customer==='string'?subscription.customer:subscription.customer.id,subscriptionId:subscription.id,status:subscription.status,cancelAtPeriodEnd:subscription.cancel_at_period_end,currentPeriodEnd:subscription.current_period_end||subscription.items.data[0]?.current_period_end||null,lastEventCreated:created,updatedAt:now()};await store.put('billing',uid,record);await store.update('users',uid,v=>({...v,plan:v.plan==='beta'?'beta':active?'unbound':'free'}));ctx.discordPlaybackChanged?.(uid);await ctx.audit('billing.subscription',uid,{status:record.status});ctx.io?.to(`user:${uid}`).emit('notification',{title:'GlukWave Unbound',body:active?'Подписка активна. Все возможности открыты.':'Статус подписки изменился. Проверь оплату в профиле.',url:'/#profile'});};const previous=locks.get(uid)||Promise.resolve(),next=previous.then(work);locks.set(uid,next.catch(()=>{}));await next;}
  app.post('/api/billing/webhook',express.raw({type:'application/json',limit:'256kb'}),asyncRoute(async(req,res)=>{if(!enabled)fail(503,'BILLING_NOT_CONFIGURED','Оплата пока не настроена.');let event;try{event=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],config.stripe.webhook);}catch{fail(400,'WEBHOOK_SIGNATURE','Неверная подпись платёжного события.');}if(await store.get('billingEvents',event.id))return res.json({received:true});if(event.type==='checkout.session.completed'){const session=event.data.object;const checkout=await store.get('billingCheckouts',session.id);if(checkout&&checkout.userId===session.client_reference_id&&session.subscription){const sub=await stripe.subscriptions.retrieve(typeof session.subscription==='string'?session.subscription:session.subscription.id);await synchronize(sub,event.created);}}else if(['customer.subscription.created','customer.subscription.updated','customer.subscription.deleted'].includes(event.type)){const current=await stripe.subscriptions.retrieve(event.data.object.id);await synchronize(current,event.created);}await store.put('billingEvents',event.id,{id:event.id,type:event.type,createdAt:now()});res.json({received:true});}));
}
export function setupBilling(app,ctx){const {store,config,requireAuth,stripe}=ctx;
  app.get('/api/billing/status',requireAuth,asyncRoute(async(req,res)=>{const b=await store.get('billing',req.auth.user.id);res.json({configured:ctx.billingEnabled,plan:req.auth.user.plan,subscription:b?{status:b.status,cancelAtPeriodEnd:b.cancelAtPeriodEnd,currentPeriodEnd:b.currentPeriodEnd}:null});}));
  app.post('/api/billing/checkout',requireAuth,asyncRoute(async(req,res)=>{if(!ctx.billingEnabled)fail(503,'BILLING_NOT_CONFIGURED','Покупка Unbound сейчас недоступна. Попробуй позже.');const uid=req.auth.user.id,existing=await store.get('billing',uid);if(req.auth.user.plan==='beta'||existing&&['active','trialing'].includes(existing.status))fail(409,'PLAN_ACTIVE','Полный доступ уже открыт.');const recent=(await store.list('billingCheckouts',s=>s.userId===uid&&s.expiresAt>Date.now())).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];if(recent)return res.json({url:recent.url});const session=await stripe.checkout.sessions.create({mode:'subscription',client_reference_id:uid,...(existing?.customerId?{customer:existing.customerId}:{customer_email:req.auth.user.email}),line_items:[{price:config.stripe.price,quantity:1}],subscription_data:{metadata:{userId:uid}},metadata:{userId:uid},success_url:`${config.appUrl}/?billing=success#profile`,cancel_url:`${config.appUrl}/?billing=cancel#profile`,allow_promotion_codes:true},{idempotencyKey:`gw-checkout-${uid}-${Math.floor(Date.now()/1800000)}`});await store.put('billingCheckouts',session.id,{id:session.id,userId:uid,url:session.url,expiresAt:session.expires_at*1000,createdAt:now()});res.json({url:session.url});}));
  app.post('/api/billing/portal',requireAuth,asyncRoute(async(req,res)=>{if(!ctx.billingEnabled)fail(503,'BILLING_NOT_CONFIGURED','Оплата пока не настроена.');const b=await store.get('billing',req.auth.user.id);if(!b?.customerId)fail(404,'SUBSCRIPTION_NOT_FOUND','Нет платной подписки.');const portal=await stripe.billingPortal.sessions.create({customer:b.customerId,return_url:`${config.appUrl}/#profile`});res.json({url:portal.url});}));
}
