import {z} from 'zod';
import rateLimit from 'express-rate-limit';
import {asyncRoute,parse,text,id,now,digest,fail} from './util.js';
import {artistsFromTracks,searchText} from './search.js';
import {initialState,liveState} from './rooms.js';

export const safeProfile=user=>user?Object.fromEntries(['id','username','displayName','bio','tags','avatarUrl','bannerUrl','plan','role','createdAt'].map(key=>[key,user[key]])):null;
export const friendKey=(left,right)=>digest([left,right].sort().join(':'));
const defaultPrivacy={showActivity:true,profileStats:false,allowFriendRequests:true};
const defaultTaste={artists:[],onboardingCompleted:false,onboardingStep:0,automatic:true,revision:0};
export function setupCommunity(app,ctx){
 const {store,requireAuth}=ctx,timers=new Map();let closed=false;
 const mutate=rateLimit({windowMs:60000,limit:30,standardHeaders:'draft-8',legacyHeaders:false});
 const own=req=>req.auth.user.id,privacy=async uid=>({...defaultPrivacy,...await store.get('privacy',uid)});
 ctx.areFriends=async(a,b)=>!!await store.get('friendships',friendKey(a,b));
 ctx.profilePrivacy=privacy;
 ctx.notifyFriends=async uid=>{for(const edge of await store.list('friendships',value=>value.userIds.includes(uid)))for(const friendId of edge.userIds)if(friendId!==uid)ctx.io?.to(`user:${friendId}`).emit('friends:changed',{});};
 const changed=(...uids)=>{for(const uid of new Set(uids)){ctx.io?.to(`user:${uid}`).emit('friends:changed',{});void ctx.notifyFriends(uid).catch(()=>{});}};
 async function catalogue(user){const tracks=await store.list('tracks',track=>track.public||track.uploadedBy===user?.id);return tracks.filter(track=>track.public||track.uploadedBy===user?.id);}
 async function rememberArtists(artists,user){for(const artist of artists){const {trackIds,...metadata}=artist;if(!artist.name||!artist.id)continue;let publicArtist=!trackIds?.length;for(const tid of trackIds||[])if(await ctx.canAccessTrack(await store.get('tracks',tid),null)){publicArtist=true;break;}await store.update('artists',artist.id,previous=>({...metadata,artwork:artist.artwork||'',public:publicArtist||previous?.public||false,ownerIds:[...new Set([...previous?.ownerIds||[],...(!publicArtist&&user?[user.id]:[])])],updatedAt:now()}));}return artists;}
 const genresFor=tracks=>[...new Set(tracks.flatMap(track=>[track.genre,...track.tags||[]]).filter(value=>typeof value==='string'&&value.length>1&&value.length<60))].sort().slice(0,100);
 app.get('/api/artists',mutate,asyncRoute(async(req,res)=>{
  const q=parse(z.string().trim().max(200),req.query.q||''),source=parse(z.enum(['all','youtube','soundcloud','spotify','local']),req.query.source||'all');
  let tracks=await catalogue(req.auth?.user),providerArtists=[];
  if(q){const requested=ctx.providerConfiguration().filter(provider=>provider.searchAvailable&&(source==='all'||source===provider.id));const results=await Promise.allSettled(requested.map(provider=>ctx.searchProvider(provider.id,q,req.auth?.user.id)));for(const result of results)if(result.status==='fulfilled'){tracks.push(...result.value);providerArtists.push(...result.value.artists||[]);}}
  tracks=tracks.filter(track=>source==='all'||source===track.source);const artists=await rememberArtists(artistsFromTracks(tracks,q,providerArtists),req.auth?.user);res.set('Cache-Control','private, no-store').json({artists,genres:genresFor(tracks)});
 }));
 app.get('/api/artists/:id',asyncRoute(async(req,res)=>{
  const artist=await store.get('artists',req.params.id);if(!artist||!artist.public&&!artist.ownerIds?.includes(req.auth?.user.id))fail(404,'ARTIST_NOT_FOUND','Артист не найден.');const tracks=(await catalogue(req.auth?.user)).filter(track=>track.source===artist.source&&(track.artists||[{name:track.artist}]).some(value=>searchText(value.name)===searchText(artist.name)));res.set('Cache-Control','private, no-store').json({artist:((({public:visible,ownerIds,updatedAt,...value})=>value)(artist)),tracks:tracks.map(track=>ctx.publicTrack(track,req.auth?.user))});
 }));
 async function learned(uid,taste){if(!taste.automatic)return [];const stats=await store.list('listeningStats',row=>row.userId===uid&&(!taste.learnedResetAt||row.updatedAt>taste.learnedResetAt)),scores=new Map();for(const row of stats){if(!row.artist)continue;const key=searchText(row.artist);scores.set(key,{name:row.artist,score:(scores.get(key)?.score||0)+row.plays+row.seconds/60-(row.skips||0)*2,source:row.source,artwork:row.artwork||''});}const library=await store.get('libraries',uid);for(const tid of library?.likedIds||[]){if(taste.learnedResetAt&&!(library.likedAt?.[tid]>taste.learnedResetAt))continue;const track=await store.get('tracks',tid);if(track?.artist){const key=searchText(track.artist),previous=scores.get(key)||{name:track.artist,score:0,source:track.source,artwork:track.artistArtwork||''};scores.set(key,{...previous,score:previous.score+5});}}return [...scores.values()].filter(value=>value.score>0).sort((a,b)=>b.score-a.score).slice(0,20).map(({score,...value})=>({...value,id:'learned-'+digest(value.name).slice(0,24)}));}
 async function tasteEnvelope(uid){const taste={...defaultTaste,...await store.get('taste',uid)};return {taste,learnedArtists:await learned(uid,taste)};}
 app.get('/api/taste',requireAuth,asyncRoute(async(req,res)=>res.set('Cache-Control','no-store').json(await tasteEnvelope(own(req)))));
 const artistSchema=z.object({id:text(200),name:text(300),source:text(30),artwork:z.string().max(2048).optional(),sourceUrl:z.string().max(2048).optional(),trackIds:z.array(text(200)).max(1000).optional()}).passthrough();
 app.put('/api/taste',requireAuth,mutate,asyncRoute(async(req,res)=>{
  const body=parse(z.object({artists:z.array(artistSchema).max(100).optional(),onboardingCompleted:z.boolean().optional(),onboardingStep:z.number().int().min(0).max(3).optional(),automatic:z.boolean().optional()}).strict(),req.body);let artists;
  if(body.artists){artists=[];for(const item of body.artists){const known=await store.get('artists',item.id);if(!known||!known.public&&!known.ownerIds?.includes(own(req)))fail(400,'ARTIST_NOT_FOUND','Сначала найди артиста в поиске.');if(!artists.some(value=>value.id===known.id)){const {updatedAt,public:visible,ownerIds,...artist}=known;artists.push(artist);}}}
  await ctx.withLock('taste:'+own(req),()=>store.update('taste',own(req),previous=>({...defaultTaste,...previous,...body,...(artists?{artists}:{}),id:own(req),revision:(previous?.revision||0)+1,updatedAt:now()})));const response=await tasteEnvelope(own(req));ctx.io?.to(`user:${own(req)}`).emit('taste:changed',response);res.json(response);
 }));
 app.delete('/api/taste/learned',requireAuth,asyncRoute(async(req,res)=>{await store.update('taste',own(req),previous=>({...defaultTaste,...previous,id:own(req),learnedResetAt:now(),revision:(previous?.revision||0)+1}));const response=await tasteEnvelope(own(req));ctx.io?.to(`user:${own(req)}`).emit('taste:changed',response);res.json(response);}));
 app.get('/api/recommendations',asyncRoute(async(req,res)=>{
  const mood=parse(z.enum(['personal','relax','focus','energy','dream']),req.query.mood||'personal'),uid=req.auth?.user.id,taste=uid?(await tasteEnvelope(uid)):{taste:defaultTaste,learnedArtists:[]},library=uid?await store.get('libraries',uid):null,tracks=await catalogue(req.auth?.user);
  const selected=new Set(taste.taste.artists.map(artist=>searchText(artist.name))),inferred=new Set(taste.learnedArtists.map(artist=>searchText(artist.name))),liked=new Set(library?.likedIds||[]),history=new Set(library?.history?.map(entry=>entry.trackId)||[]),moods={relax:/ambient|chill|relax|lo.?fi|jazz|спокой|эмбиент/i,focus:/instrumental|piano|classic|focus|ambient|инструмент|классик/i,energy:/dance|electronic|rock|hip.?hop|pop|энерг|танц/i,dream:/dream|shoegaze|ambient|indie|электро/i};
  const scored=tracks.map(track=>{const names=(track.artists||[{name:track.artist}]).map(artist=>searchText(artist.name)),score=names.some(name=>selected.has(name))?20:0;return {track,score:score+(names.some(name=>inferred.has(name))?8:0)+(liked.has(track.id)?6:0)+(history.has(track.id)?3:0)+(mood!=='personal'&&moods[mood].test([track.genre,...track.tags||[]].join(' '))?10:0)};}).sort((a,b)=>b.score-a.score||String(b.track.createdAt||'').localeCompare(a.track.createdAt||''));
  res.set('Cache-Control','private, no-store').json({tracks:scored.slice(0,60).map(({track})=>ctx.publicTrack(track,req.auth?.user)),artists:taste.taste.artists,genres:genresFor(tracks),reason:!tracks.length?'empty':selected.size?'taste':history.size?'history':'catalogue'});
 }));
 app.get('/api/account/privacy',requireAuth,asyncRoute(async(req,res)=>res.json({privacy:await privacy(own(req))})));
 app.patch('/api/account/privacy',requireAuth,asyncRoute(async(req,res)=>{const body=parse(z.object({showActivity:z.boolean().optional(),profileStats:z.boolean().optional(),allowFriendRequests:z.boolean().optional()}).strict(),req.body);await store.update('privacy',own(req),previous=>({...defaultPrivacy,...previous,...body,id:own(req)}));changed(own(req));res.json({privacy:await privacy(own(req))});}));
 async function activity(viewer,friend){
  if(!(await privacy(friend.id)).showActivity)return undefined;
  const output=await ctx.friendOutput?.(friend.id);if(!output)return undefined;
  const track=output.state.trackId?await store.get('tracks',output.state.trackId):null,allowed=track&&await ctx.canAccessTrack(track,viewer);
  const jam=(await store.list('rooms',room=>room.type==='jam'&&room.ownerId===friend.id&&room.expiresAt>Date.now()))[0];
  return {track:allowed?ctx.publicTrack(track,viewer):null,position:allowed?output.state.position:0,playing:!!allowed&&output.state.playing,device:output.device||null,jamId:jam?.id||null};
 }
 app.get('/api/friends',requireAuth,asyncRoute(async(req,res)=>{
  const uid=own(req),edges=await store.list('friendships',edge=>edge.userIds.includes(uid)),requests=await store.list('friendRequests',request=>request.fromId===uid||request.toId===uid),friends=[];
  for(const edge of edges){const user=await store.get('users',edge.userIds.find(value=>value!==uid));if(!user||user.blocked)continue;friends.push({user:safeProfile(user),online:!!ctx.userOnline?.(user.id),activity:await activity(req.auth.user,user)});}
  const incoming=[],outgoing=[];for(const request of requests){const user=await store.get('users',request.fromId===uid?request.toId:request.fromId);if(!user||user.blocked)continue;(request.toId===uid?incoming:outgoing).push({id:request.id,[request.toId===uid?'from':'to']:safeProfile(user)});}
  res.set('Cache-Control','no-store').json({friends,incoming,outgoing});
 }));
 app.get('/api/users/search',requireAuth,mutate,asyncRoute(async(req,res)=>{const q=searchText(parse(z.string().trim().min(2).max(100),req.query.q)),uid=own(req),matches=(await store.list('users',user=>!user.blocked&&user.id!==uid&&(searchText(user.username).includes(q)||searchText(user.displayName).includes(q)))).slice(0,30),users=[];for(const user of matches){const key=friendKey(uid,user.id);users.push({...safeProfile(user),relationship:await store.get('friendships',key)?'friend':await store.get('friendRequests',key)?'pending':'none'});}res.set('Cache-Control','no-store').json({users});}));
 app.post('/api/friends/requests',requireAuth,mutate,asyncRoute(async(req,res)=>{const {userId}=parse(z.object({userId:text(100)}).strict(),req.body),uid=own(req),key=friendKey(uid,userId);if(uid===userId)fail(400,'VALIDATION','Выбери другого пользователя.');const user=await store.get('users',userId);if(!user||user.blocked||!(await privacy(userId)).allowFriendRequests)fail(404,'USER_NOT_FOUND','Пользователь не принимает заявки.');const request=await ctx.withLock('friend:'+key,async()=>{if(await store.get('friendships',key))fail(409,'ALREADY_FRIENDS','Вы уже друзья.');const pending=await store.get('friendRequests',key);if(pending)return pending;if((await store.list('friendRequests',entry=>entry.fromId===uid)).length>=100)fail(429,'RATE_LIMIT','Сначала дождись ответа на отправленные заявки.');const entry={id:key,fromId:uid,toId:userId,createdAt:now()};await store.create('friendRequests',key,entry);return entry;});changed(uid,userId);res.status(201).json({request});}));
 app.put('/api/friends/requests/:id',requireAuth,mutate,asyncRoute(async(req,res)=>{const {accept}=parse(z.object({accept:z.boolean()}).strict(),req.body),uid=own(req);await ctx.withLock('friend:'+req.params.id,async()=>{const request=await store.get('friendRequests',req.params.id);if(!request||request.toId!==uid)fail(404,'FRIEND_REQUEST_NOT_FOUND','Заявка не найдена.');if(accept){for(const userId of [uid,request.fromId])if((await store.list('friendships',edge=>edge.userIds.includes(userId))).length>=500)fail(403,'FRIEND_LIMIT','Достигнут лимит друзей.');await store.put('friendships',request.id,{id:request.id,userIds:[request.fromId,uid],createdAt:now()});}await store.remove('friendRequests',request.id);changed(uid,request.fromId);});res.json({ok:true});}));
 app.delete('/api/friends/:userId',requireAuth,asyncRoute(async(req,res)=>{const uid=own(req),other=req.params.userId,key=friendKey(uid,other);await ctx.withLock('friend:'+key,async()=>{await store.remove('friendships',key);await store.remove('friendRequests',key);for(const room of await store.list('rooms',room=>room.type==='jam'&&[uid,other].includes(room.ownerId)&&room.members.some(member=>member.userId===uid)&&room.members.some(member=>member.userId===other))){const guest=room.ownerId===uid?other:uid;await ctx.leaveJam(guest,room.id);}});changed(uid,other);res.json({ok:true});}));
 ctx.closeJam=async room=>{clearTimeout(timers.get(room.id));timers.delete(room.id);ctx.io?.to(`room:${room.id}`).emit('room:closed',{roomId:room.id});for(const member of room.members)await ctx.leaveAccountRoom?.(member.userId,room.id);await store.remove('rooms',room.id);ctx.io?.in(`room:${room.id}`).socketsLeave(`room:${room.id}`);for(const message of await store.list('messages',entry=>entry.roomId===room.id))await store.remove('messages',message.id);changed(...room.members.map(member=>member.userId));};
 ctx.leaveJam=async(uid,rid)=>{const room=await store.get('rooms',rid);if(room?.type!=='jam')return false;if(room.ownerId===uid)await ctx.closeJam(room);else{await ctx.leaveAccountRoom?.(uid,rid);await store.update('rooms',rid,previous=>previous?{...previous,members:previous.members.filter(member=>member.userId!==uid)}:undefined);ctx.io?.in(`user:${uid}`).socketsLeave(`room:${rid}`);await ctx.refreshRoomPresence?.(rid);}return true;};
 ctx.jamDisconnected=uid=>{if(closed)return;void (async()=>{if(ctx.userOnline?.(uid))return;for(const room of await store.list('rooms',room=>room.type==='jam'&&room.ownerId===uid)){if(timers.has(room.id))continue;const timer=setTimeout(()=>{timers.delete(room.id);void (async()=>{const fresh=await store.get('rooms',room.id);if(fresh&&!ctx.userOnline?.(uid))await ctx.closeJam(fresh);})().catch(error=>ctx.log.warn({message:error.message},'Jam cleanup failed'));},30000);timer.unref();timers.set(room.id,timer);}})().catch(()=>{});};
 ctx.ensureJam=async host=>{const uid=host.id;const room=await ctx.withLock('jams:'+uid,async()=>{const old=(await store.list('rooms',room=>room.type==='jam'&&room.ownerId===uid))[0];if(old&&old.expiresAt>Date.now())return old;if(old)await ctx.closeJam(old);const output=await ctx.friendOutput?.(uid),user=host,room={id:id(),type:'jam',visibility:'private',name:user.displayName,ownerId:uid,members:[{userId:uid,displayName:user.displayName,avatarUrl:user.avatarUrl,role:'owner',canControl:true}],state:output?.state||initialState(),createdAt:now(),expiresAt:Date.now()+24*3600000};await store.create('rooms',room.id,room);return room;});changed(uid);return room;};
 app.post('/api/jams',requireAuth,mutate,asyncRoute(async(req,res)=>{parse(z.object({}).strict(),req.body||{});res.status(201).json({room:await ctx.ensureJam(req.auth.user)});}));
 ctx.joinJam=async(member,rid)=>{const uid=member.id,active=await store.get('connect',uid);if(active?.roomId&&active.roomId!==rid){const destination=await store.get('rooms',rid);if(destination?.type!=='jam'||!await ctx.areFriends(uid,destination.ownerId))fail(404,'JAM_NOT_FOUND','Джем недоступен.');await ctx.leaveJam(uid,active.roomId);}const room=await ctx.withLock('room:'+rid,async()=>{const previous=await store.get('rooms',rid);if(previous?.type!=='jam'||previous.expiresAt<=Date.now()||!await ctx.areFriends(uid,previous.ownerId))fail(404,'JAM_NOT_FOUND','Джем доступен только друзьям ведущего.');if(previous.members.some(member=>member.userId===uid))return previous;if(previous.members.length>=5)fail(403,'JAM_FULL','В джеме уже пять участников.');const user=member,next={...previous,members:[...previous.members,{userId:uid,displayName:user.displayName,avatarUrl:user.avatarUrl,role:'member',canControl:false}]};await store.put('rooms',rid,next);return next;});ctx.io?.to(`room:${rid}`).emit('room:members',{roomId:rid,members:room.members});return {...room,state:liveState(room.state)};};
 app.post('/api/jams/:id/join',requireAuth,mutate,asyncRoute(async(req,res)=>{parse(z.object({}).strict(),req.body||{});res.json({room:await ctx.joinJam(req.auth.user,req.params.id)});}));
 app.get('/api/jams/:id',requireAuth,asyncRoute(async(req,res)=>{const room=await ctx.requireRoom(req.params.id,own(req));if(room.type!=='jam')fail(404,'JAM_NOT_FOUND','Джем не найден.');res.json({room:ctx.decorateRoom?await ctx.decorateRoom(room):room});}));
 app.post('/api/jams/:id/pause',requireAuth,asyncRoute(async(req,res)=>{const {paused}=parse(z.object({paused:z.boolean()}).strict(),req.body),room=await ctx.requireRoom(req.params.id,own(req));if(room.type!=='jam'||room.ownerId===own(req))fail(403,'ROOM_PERMISSION','Ведущий управляет общим воспроизведением.');res.json({connect:await ctx.pauseJamListener(own(req),room,paused)});}));
 const prune=setInterval(()=>{void (async()=>{for(const room of await store.list('rooms',room=>room.type==='jam'&&room.expiresAt<=Date.now()))await ctx.closeJam(room);})().catch(error=>ctx.log.warn({message:error.message},'Jam cleanup failed'));},300000);prune.unref();ctx.closeCommunity=()=>{closed=true;clearInterval(prune);for(const timer of timers.values())clearTimeout(timer);timers.clear();};
}
