import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import multer from 'multer';
import {parseFile} from 'music-metadata';
import {S3Client,PutObjectCommand,GetObjectCommand,DeleteObjectCommand} from '@aws-sdk/client-s3';
import {z} from 'zod';
import {id,now,parse,text,fail,asyncRoute,publicUser} from './util.js';
import {planLimits} from './plans.js';

const audioExtensions={'.mp3':'audio/mpeg','.flac':'audio/flac','.wav':'audio/wav','.ogg':'audio/ogg','.opus':'audio/ogg','.m4a':'audio/mp4','.aac':'audio/aac','.mp4':'audio/mp4'};
function imageType(b){if(b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)return {ext:'.jpg',mime:'image/jpeg'};if(b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return {ext:'.png',mime:'image/png'};if(/^GIF8[79]a$/.test(b.subarray(0,6).toString()))return {ext:'.gif',mime:'image/gif'};if(b.subarray(0,4).toString()==='RIFF'&&b.subarray(8,12).toString()==='WEBP')return {ext:'.webp',mime:'image/webp'};return null;}
export function parseRange(value,size){if(!value)return null;const m=value.match(/^bytes=(\d*)-(\d*)$/);if(!m||(!m[1]&&!m[2]))return false;let start,end;if(!m[1]){const count=Number(m[2]);if(count<=0)return false;start=Math.max(0,size-count);end=size-1;}else{start=Number(m[1]);end=m[2]?Math.min(Number(m[2]),size-1):size-1;}return Number.isSafeInteger(start)&&Number.isSafeInteger(end)&&start>=0&&start<size&&end>=start?{start,end}:false;}

export function setupMedia(app,ctx){
  const {store,config,requireAuth}=ctx;
  const mediaDir=path.join(config.dataDir,'media'),tempDir=path.join(config.dataDir,'tmp');fs.mkdirSync(mediaDir,{recursive:true});fs.mkdirSync(tempDir,{recursive:true});
  const upload=multer({dest:tempDir,limits:{fileSize:config.uploadLimitMB*1024*1024,files:1,fields:8,fieldSize:4096}});
  const profileUpload=multer({dest:tempDir,limits:{fileSize:8*1024*1024,files:1,fields:2}});
  const importUpload=multer({dest:tempDir,limits:{fileSize:4*1024*1024,files:1,fields:3}});
  ctx.importUpload=importUpload;
  const s3=config.objectStorage==='r2'?new S3Client({region:'auto',endpoint:config.r2.endpoint,credentials:{accessKeyId:config.r2.accessKey,secretAccessKey:config.r2.secretKey}}):null;
  async function putFile(temp,key,mime,size){if(s3){await s3.send(new PutObjectCommand({Bucket:config.r2.bucket,Key:key,Body:fs.createReadStream(temp),ContentType:mime,ContentLength:size}));await fsp.unlink(temp);}else{const target=path.join(mediaDir,key);await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.rename(temp,target);}}
  async function deleteFile(key){if(s3)await s3.send(new DeleteObjectCommand({Bucket:config.r2.bucket,Key:key}));else await fsp.unlink(path.join(mediaDir,key)).catch(()=>{});}
  ctx.deleteMedia=deleteFile;
  ctx.openAudioStream=async track=>{
    if(track.source!=='local'||!track.mediaKey)fail(404,'TRACK_NOT_FOUND','Трек не найден.');
    if(s3)return (await s3.send(new GetObjectCommand({Bucket:config.r2.bucket,Key:track.mediaKey}))).Body;
    const location=path.resolve(mediaDir,track.mediaKey);if(!location.startsWith(path.resolve(mediaDir)+path.sep))fail(404,'TRACK_NOT_FOUND','Трек не найден.');
    await fsp.access(location);return fs.createReadStream(location,{highWaterMark:65536});
  };
  const clean=async file=>{if(file)await fsp.unlink(file.path).catch(()=>{});};
  async function authorizedTrack(track,user,download=false){if(!track)return false;if(track.public&&track.source!=='local')return !download;if(!user)return false;if(track.uploadedBy===user.id||user.role==='admin')return true;if(download)return false;const rooms=await store.list('rooms',r=>r.members.some(m=>m.userId===user.id));return rooms.some(r=>r.state.trackId===track.id||r.state.queue.includes(track.id));}
  ctx.canAccessTrack=authorizedTrack;
  ctx.publicTrack=(t,user)=>{const {mediaKey,mime,size,waveformUrl,uploadedBy,public:visible,...value}=t;return {...value,...(t.source==='local'?{uploadedBy,...(user&&user.id!==uploadedBy&&user.role!=='admin'?{playback:{...value.playback,offline:false}}:{})}:{} )};};
  app.post('/api/tracks/upload',requireAuth,upload.single('file'),asyncRoute(ctx.quotaRoute('upload',async(req,res)=>{const file=req.file;if(!file)fail(400,'FILE_REQUIRED','Выбери аудиофайл.');let savedKey=null;try{const b=parse(z.object({title:text(200).optional(),artist:text(200).optional(),album:z.string().max(200).optional()}).strict(),req.body);const ext=path.extname(file.originalname).toLowerCase();if(!audioExtensions[ext])fail(415,'AUDIO_FORMAT','Поддерживаются MP3, FLAC, WAV, OGG, OPUS, M4A и AAC.');const user=req.auth.user,owned=await store.list('tracks',t=>t.source==='local'&&t.uploadedBy===user.id);const limit=user.plan==='free'?200:10000;if(owned.length>=limit)fail(403,'PLAN_LIMIT','Лимит загруженных треков достигнут.');const metadata=await parseFile(file.path,{duration:true});if(!metadata.format.codec&&!metadata.format.container)fail(415,'INVALID_AUDIO','Файл не распознан как аудио.');if(!metadata.format.duration||metadata.format.duration>86400)fail(415,'INVALID_AUDIO','Не удалось прочитать длительность аудио.');const tid=id(),key=`audio/${tid}${ext}`,track={id:tid,title:b.title||metadata.common.title||path.basename(file.originalname,ext),artist:b.artist||metadata.common.artist||'Неизвестный исполнитель',album:b.album||metadata.common.album||'',artwork:'',duration:metadata.format.duration,source:'local',sourceId:tid,sourceUrl:'',playback:{kind:'audio',url:`/api/media/${tid}`,offline:true},createdAt:now(),uploadedBy:user.id,public:false,mediaKey:key,mime:audioExtensions[ext],size:file.size};await putFile(file.path,key,track.mime,file.size);savedKey=key;const cover=metadata.common.picture?.[0];if(cover&&cover.data.length<5*1024*1024){const type=imageType(cover.data);if(type){const aid=id(),ak=`images/${aid}${type.ext}`,tmp=path.join(tempDir,aid);await fsp.writeFile(tmp,cover.data);await putFile(tmp,ak,type.mime,cover.data.length);await store.create('assets',aid,{id:aid,key:ak,mime:type.mime,size:cover.data.length,ownerId:user.id,createdAt:now()});track.artwork=`/api/profile-assets/${aid}`;}}await store.create('tracks',tid,track);await ctx.audit('track.upload',user.id,{trackId:tid,bytes:file.size});res.status(201).json({track:ctx.publicTrack(track)});}catch(err){await clean(file);if(savedKey)await deleteFile(savedKey);throw err;}})));
  app.get('/api/tracks/:id/playback',asyncRoute(async(req,res)=>{const t=await store.get('tracks',req.params.id);if(!await authorizedTrack(t,req.auth?.user))fail(404,'TRACK_NOT_FOUND','Трек не найден.');res.json({playback:ctx.publicTrack(t,req.auth?.user).playback});}));
  async function stream(req,res,download=false){const t=await store.get('tracks',req.params.id);if(!t||t.source!=='local'||!await authorizedTrack(t,req.auth?.user,download))fail(404,'TRACK_NOT_FOUND','Трек не найден.');if(download&&!t.playback.offline)fail(403,'OFFLINE_UNAVAILABLE','Эта площадка не предоставляет скачивание.');const range=parseRange(req.headers.range,t.size);if(range===false)return res.status(416).set('Content-Range',`bytes */${t.size}`).end();const headers={'Content-Type':t.mime,'Accept-Ranges':'bytes','Cache-Control':'private, no-store','Content-Length':String(range?range.end-range.start+1:t.size),'X-Content-Type-Options':'nosniff'};if(range)headers['Content-Range']=`bytes ${range.start}-${range.end}/${t.size}`;if(download)headers['Content-Disposition']=`attachment; filename="glukwave-${t.id}${path.extname(t.mediaKey)}"`;let readable;if(s3){const response=await s3.send(new GetObjectCommand({Bucket:config.r2.bucket,Key:t.mediaKey,...(range?{Range:`bytes=${range.start}-${range.end}`}:{})}));readable=response.Body;}else{await fsp.access(path.join(mediaDir,t.mediaKey));readable=fs.createReadStream(path.join(mediaDir,t.mediaKey),range||{});}res.status(range?206:200).set(headers);if(req.method==='HEAD'){readable.destroy();return res.end();}readable.on('error',err=>{ctx.log.error({err},'Media stream failed');res.destroy();});res.on('close',()=>readable.destroy());readable.pipe(res);}
  app.get('/api/media/:id',asyncRoute((req,res)=>stream(req,res)));
  app.get('/api/media/:id/download',asyncRoute((req,res)=>stream(req,res,true)));
  app.delete('/api/tracks/:id',requireAuth,asyncRoute(async(req,res)=>{const t=await store.get('tracks',req.params.id);if(!t||t.uploadedBy!==req.auth.user.id&&req.auth.user.role!=='admin')fail(404,'TRACK_NOT_FOUND','Трек не найден.');if(t.mediaKey)await deleteFile(t.mediaKey);await store.remove('tracks',t.id);await store.remove('waveforms',t.id);for(const p of await store.list('playlists',p=>p.trackIds.includes(t.id)))await store.update('playlists',p.id,v=>({...v,trackIds:v.trackIds.filter(x=>x!==t.id),updatedAt:now()}));res.json({ok:true});}));
  async function removeProfileAsset(url,uid){if(!url?.startsWith('/api/profile-assets/'))return;const aid=url.split('/').at(-1),asset=await store.get('assets',aid);if(asset?.ownerId!==uid)return;try{await deleteFile(asset.key);await store.remove('assets',aid);}catch(err){await store.put('mediaCleanup',aid,{id:aid,ownerId:uid,key:asset.key,createdAt:now()});ctx.log.warn({assetId:aid,message:err.message},'Profile media cleanup queued');}}
  ctx.cleanProfileAsset=removeProfileAsset;
  ctx.retryMediaCleanup=async()=>{for(const entry of (await store.list('mediaCleanup')).slice(0,100)){await deleteFile(entry.key);await store.remove('assets',entry.id);await store.remove('mediaCleanup',entry.id);}};
  app.post('/api/profile/media',requireAuth,profileUpload.single('file'),asyncRoute(async(req,res)=>{const file=req.file;if(!file)fail(400,'FILE_REQUIRED','Выбери картинку.');let aid,key,committed=false;try{const kind=parse(z.enum(['avatar','banner']),req.body.kind),b=await fsp.readFile(file.path),type=imageType(b);if(!type)fail(415,'IMAGE_FORMAT','Поддерживаются PNG, JPEG, GIF и WebP.');const animated=type.ext==='.gif'||type.ext==='.webp'&&b.includes(Buffer.from('ANIM'))||type.ext==='.png'&&b.includes(Buffer.from('acTL'));if(animated&&!planLimits(req.auth.user).animatedProfile)fail(403,'PLAN_LIMIT','Анимированные фото доступны в Unbound.');aid=id();key=`images/${aid}${type.ext}`;await putFile(file.path,key,type.mime,file.size);await store.create('assets',aid,{id:aid,key,mime:type.mime,size:file.size,ownerId:req.auth.user.id,createdAt:now()});await ctx.withLock('profile-media:'+req.auth.user.id,async()=>{const previous=await store.get('users',req.auth.user.id),user=await store.update('users',previous.id,v=>({...v,[`${kind}Url`]:`/api/profile-assets/${aid}`}));committed=true;await removeProfileAsset(previous[`${kind}Url`],user.id);res.json({user:publicUser(user)});});}catch(err){await clean(file);if(key&&!committed){await deleteFile(key).catch(()=>{});if(aid)await store.remove('assets',aid);}throw err;}}));
  app.delete('/api/profile/media/:kind',requireAuth,asyncRoute(async(req,res)=>{const kind=parse(z.enum(['avatar','banner']),req.params.kind);await ctx.withLock('profile-media:'+req.auth.user.id,async()=>{const previous=await store.get('users',req.auth.user.id),user=await store.update('users',previous.id,v=>({...v,[`${kind}Url`]:''}));await removeProfileAsset(previous[`${kind}Url`],user.id);await ctx.audit('profile.media.remove',user.id,{kind});res.json({user:publicUser(user)});});}));
  app.get('/api/profile-assets/:id',asyncRoute(async(req,res)=>{const a=await store.get('assets',req.params.id);if(!a)fail(404,'IMAGE_NOT_FOUND','Картинка не найдена.');res.set({'Content-Type':a.mime,'Content-Length':String(a.size),'Cache-Control':'public, max-age=86400','Cross-Origin-Resource-Policy':'cross-origin','X-Content-Type-Options':'nosniff'});if(s3){const r=await s3.send(new GetObjectCommand({Bucket:config.r2.bucket,Key:a.key}));r.Body.on('error',()=>res.destroy());r.Body.pipe(res);}else res.sendFile(path.join(mediaDir,a.key));}));
}
