import {browserLanguage,languageCodes} from './locale.js';

const order=['en','kk','uk','de','es'];
const groups=[
  ['AUTH_REQUIRED','Sign in to your account.','Аккаунтыңызға кіріңіз.','Увійдіть у свій обліковий запис.','Melde dich bei deinem Konto an.','Inicia sesión en tu cuenta.'],
  ['EMAIL_UNVERIFIED','Verify your email address to continue.','Жалғастыру үшін поштаңызды растаңыз.','Підтвердьте адресу пошти, щоб продовжити.','Bestätige deine E-Mail-Adresse, um fortzufahren.','Verifica tu correo para continuar.'],
  ['ADMIN_REQUIRED','Administrator access is required.','Әкімші рұқсаты қажет.','Потрібен доступ адміністратора.','Administratorzugriff ist erforderlich.','Se requiere acceso de administrador.'],
  ['INVALID_CREDENTIALS','Email or password is incorrect.','Электрондық пошта немесе құпиясөз қате.','Неправильна пошта або пароль.','E-Mail oder Passwort ist falsch.','El correo o la contraseña son incorrectos.'],
  ['ACCOUNT_BLOCKED','This account is blocked.','Бұл аккаунт бұғатталған.','Цей обліковий запис заблоковано.','Dieses Konto ist gesperrt.','Esta cuenta está bloqueada.'],
  ['SESSION_CHANGED','Your account has changed. Open settings again.','Аккаунт өзгерді. Параметрлерді қайта ашыңыз.','Обліковий запис змінився. Відкрийте налаштування знову.','Dein Konto hat sich geändert. Öffne die Einstellungen erneut.','Tu cuenta ha cambiado. Vuelve a abrir los ajustes.'],
  ['ACCOUNT_EXISTS USERNAME_TAKEN','This email or username is already in use.','Бұл пошта немесе пайдаланушы аты қолданылуда.','Ця пошта або ім’я користувача вже зайняті.','Diese E-Mail-Adresse oder dieser Benutzername wird bereits verwendet.','Este correo o nombre de usuario ya está en uso.'],
  ['VALIDATION INVALID_COMMAND POSITION_REQUIRED VOLUME_REQUIRED','Check the entered values.','Енгізілген деректерді тексеріңіз.','Перевірте введені дані.','Überprüfe deine Eingaben.','Revisa los datos introducidos.'],
  ['NOT_FOUND TRACK_NOT_FOUND PLAYLIST_NOT_FOUND PROFILE_NOT_FOUND USER_NOT_FOUND COMMENT_NOT_FOUND MEMBER_NOT_FOUND IMAGE_NOT_FOUND SESSION_NOT_FOUND ARTIST_NOT_FOUND FRIEND_REQUEST_NOT_FOUND JAM_NOT_FOUND','The requested item was not found.','Сұралған элемент табылмады.','Запитаний елемент не знайдено.','Der angeforderte Eintrag wurde nicht gefunden.','No se encontró el elemento solicitado.'],
  ['ORIGIN_DENIED','Requests from this website are not allowed.','Бұл сайттан сұрау жіберуге рұқсат жоқ.','Запити з цього сайту не дозволені.','Anfragen von dieser Website sind nicht erlaubt.','No se permiten solicitudes desde este sitio.'],
  ['RATE_LIMIT CHAT_LIMIT COMMENT_LIMIT REALTIME_LIMIT','Too many requests. Try again later.','Сұраулар тым көп. Кейін қайталаңыз.','Забагато запитів. Спробуйте пізніше.','Zu viele Anfragen. Versuche es später erneut.','Demasiadas solicitudes. Inténtalo más tarde.'],
  ['CAPTCHA_REQUIRED CAPTCHA_FAILED CAPTCHA_HOST','Complete the security check and try again.','Қауіпсіздік тексеруінен өтіп, қайталаңыз.','Пройдіть перевірку безпеки й спробуйте ще раз.','Schließe die Sicherheitsprüfung ab und versuche es erneut.','Completa la comprobación de seguridad e inténtalo de nuevo.'],
  ['CAPTCHA_UNAVAILABLE','The security check is temporarily unavailable. Try again later.','Қауіпсіздік тексеруі уақытша қолжетімсіз. Кейін қайталаңыз.','Перевірка безпеки тимчасово недоступна. Спробуйте пізніше.','Die Sicherheitsprüfung ist vorübergehend nicht verfügbar. Versuche es später erneut.','La comprobación de seguridad no está disponible. Inténtalo más tarde.'],
  ['CHALLENGE_EXPIRED CHALLENGE_NOT_FOUND CHALLENGE_USED TOKEN_EXPIRED TOKEN_USED OAUTH_STATE OAUTH_REPLAY OAUTH_CODE','This sign-in link or code has expired or was already used. Start again.','Бұл кіру сілтемесі немесе код ескірген не қолданылған. Қайта бастаңыз.','Це посилання або код входу прострочено чи вже використано. Почніть знову.','Dieser Anmeldelink oder Code ist abgelaufen oder wurde bereits verwendet. Starte erneut.','Este enlace o código ha caducado o ya se ha usado. Empieza de nuevo.'],
  ['OAUTH_CANCELLED','Sign-in was cancelled.','Кіру тоқтатылды.','Вхід скасовано.','Die Anmeldung wurde abgebrochen.','Se canceló el inicio de sesión.'],
  ['GOOGLE_IDENTITY','The account could not be verified. Try signing in again.','Аккаунтты тексеру мүмкін болмады. Қайта кіріңіз.','Не вдалося перевірити обліковий запис. Спробуйте увійти знову.','Das Konto konnte nicht bestätigt werden. Melde dich erneut an.','No se pudo verificar la cuenta. Intenta iniciar sesión de nuevo.'],
  ['MAIL_UNAVAILABLE','Email delivery is temporarily unavailable. Try again later.','Хат жіберу уақытша қолжетімсіз. Кейін қайталаңыз.','Надсилання листів тимчасово недоступне. Спробуйте пізніше.','Der E-Mail-Versand ist vorübergehend nicht verfügbar. Versuche es später erneut.','El envío de correo no está disponible. Inténtalo más tarde.'],
  ['BILLING_NOT_CONFIGURED','Unbound checkout is currently unavailable. Try again later.','Unbound төлемі қазір қолжетімсіз. Кейін қайталаңыз.','Оформлення Unbound зараз недоступне. Спробуйте пізніше.','Unbound kann derzeit nicht gekauft werden. Versuche es später erneut.','La compra de Unbound no está disponible. Inténtalo más tarde.'],
  ['PLAN_ACTIVE','Unbound is already active on your account.','Аккаунтыңызда Unbound белсенді.','Unbound уже активний у вашому обліковому записі.','Unbound ist für dein Konto bereits aktiv.','Unbound ya está activo en tu cuenta.'],
  ['SUBSCRIPTION_NOT_FOUND','No active subscription was found.','Белсенді жазылым табылмады.','Активну підписку не знайдено.','Es wurde kein aktives Abonnement gefunden.','No se encontró una suscripción activa.'],
  ['PLAN_LIMIT','Your current plan limit has been reached.','Қазіргі тарифіңіздің шегіне жеттіңіз.','Досягнуто ліміту вашого поточного тарифу.','Das Limit deines aktuellen Tarifs wurde erreicht.','Has alcanzado el límite de tu plan actual.'],
  ['OWNER_REQUIRED OWNER_ROLE ROOM_PERMISSION PUSH_OWNER SELF_ADMIN','You do not have permission for this action.','Бұл әрекетке рұқсатыңыз жоқ.','Ви не маєте дозволу на цю дію.','Du hast keine Berechtigung für diese Aktion.','No tienes permiso para realizar esta acción.'],
  ['OWNER_LEAVE','Transfer ownership before leaving the room.','Бөлмеден шықпас бұрын иелік құқығын беріңіз.','Перед виходом із кімнати передайте права власника.','Übertrage die Leitung, bevor du den Raum verlässt.','Transfiere la propiedad antes de salir de la sala.'],
  ['ROOM_NOT_FOUND INVITE_NOT_FOUND','This room or invitation is no longer available.','Бұл бөлме немесе шақыру енді қолжетімсіз.','Ця кімната або запрошення більше недоступні.','Dieser Raum oder diese Einladung ist nicht mehr verfügbar.','Esta sala o invitación ya no está disponible.'],
  ['ROOM_FULL','This room is full.','Бұл бөлме толы.','Ця кімната заповнена.','Dieser Raum ist voll.','Esta sala está llena.'],
  ['DEVICE_OFFLINE SOURCE_OFFLINE','The device is offline. Open GlukWave on it and try again.','Құрылғы желіде емес. Онда GlukWave ашып, қайталаңыз.','Пристрій не в мережі. Відкрийте на ньому GlukWave і спробуйте знову.','Das Gerät ist offline. Öffne dort GlukWave und versuche es erneut.','El dispositivo está desconectado. Abre GlukWave en él e inténtalo de nuevo.'],
  ['DEVICE_TIMEOUT','The device did not respond. Playback transfer was not completed.','Құрылғы жауап бермеді. Ойнатуды ауыстыру аяқталмады.','Пристрій не відповів. Передачу відтворення не завершено.','Das Gerät hat nicht geantwortet. Die Wiedergabe wurde nicht übertragen.','El dispositivo no respondió. No se completó la transferencia.'],
  ['SOURCE_DEVICE','Choose a different device for playback transfer.','Ойнатуды ауыстыру үшін басқа құрылғыны таңдаңыз.','Виберіть інший пристрій для передачі відтворення.','Wähle ein anderes Gerät für die Wiedergabeübertragung.','Elige otro dispositivo para transferir la reproducción.'],
  ['NO_TRACK TRACK_REQUIRED EMPTY_QUEUE','Select a track first.','Алдымен тректі таңдаңыз.','Спочатку виберіть трек.','Wähle zuerst einen Titel.','Selecciona primero una pista.'],
  ['OFFLINE_UNAVAILABLE','This source does not provide an offline audio file.','Бұл дереккөз офлайн аудиофайл бермейді.','Це джерело не надає аудіофайл для офлайн-прослуховування.','Diese Quelle stellt keine Audiodatei für die Offline-Wiedergabe bereit.','Esta fuente no ofrece un archivo de audio para escuchar sin conexión.'],
  ['FILE_REQUIRED','Choose a file.','Файлды таңдаңыз.','Виберіть файл.','Wähle eine Datei.','Elige un archivo.'],
  ['AUDIO_FORMAT INVALID_AUDIO','This audio file could not be read. Choose a supported audio format.','Аудиофайлды оқу мүмкін болмады. Қолдау көрсетілетін пішімді таңдаңыз.','Не вдалося прочитати аудіофайл. Виберіть підтримуваний формат.','Die Audiodatei konnte nicht gelesen werden. Wähle ein unterstütztes Format.','No se pudo leer el audio. Elige un formato compatible.'],
  ['IMAGE_FORMAT','Choose a PNG, JPEG, WebP or GIF image.','PNG, JPEG, WebP немесе GIF кескінін таңдаңыз.','Виберіть зображення PNG, JPEG, WebP або GIF.','Wähle ein Bild im Format PNG, JPEG, WebP oder GIF.','Elige una imagen PNG, JPEG, WebP o GIF.'],
  ['UPLOAD_TOO_LARGE IMPORT_TOO_LARGE SOUNDCLOUD_LIMIT','The file or response exceeds the permitted size.','Файл немесе жауап рұқсат етілген көлемнен асады.','Файл або відповідь перевищує дозволений розмір.','Die Datei oder Antwort überschreitet die zulässige Größe.','El archivo o la respuesta supera el tamaño permitido.'],
  ['IMPORT_FORMAT IMPORT_METADATA IMPORT_ROW IMPORT_TITLE IMPORT_URL INVALID_CSV EMPTY_IMPORT METADATA_REQUIRED','This import could not be read. Check the file format and track information.','Импортты оқу мүмкін болмады. Файл пішімі мен трек деректерін тексеріңіз.','Не вдалося прочитати імпорт. Перевірте формат файлу й дані треків.','Der Import konnte nicht gelesen werden. Überprüfe das Dateiformat und die Titeldaten.','No se pudo leer la importación. Revisa el formato y los datos de las pistas.'],
  ['INVALID_URL UNSUPPORTED_URL SOUNDCLOUD_REDIRECT','This track link is not supported. Use a direct link from a supported service.','Бұл трек сілтемесі қолдау таппайды. Қолдау көрсетілетін сервистің тікелей сілтемесін қолданыңыз.','Це посилання не підтримується. Використайте пряме посилання з підтримуваного сервісу.','Dieser Titellink wird nicht unterstützt. Verwende einen direkten Link eines unterstützten Dienstes.','Este enlace no es compatible. Usa un enlace directo de un servicio admitido.'],
  ['CONNECT_REQUIRED RECONNECT_REQUIRED','Reconnect this service to access your library.','Кітапханаға кіру үшін сервисті қайта қосыңыз.','Повторно підключіть сервіс для доступу до бібліотеки.','Verbinde diesen Dienst erneut, um auf deine Bibliothek zuzugreifen.','Vuelve a conectar este servicio para acceder a tu biblioteca.'],
  ['PROVIDER_NOT_CONFIGURED PROVIDER_UNAVAILABLE PROVIDER_ERROR SOUNDCLOUD_BUSY SOUNDCLOUD_FORMAT SOUNDCLOUD_METADATA LIKES_UNAVAILABLE','This music source is temporarily unavailable. Try another source or try again later.','Бұл музыка дереккөзі уақытша қолжетімсіз. Басқасын таңдаңыз немесе кейін қайталаңыз.','Це музичне джерело тимчасово недоступне. Виберіть інше або спробуйте пізніше.','Diese Musikquelle ist vorübergehend nicht verfügbar. Wähle eine andere oder versuche es später erneut.','Esta fuente no está disponible. Elige otra o inténtalo más tarde.'],
  ['PUSH_NOT_CONFIGURED FCM_NOT_CONFIGURED PUSH_ENDPOINT','Notifications are currently unavailable on this device.','Бұл құрылғыда хабарландырулар қазір қолжетімсіз.','Сповіщення зараз недоступні на цьому пристрої.','Benachrichtigungen sind auf diesem Gerät derzeit nicht verfügbar.','Las notificaciones no están disponibles en este dispositivo.'],
  ['LYRICS_EMPTY','Add at least one line of lyrics.','Кемінде бір мәтін жолын қосыңыз.','Додайте хоча б один рядок тексту пісні.','Füge mindestens eine Textzeile hinzu.','Añade al menos una línea de letra.'],
  ['LYRICS_NOT_FOUND','No lyrics were found. Try another source or paste them manually.','Мәтін табылмады. Басқа дереккөзді таңдаңыз немесе қолмен енгізіңіз.','Текст не знайдено. Виберіть інше джерело або вставте вручну.','Kein Liedtext gefunden. Wähle eine andere Quelle oder füge ihn manuell ein.','No se encontró la letra. Prueba otra fuente o pégala manualmente.'],
  ['LYRICS_SOURCE_URL','Paste an HTTPS Genius song URL ending in -lyrics.','Соңы -lyrics болатын Genius әнінің HTTPS сілтемесін енгізіңіз.','Вставте HTTPS-посилання на пісню Genius, що закінчується на -lyrics.','Füge einen HTTPS-Link zu einem Genius-Liedtext ein, der auf -lyrics endet.','Pega un enlace HTTPS a una canción de Genius que termine en -lyrics.'],
  ['LYRICS_UNAVAILABLE LYRICS_SOURCE_UNAVAILABLE','This lyrics source is currently unavailable. Try another source or paste the text manually.','Бұл мәтін дереккөзі қазір қолжетімсіз. Басқасын таңдаңыз немесе мәтінді қолмен енгізіңіз.','Це джерело текстів зараз недоступне. Виберіть інше або вставте текст вручну.','Diese Textquelle ist derzeit nicht verfügbar. Wähle eine andere oder füge den Text manuell ein.','Esta fuente no está disponible. Prueba otra o pega el texto manualmente.'],
  ['LYRICS_SOURCE_BUSY','Too many lyrics requests. Try again in a few seconds.','Мәтін сұраулары тым көп. Бірнеше секундтан кейін қайталаңыз.','Забагато запитів тексту. Спробуйте за кілька секунд.','Zu viele Textanfragen. Versuche es in einigen Sekunden erneut.','Demasiadas solicitudes de letras. Inténtalo en unos segundos.'],
  ['LYRICS_SOURCE_TOO_LARGE','This page is too large. Choose another song page.','Бұл бет тым үлкен. Басқа ән бетін таңдаңыз.','Ця сторінка завелика. Виберіть іншу сторінку пісні.','Diese Seite ist zu groß. Wähle eine andere Liedseite.','Esta página es demasiado grande. Elige otra página de canción.'],
  ['WAVEFORM_BUSY WAVEFORM_URL','The audio waveform is currently unavailable. Try again later.','Дыбыс толқыны қазір қолжетімсіз. Кейін қайталаңыз.','Форма звукової хвилі зараз недоступна. Спробуйте пізніше.','Die Audiowellenform ist derzeit nicht verfügbar. Versuche es später erneut.','La onda de audio no está disponible. Inténtalo más tarde.'],
  ['INVALID_CURSOR','This list has changed. Refresh it and try again.','Тізім өзгерді. Жаңартып, қайталаңыз.','Цей список змінився. Оновіть його й спробуйте знову.','Diese Liste hat sich geändert. Aktualisiere sie und versuche es erneut.','Esta lista ha cambiado. Actualízala e inténtalo de nuevo.'],
  ['INVALID_JSON','The request could not be read.','Сұрауды оқу мүмкін болмады.','Не вдалося прочитати запит.','Die Anfrage konnte nicht gelesen werden.','No se pudo leer la solicitud.'],
  ['WEBHOOK_SIGNATURE','The payment notification could not be verified.','Төлем хабарландыруын тексеру мүмкін болмады.','Не вдалося перевірити повідомлення про оплату.','Die Zahlungsbenachrichtigung konnte nicht bestätigt werden.','No se pudo verificar la notificación de pago.'],
  ['REGISTRATION_CLOSED','Registration is temporarily closed.','Тіркелу уақытша жабық.','Реєстрація тимчасово закрита.','Die Registrierung ist vorübergehend geschlossen.','El registro está temporalmente cerrado.'],
  ['PASSWORD_REQUIRED','Set a password using email recovery first.','Алдымен пошта арқылы құпиясөз орнатыңыз.','Спочатку встановіть пароль через відновлення поштою.','Lege zuerst über die E-Mail-Wiederherstellung ein Passwort fest.','Primero establece una contraseña con la recuperación por correo.'],
  ['CONFIRMATION_REQUIRED','Enter the username to confirm.','Растау үшін пайдаланушы атын енгізіңіз.','Введіть ім’я користувача для підтвердження.','Gib zur Bestätigung den Benutzernamen ein.','Introduce el nombre de usuario para confirmar.'],
  ['ALREADY_FRIENDS','You are already friends.','Сіздер достарсыздар.','Ви вже друзі.','Ihr seid bereits befreundet.','Ya sois amigos.'],
  ['FRIEND_LIMIT JAM_FULL','The participant limit has been reached.','Қатысушылар шегіне жетті.','Досягнуто ліміту учасників.','Das Teilnehmerlimit wurde erreicht.','Se ha alcanzado el límite de participantes.'],
  ['PRIVATE_TRACK','Public playlists can contain only public tracks.','Ашық плейлистке тек ашық тректерді қосуға болады.','Публічні плейлисти можуть містити лише загальнодоступні треки.','Öffentliche Playlists dürfen nur öffentliche Titel enthalten.','Las listas públicas solo pueden contener pistas públicas.'],
  ['PACKAGE_FORMAT','Choose a valid installation package.','Жарамды орнату пакетін таңдаңыз.','Виберіть коректний інсталяційний пакет.','Wähle ein gültiges Installationspaket.','Elige un paquete de instalación válido.'],
  ['SERVER_ERROR','The action could not be completed. Try again.','Әрекетті орындау мүмкін болмады. Қайталаңыз.','Не вдалося виконати дію. Спробуйте ще раз.','Die Aktion konnte nicht ausgeführt werden. Versuche es erneut.','No se pudo completar la acción. Inténtalo de nuevo.'],
];
export const errorCatalog=Object.fromEntries(groups.flatMap(([codes,...values])=>codes.split(' ').map(code=>[code,Object.fromEntries(order.map((language,index)=>[language,values[index]]))])));
export function localizedError(error,language){if(language==='ru')return {...error};return {...error,message:(errorCatalog[error.code]||errorCatalog.SERVER_ERROR)[language]||errorCatalog.SERVER_ERROR.en};}
const descriptions={
  soundcloud:['Public track links and search are available. Connect your account to import its library.','Трек сілтемелері мен ашық іздеу қолжетімді. Кітапхананы импорттау үшін аккаунтты қосыңыз.','Публічні посилання й пошук доступні. Підключіть обліковий запис для імпорту бібліотеки.','Öffentliche Titellinks und Suche sind verfügbar. Verbinde dein Konto zum Bibliotheksimport.','Los enlaces públicos y la búsqueda están disponibles. Conecta tu cuenta para importar la biblioteca.'],
  yandex:['Listen through the official player and import track lists from a file.','Ресми плеер арқылы тыңдап, тректер тізімін файлдан импорттаңыз.','Слухайте через офіційний плеєр та імпортуйте списки треків із файлу.','Höre über den offiziellen Player und importiere Titellisten aus einer Datei.','Escucha con el reproductor oficial e importa listas desde un archivo.'],
  youtube:['Listen to supported videos in the official YouTube player.','Қолдау көрсетілетін бейнелерді ресми YouTube плеерінде тыңдаңыз.','Слухайте підтримувані відео в офіційному плеєрі YouTube.','Höre unterstützte Videos im offiziellen YouTube-Player.','Escucha vídeos compatibles en el reproductor oficial de YouTube.'],
  spotify:['The original Spotify player determines playback availability.','Ойнатудың қолжетімділігін Spotify плеері анықтайды.','Доступність відтворення визначає оригінальний плеєр Spotify.','Der Original-Player von Spotify bestimmt die Verfügbarkeit der Wiedergabe.','El reproductor original de Spotify determina la disponibilidad.'],
};
function localizedProvider(provider,language){
  if(language==='ru'||!provider.reason)return provider;
  // Unavailable account connections must not accidentally advertise an enabled sign-in.
  if(Object.hasOwn(provider,'connected')&&!provider.configured)return {...provider,reason:errorCatalog.PROVIDER_UNAVAILABLE[language]};
  const text=descriptions[provider.id||provider.provider];
  if(provider.id==='soundcloud'&&!provider.searchAvailable)return {...provider,reason:errorCatalog.PROVIDER_UNAVAILABLE[language]};
  return {...provider,reason:text?.[order.indexOf(language)]||errorCatalog.PROVIDER_UNAVAILABLE[language]};
}
export function installLocalizedResponses(app,ctx){
  app.use('/api',(req,res,next)=>{
    const language=browserLanguage(req.headers['accept-language'])||ctx.localeFor(req).language;req.language=language;
    res.set('Content-Language',language);res.vary('Accept-Language');const json=res.json.bind(res),diagnosticRoute=req.path.startsWith('/admin/errors');
    res.json=payload=>{
      // Diagnostics are evidence, not consumer error messages to translate.
      const diagnosticLogs=res.statusCode<400&&diagnosticRoute;
      if(payload&&typeof payload==='object'&&!diagnosticLogs){
        if(payload.error)payload={...payload,error:localizedError(payload.error,language)};
        if(Array.isArray(payload.errors))payload={...payload,errors:payload.errors.map(error=>({...error,message:localizedError({code:error.code||'PROVIDER_UNAVAILABLE',message:error.message},language).message}))};
        for(const key of ['providers','connections'])if(Array.isArray(payload[key]))payload={...payload,[key]:payload[key].map(provider=>localizedProvider(provider,language))};
      }
      return json(payload);
    };
    next();
  });
}
