import crypto from 'node:crypto';
import {systemText} from './system-text.js';
import {z} from 'zod';
import {jwtVerify,createRemoteJWKSet} from 'jose';
import {id,now,secret,digest,seal,unseal,parse,text,fail,asyncRoute,publicUser,remoteJson as defaultRemoteJson} from './util.js';
import {createPublicSoundcloud,soundcloudWaveformUrl} from './soundcloud-public.js';
import {oauthCredentials,oauthSettings,oauthReturnBase} from './oauth-config.js';
import {planLimits} from './plans.js';
import {discordScopes} from './discord-presence.js';

const jwks=createRemoteJWKSet(new URL('https://www.googleapis.com/oauth2/v3/certs'));
const oauthDefs={
  google:{auth:'https://accounts.google.com/o/oauth2/v2/auth',token:'https://oauth2.googleapis.com/token',scope:'openid email profile'},
  youtube:{auth:'https://accounts.google.com/o/oauth2/v2/auth',token:'https://oauth2.googleapis.com/token',scope:'openid email profile https://www.googleapis.com/auth/youtube.readonly'},
  spotify:{auth:'https://accounts.spotify.com/authorize',token:'https://accounts.spotify.com/api/token',scope:'playlist-read-private playlist-read-collaborative user-library-read user-read-private streaming user-read-playback-state user-modify-playback-state'},
  soundcloud:{auth:'https://secure.soundcloud.com/authorize',token:'https://secure.soundcloud.com/oauth/token',scope:''},
  discord:{auth:'https://discord.com/oauth2/authorize',token:'https://discord.com/api/oauth2/token',scope:discordScopes},
};
export function providerConfiguration(config,{diagnostics=false}={}){const providers=[
  {id:'soundcloud',name:'SoundCloud',configured:!!(config.soundcloud.id&&config.soundcloud.secret),searchAvailable:config.soundcloudPublicSearch!==false||!!(config.soundcloud.id&&config.soundcloud.secret),capabilities:['public-links',...(config.soundcloud.id&&config.soundcloud.secret?['native-stream']:[]),...(config.soundcloudPublicSearch!==false?['public-search']:[]),'search','playlists'],reason:config.soundcloudPublicSearch!==false?'Публичный поиск и треки по ссылке доступны без ключей. Вход и импорт личной библиотеки требуют ключи SoundCloud.':'Публичные метаданные доступны без ключей. Собственный поток и личная библиотека требуют OAuth приложения SoundCloud.'},
  {id:'yandex',name:'Яндекс Музыка',configured:false,capabilities:['export-import','audio-match'],reason:'Импорт CSV/JSON; собственное аудио через точное разрешённое совпадение. Публичный OAuth API библиотеки не подключён.'},
  {id:'youtube',name:'YouTube',configured:!!config.youtubeKey,capabilities:['search','playlists','licensed-audio','audio-match'],reason:'Поиск требует YouTube Data API key; личная библиотека — Google OAuth. YouTube Music не имеет отдельного публичного API.'},
  {id:'spotify',name:'Spotify',configured:!!(config.spotify.id&&config.spotify.secret),capabilities:['search','playlists','audio-match'],reason:'Поиск и импорт требуют ключи Spotify. Собственное аудио — разрешённое совпадение, а не оригинальный поток Spotify.'},
].map(provider=>({...provider,configured:oauthSettings(config,provider.id).loginAvailable,loginAvailable:oauthSettings(config,provider.id).loginAvailable,searchAvailable:provider.searchAvailable??(provider.id==='youtube'?!!config.youtubeKey:provider.id==='spotify'?!!(config.spotify.id&&config.spotify.secret):false)}));if(diagnostics)return providers;const descriptions={soundcloud:'Ищи музыку или добавляй треки по ссылке.',yandex:'Переноси плейлисты и слушай музыку по ссылке.',youtube:'Добавляй треки и клипы из YouTube.',spotify:'Переноси любимую музыку и открывай треки Spotify.'};return providers.map(provider=>({...provider,reason:descriptions[provider.id]}));}
export function sourceUrl(input){let u;try{u=new URL(input);}catch{fail(400,'INVALID_URL','Вставь полную ссылку на трек.');}if(u.protocol!=='https:'||u.username||u.password||u.port)fail(400,'INVALID_URL','Нужна HTTPS-ссылка площадки.');const host=u.hostname.toLowerCase();if(['youtube.com','www.youtube.com','m.youtube.com','music.youtube.com','youtu.be','www.youtube-nocookie.com'].includes(host)){const sid=host==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.match(/^\/(?:shorts|embed)\/([^/]+)/)?.[1];if(!/^[\w-]{11}$/.test(sid||''))fail(400,'INVALID_URL','В ссылке нет YouTube-видео.');return {source:'youtube',sourceId:sid,url:`https://www.youtube.com/watch?v=${sid}`};}if(host==='open.spotify.com'){const sid=u.pathname.match(/\/track\/([a-zA-Z0-9]{22})/)?.[1];if(!sid)fail(400,'INVALID_URL','Нужна ссылка Spotify на отдельный трек.');return {source:'spotify',sourceId:sid,url:`https://open.spotify.com/track/${sid}`};}if(['soundcloud.com','www.soundcloud.com'].includes(host)&&/^\/[^/]+\/[^/]+\/?$/.test(u.pathname))return {source:'soundcloud',sourceId:digest(u.pathname).slice(0,24),url:`https://soundcloud.com${u.pathname}`};if(['music.yandex.ru','music.yandex.com','music.yandex.kz'].includes(host)){const m=u.pathname.match(/^\/album\/(\d+)\/track\/(\d+)\/?$/);if(!m)fail(400,'INVALID_URL','Нужна ссылка Яндекс Музыки на трек внутри альбома.');return {source:'yandex',sourceId:m[2],albumId:m[1],url:`https://music.yandex.ru/album/${m[1]}/track/${m[2]}`};}fail(400,'UNSUPPORTED_URL','Поддерживаются ссылки SoundCloud, YouTube, Spotify и Яндекс Музыки.');}
export const durationISO=value=>{const m=String(value||'').match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);return m?Number(m[1]||0)*3600+Number(m[2]||0)*60+Number(m[3]||0):0;};
export function normalizeSpotify(t){return {id:`spotify-${t.id}`,title:t.name,artist:t.artists?.map(x=>x.name).join(', ')||'',artists:(t.artists||[]).map(x=>({name:x.name,sourceId:x.id,sourceUrl:x.external_urls?.spotify||'',artwork:x.images?.[0]?.url||''})),tags:t.artists?.flatMap(x=>x.genres||[])||[],album:t.album?.name||'',artwork:t.album?.images?.[0]?.url||'',duration:(t.duration_ms||0)/1000,source:'spotify',sourceId:t.id,sourceUrl:t.external_urls?.spotify||`https://open.spotify.com/track/${t.id}`,playback:{kind:'spotify',embedUrl:`https://open.spotify.com/embed/track/${t.id}`,offline:false},createdAt:now(),public:true};}
export function normalizeYoutube(t){const sid=typeof t.id==='string'?t.id:t.id?.videoId||t.contentDetails?.videoId||t.snippet?.resourceId?.videoId;return {id:`youtube-${sid}`,title:t.snippet?.title||'',artist:t.snippet?.videoOwnerChannelTitle||t.snippet?.channelTitle||'',album:'',artwork:t.snippet?.thumbnails?.high?.url||t.snippet?.thumbnails?.default?.url||'',duration:durationISO(t.contentDetails?.duration),source:'youtube',sourceId:sid,sourceUrl:`https://www.youtube.com/watch?v=${sid}`,playback:{kind:'youtube',embedUrl:`https://www.youtube-nocookie.com/embed/${sid}?enablejsapi=1`,offline:false},createdAt:now(),public:true};}
export function normalizeSoundcloud(t){const sid=t.urn||String(t.id);return {id:`soundcloud-${sid}`,title:t.title,artist:t.user?.username||'',artists:t.user?.username?[{name:t.user.username,sourceId:String(t.user.id||t.user.permalink||t.user.username),artwork:t.user.avatar_url||'',sourceUrl:t.user.permalink_url||''}]:[],genre:String(t.genre||'').slice(0,200),tags:(String(t.tag_list||'').match(/"[^"]+"|\S+/g)||[]).map(tag=>tag.replace(/^"|"$/g,'')).slice(0,30),album:'',artwork:t.artwork_url||t.user?.avatar_url||'',waveformUrl:soundcloudWaveformUrl(t.waveform_url),sourcePermission:{downloadable:t.downloadable===true,license:String(t.license||'')},duration:(t.duration||0)/1000,source:'soundcloud',sourceId:sid,sourceUrl:t.permalink_url,playback:{kind:'soundcloud',embedUrl:`https://w.soundcloud.com/player/?url=${encodeURIComponent(t.permalink_url)}&auto_play=false`,offline:false},createdAt:now(),public:t.sharing!=='private'};}

export function setupProviders(app,ctx){
  const {store,config,requireAuth}=ctx;
  const remoteJson=ctx.providerRemoteJson||defaultRemoteJson;
  const publicSoundcloud=createPublicSoundcloud();
  ctx.publicSoundcloudTrack=publicSoundcloud.track;
  const locks=new Map();
  const credentials=p=>oauthCredentials(config,p);
  const configured=p=>!!(credentials(p)?.id&&credentials(p)?.secret);
  async function tokenRequest(p,body){if(p==='discord')return ctx.discordExchange(body);const c=credentials(p),headers={'Content-Type':'application/x-www-form-urlencoded'};if(p==='spotify'||(p==='soundcloud'&&body.grant_type==='client_credentials'))headers.Authorization=`Basic ${Buffer.from(`${c.id}:${c.secret}`).toString('base64')}`;else Object.assign(body,{client_id:c.id,client_secret:c.secret});return remoteJson(oauthDefs[p].token,{method:'POST',headers,body:new URLSearchParams(body)});}
  async function token(p,userId=null,invalidAccess=null){const key=userId?`${userId}:${p}`:`app:${p}`;if(locks.has(key))return locks.get(key);const promise=(async()=>{const record=await store.get('connections',key);let t=record?unseal(record.token,config.encryptionKey):null;if(t&&t.expiresAt>Date.now()+30000&&t.access_token!==invalidAccess)return t.access_token;if(userId&&!record)fail(409,'CONNECT_REQUIRED','Сначала подключи аккаунт площадки.');if(!configured(p))fail(503,'PROVIDER_NOT_CONFIGURED','Этот сервис сейчас недоступен. Выбери другой источник.');const body=t?.refresh_token?{grant_type:'refresh_token',refresh_token:t.refresh_token}:{grant_type:'client_credentials'};if(userId&&!t?.refresh_token)fail(409,'RECONNECT_REQUIRED','Переподключи площадку: доступ истёк.');const fresh=await tokenRequest(p,body);t={...t,...fresh,expiresAt:Date.now()+Number(fresh.expires_in||3600)*1000};await store.put('connections',key,{...(record||{}),id:key,provider:p,userId,token:seal(t,config.encryptionKey),updatedAt:now()});return t.access_token;})();locks.set(key,promise);try{return await promise;}finally{locks.delete(key);}}
  const call=async(p,pathname,userId=null)=>{const access=await token(p,userId),base=p==='spotify'?'https://api.spotify.com/v1':p==='soundcloud'?'https://api.soundcloud.com':'https://www.googleapis.com/youtube/v3';const url=new URL(pathname,base+'/');if(url.origin!==new URL(base).origin||!url.pathname.startsWith(new URL(base).pathname))fail(400,'INVALID_CURSOR','Неверный адрес страницы.');const request=value=>remoteJson(url,{headers:{Authorization:`${p==='soundcloud'?'OAuth':'Bearer'} ${value}`}});try{return await request(access);}catch(error){if(p!=='soundcloud'||error.details?.upstreamStatus!==401)throw error;return request(await token(p,userId,access));}};
  ctx.officialSoundcloudCall=(pathname,userId=null)=>call('soundcloud',pathname,userId);
  const persist=async(tracks,{ownerId}={})=>{
    const saved=[];
    for(let track of tracks){
      if(!track.title||!track.sourceId)continue;
      if(track.public===false&&!track.uploadedBy){
        // Private OAuth metadata belongs to this account, never the public catalog.
        if(!ownerId)continue;
        track={...track,id:`private-${track.source}-${digest(`${ownerId}:${track.sourceId}`).slice(0,32)}`,uploadedBy:ownerId};
      }
      await store.put('tracks',track.id,track);saved.push(track);
    }
    return saved;
  };
  ctx.providerToken=token;ctx.persistTracks=persist;
  ctx.searchProvider=async(p,q,userId)=>{
    if(p==='youtube'){
      if(ctx.extractorAvailable?.('youtube'))try{const results=await ctx.extractorSearch(q);return persist(results.map(item=>({id:`youtube-${item.track_id}`,source:'youtube',sourceId:item.track_id,sourceUrl:item.source_url,title:item.title,artist:item.artist,album:item.album,artwork:item.cover,duration:Number(item.duration)||0,createdAt:now(),public:true,playback:{kind:'youtube',embedUrl:`https://www.youtube-nocookie.com/embed/${item.track_id}?enablejsapi=1`,offline:false}})));}catch(error){if(!config.youtubeKey)throw error;}
      if(!config.youtubeKey)fail(503,'PROVIDER_NOT_CONFIGURED','Поиск YouTube сейчас недоступен. Можно открыть трек по ссылке.');
      const r=await remoteJson(`https://www.googleapis.com/youtube/v3/search?${new URLSearchParams({part:'snippet',type:'video,channel',maxResults:'20',q,key:config.youtubeKey})}`);
      const videoItems=(r.items||[]).filter(item=>item.id?.videoId);
      let videoMap=new Map();
      if(videoItems.length){
        try{
          const vr=await remoteJson(`https://www.googleapis.com/youtube/v3/videos?${new URLSearchParams({part:'snippet,contentDetails',id:videoItems.map(item=>item.id.videoId).join(','),key:config.youtubeKey})}`);
          videoMap=new Map((vr.items||[]).map(v=>[v.id,v]));
        }catch{}
      }
      const tracks=await persist(videoItems.map(item=>normalizeYoutube(videoMap.get(item.id.videoId)||item)));
      tracks.artists=(r.items||[]).filter(item=>item.id?.channelId).map(item=>({id:`youtube-artist-${item.id.channelId}`,sourceId:item.id.channelId,source:'youtube',name:item.snippet.title,artwork:item.snippet.thumbnails?.medium?.url||'',sourceUrl:`https://www.youtube.com/channel/${item.id.channelId}`}));return tracks;
    }
    if(p==='spotify'){
      const r=await call(p,`search?${new URLSearchParams({q,type:'track,artist',limit:'10'})}`,userId&&(await store.get('connections',`${userId}:spotify`))?userId:null);
      const tracks=await persist((r.tracks?.items||[]).map(normalizeSpotify));
      tracks.artists=(r.artists?.items||[]).map(item=>({id:`spotify-artist-${item.id}`,sourceId:item.id,source:'spotify',name:item.name,artwork:item.images?.[0]?.url||'',sourceUrl:item.external_urls?.spotify||'',genres:item.genres||[]}));return tracks;
    }
    if(p==='soundcloud'){
      if(configured(p)){try{const r=await call(p,`tracks?${new URLSearchParams({q,limit:'20',linked_partitioning:'true'})}`);return persist((r.collection||r||[]).map(normalizeSoundcloud));}catch(error){if(config.soundcloudPublicSearch===false)throw error;}}
      if(config.soundcloudPublicSearch===false)fail(503,'PROVIDER_NOT_CONFIGURED','Поиск SoundCloud отключён.');
      return persist((await publicSoundcloud.search(q)).map(normalizeSoundcloud));
    }return [];
  };
  ctx.resolveSource=async(input,metadata={},options={})=>{const s=sourceUrl(input);let track;
  if(s.source==='spotify'&&ctx.extractorAvailable?.('spotify'))try{const info=await ctx.extractorMetadata('spotify',s.url);track=normalizeSpotify({id:s.sourceId,name:info.title,artists:[{name:info.artist}],album:{name:info.album,images:[{url:info.cover}]},duration_ms:info.duration*1000});}catch{ /* Official API/oEmbed remains independent of spotDL. */ }
  if(!track&&s.source==='spotify'&&configured('spotify')){track=normalizeSpotify(await call('spotify',`tracks/${s.sourceId}`));}else if(!track&&s.source==='youtube'){if(config.youtubeKey){try{const vr=await remoteJson(`https://www.googleapis.com/youtube/v3/videos?${new URLSearchParams({part:'snippet,contentDetails',id:s.sourceId,key:config.youtubeKey})}`);if(vr?.items?.[0])track=normalizeYoutube(vr.items[0]);}catch{}}if(!track){const r=await remoteJson(`https://www.youtube.com/oembed?${new URLSearchParams({url:s.url,format:'json'})}`);track={...normalizeYoutube({id:s.sourceId,snippet:{title:r.title,channelTitle:r.author_name,thumbnails:{high:{url:r.thumbnail_url}}}})};}}else if(!track&&s.source==='soundcloud'){try{track=normalizeSoundcloud(await publicSoundcloud.track(s.url));}catch(error){if(error.status===429||error.code==='SOUNDCLOUD_BUSY')throw error;const r=await remoteJson(`https://soundcloud.com/oembed?${new URLSearchParams({url:s.url,format:'json'})}`),author=String(r.author_name||''),suffix=` by ${author}`;track=normalizeSoundcloud({urn:s.sourceId,title:author&&r.title?.endsWith(suffix)?r.title.slice(0,-suffix.length):r.title,user:{username:author},artwork_url:r.thumbnail_url,permalink_url:s.url});}}else if(!track&&s.source==='spotify'){const r=await remoteJson(`https://open.spotify.com/oembed?${new URLSearchParams({url:s.url})}`);track=normalizeSpotify({id:s.sourceId,name:r.title,artists:[],album:{images:[{url:r.thumbnail_url}]}});}else if(!track) {
    // User export metadata is accepted explicitly; no fabricated titles or private API credentials.
    if(!metadata.title)fail(422,'METADATA_REQUIRED','Не удалось прочитать название трека. Перенеси его из сохранённого плейлиста.');
    track={id:`yandex-${s.sourceId}`,title:metadata.title,artist:metadata.artist||'',album:metadata.album||'',artwork:'',duration:0,source:'yandex',sourceId:s.sourceId,sourceUrl:s.url,playback:{kind:'yandex',embedUrl:`https://music.yandex.ru/iframe/#track/${s.sourceId}/${s.albumId}`,offline:false},createdAt:now(),public:true};
  }if(options.persist!==false)await persist([track]);return track;};
  ctx.providerConfiguration=(options)=>providerConfiguration(config,options).map(provider=>({...provider,searchAvailable:provider.searchAvailable||provider.id==='youtube'&&!!ctx.extractorAvailable?.('youtube')}));

  async function startOAuth(p,req,nativePost=false){if(p==='discord'&&!planLimits(req.auth?.user).discordPresence)fail(403,'PLAN_LIMIT','Discord доступен в Beta и Unbound.');const settings=oauthSettings(config,p);if(!oauthDefs[p]||!settings.loginAvailable)fail(503,'PROVIDER_NOT_CONFIGURED','Вход в этот сервис сейчас недоступен. Попробуй позже.');const state=secret(),verifier=secret(),nonce=secret(),callback=settings.redirectUri;let bridgeId=null;if(p==='google'&&req.query.native){const c=await store.get('challenges',String(req.query.native));if(!c||c.kind!=='native'||c.status!=='pending'||c.expiresAt<Date.now()||digest(String(req.query.secret||''))!==c.secretHash)fail(400,'CHALLENGE_EXPIRED','Вход в приложение устарел.');bridgeId=c.id;}
    const entry={id:digest(state),provider:p,userId:req.auth?.user.id||null,sessionId:req.auth?.session.id||null,verifier,nonce,callback,returnBase:oauthReturnBase(config,req),bridgeId,native:nativePost||!!bridgeId,expiresAt:Date.now()+10*60000};await store.create('oauthStates',entry.id,entry);const u=new URL(oauthDefs[p].auth);const params={client_id:credentials(p).id,redirect_uri:callback,response_type:'code',state,scope:oauthDefs[p].scope};Object.assign(params,{code_challenge:crypto.createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'});if(p==='google'||p==='youtube')Object.assign(params,{nonce,access_type:'offline',prompt:'consent'});u.search=new URLSearchParams(params);return {url:u.toString(),state,native:entry.native};
  }
  const stateCookie=(p,r,res)=>{if(!r.native)res.cookie(`gw_oauth_${p}`,digest(r.state),{httpOnly:true,sameSite:'lax',secure:config.production,maxAge:600000,path:'/'});};
  app.get('/api/auth/google/start',asyncRoute(async(req,res)=>{const r=await startOAuth('google',req);stateCookie('google',r,res);res.redirect(r.url);}));
  app.get('/api/integrations',requireAuth,asyncRoute(async(req,res)=>{const connections=[];for(const p of ['soundcloud','yandex','youtube','spotify','discord']){const r=await store.get('connections',`${req.auth.user.id}:${p}`),pc=providerConfiguration(config).find(x=>x.id===p);connections.push({provider:p,connected:!!r,displayName:r?.displayName||'',configured:oauthSettings(config,p).loginAvailable,searchAvailable:pc?.searchAvailable||false,reason:pc?.reason});}res.json({connections});}));
  app.get('/api/integrations/:provider/connect',requireAuth,asyncRoute(async(req,res)=>{const r=await startOAuth(req.params.provider,req);stateCookie(req.params.provider,r,res);res.redirect(r.url);}));
  app.post('/api/integrations/:provider/connect',requireAuth,asyncRoute(async(req,res)=>{const r=await startOAuth(req.params.provider,req,req.headers['x-glukwave-client']==='native');stateCookie(req.params.provider,r,res);res.set('Cache-Control','no-store').json({url:r.url});}));
  async function callback(p,req,res){const state=String(req.query.state||''),key=digest(state),s=await store.get('oauthStates',key);if(!s||s.used||s.provider!==p||s.expiresAt<Date.now()||(!s.native&&req.cookies[`gw_oauth_${p}`]!==key))fail(400,'OAUTH_STATE','Вход устарел. Запусти подключение заново.');if(s.sessionId){const session=await store.get('sessions',s.sessionId);if(!session||session.userId!==s.userId||session.expiresAt<Date.now())fail(401,'AUTH_REQUIRED','Сессия завершена. Запусти подключение заново.');}await store.update('oauthStates',key,v=>{if(!v||v.used)fail(400,'OAUTH_REPLAY','Вход уже завершён.');return {...v,used:true};});res.clearCookie(`gw_oauth_${p}`,{path:'/'});if(req.query.error){const errDesc=req.query.error_description?`${req.query.error}: ${req.query.error_description}`:String(req.query.error);ctx.log.warn({provider:p,error:req.query.error,description:req.query.error_description},'OAuth callback error from provider');fail(400,'OAUTH_CANCELLED',`Ошибка авторизации (${errDesc})`);}const code=String(req.query.code||'');if(!code||code.length>2048)fail(400,'OAUTH_CODE','Площадка не вернула код авторизации.');const t=await tokenRequest(p,{grant_type:'authorization_code',code,redirect_uri:s.callback,code_verifier:s.verifier});
    if(p==='google'){const {payload}=await jwtVerify(t.id_token,jwks,{audience:config.google.id,issuer:['https://accounts.google.com','accounts.google.com']});if(payload.nonce!==s.nonce||!payload.email_verified||typeof payload.email!=='string')fail(400,'GOOGLE_IDENTITY','Google не подтвердил этот адрес.');const identity=await store.get('identities',`google:${payload.sub}`);let user=identity?await store.get('users',identity.userId):(await store.list('users',u=>u.email===payload.email.toLowerCase()))[0];if(!user){if(!await ctx.registrationEnabled())fail(403,'REGISTRATION_CLOSED','Регистрация временно закрыта.');const uid=id(),username=`wave_${uid.replaceAll('-','').slice(0,14)}`;user={id:uid,email:payload.email.toLowerCase(),username,displayName:String(payload.name||username).slice(0,60),avatarUrl:String(payload.picture||''),bannerUrl:'',bio:'',tags:[],plan:'free',role:config.adminEmails.includes(payload.email.toLowerCase())?'admin':'user',emailVerified:true,passwordHash:null,blocked:false,createdAt:now()};await store.create('users',uid,user);}if(user.blocked)fail(403,'ACCOUNT_BLOCKED','Аккаунт заблокирован.');await store.update('users',user.id,u=>({...u,emailVerified:true}));await store.put('identities',`google:${payload.sub}`,{id:`google:${payload.sub}`,userId:user.id});if(s.bridgeId){await store.update('challenges',s.bridgeId,c=>{if(!c||c.status!=='pending'||c.expiresAt<Date.now())fail(400,'CHALLENGE_EXPIRED','Вход устарел.');return {...c,userId:user.id,status:'approved'};});return res.redirect(`${config.appUrl}/?nativeComplete=1`);}await ctx.issue(user,req,res);return res.redirect(`${s.returnBase||config.appUrl}/?signedIn=1`);}
    const user=await store.get('users',s.userId);if(!user||user.blocked)fail(403,'ACCOUNT_BLOCKED','Аккаунт недоступен.');if(p==='discord'&&!planLimits(user).discordPresence)fail(403,'PLAN_LIMIT','Discord доступен в Beta и Unbound.');const access=t.access_token;const info=p==='spotify'?await remoteJson('https://api.spotify.com/v1/me',{headers:{Authorization:`Bearer ${access}`}}):p==='soundcloud'?await remoteJson('https://api.soundcloud.com/me',{headers:{Authorization:`OAuth ${access}`}}):p==='discord'?await remoteJson('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${access}`}}).catch(()=>remoteJson('https://discord.com/api/oauth2/userinfo',{headers:{Authorization:`Bearer ${access}`}})):await remoteJson('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${access}`}});if(s.sessionId&&!await store.get('sessions',s.sessionId))fail(401,'AUTH_REQUIRED','Сессия завершена.');const record={id:`${user.id}:${p}`,userId:user.id,provider:p,displayName:info.display_name||info.global_name||info.username||info.name||'',providerUserId:info.id||info.sub,token:seal({...t,expiresAt:Date.now()+Number(t.expires_in||3600)*1000},config.encryptionKey),updatedAt:now()};if(p==='discord'){const discordId=String(info.id||info.sub||'');if(typeof discordId!=='string'||!/^\d{5,25}$/.test(discordId)||typeof t.access_token!=='string')fail(502,'DISCORD_IDENTITY','Discord не подтвердил аккаунт.');record.providerUserId=discordId;record.username=String(info.username||info.preferred_username||'').slice(0,80);record.displayName=info.global_name||info.display_name||info.name||record.username||'';record.avatarUrl=info.avatar&&/^[a-zA-Z0-9_]+$/.test(info.avatar)?`https://cdn.discordapp.com/avatars/${discordId}/${info.avatar}.${info.avatar.startsWith('a_')?'gif':'png'}?size=128`:info.picture||`https://cdn.discordapp.com/embed/avatars/${Number((BigInt(discordId)>>22n)%6n)}.png`;record.scope=String(t.scope||'');await ctx.discordReplaceConnection(user.id,record);ctx.discordPlaybackChanged(user.id);}else await store.put('connections',record.id,record);ctx.io?.to(`user:${user.id}`).emit('integrations:changed',{});await ctx.audit('integration.connect',user.id,{provider:p});res.redirect(`${s.returnBase||config.appUrl}/app/?connected=${p}#settings?section=connections`);
  }
  app.get('/api/auth/google/callback',asyncRoute((req,res)=>callback('google',req,res)));
  app.get('/api/integrations/:provider/callback',asyncRoute(async(req,res)=>{try{await callback(req.params.provider,req,res);}catch(error){ctx.log.warn({provider:req.params.provider,code:error.code||'PROVIDER_ERROR',status:error.status,message:error.message},'Provider callback failed');res.redirect(`${config.appUrl}/app/?integration_error=${encodeURIComponent(error.code||'PROVIDER_ERROR')}&integration_msg=${encodeURIComponent(error.message||'')}#settings?section=connections`);}}));
  app.get('/api/admin/integrations/diagnostics',ctx.requireAdmin,(req,res)=>{res.set('Cache-Control','no-store').json({providers:['google','soundcloud','yandex','youtube','spotify','discord'].map(p=>({...oauthSettings(config,p),searchAvailable:providerConfiguration(config).find(provider=>provider.id===p)?.searchAvailable||false}))});});
  app.delete('/api/integrations/:provider',requireAuth,asyncRoute(async(req,res)=>{const key=`${req.auth.user.id}:${req.params.provider}`;if(req.params.provider==='discord')await ctx.discordDisconnect(req.auth.user.id);else await store.remove('connections',key);await ctx.audit('integration.disconnect',req.auth.user.id,{provider:req.params.provider});res.json({ok:true});}));
  app.get('/api/integrations/spotify/token',requireAuth,asyncRoute(async(req,res)=>{res.set('Cache-Control','no-store').json({accessToken:await token('spotify',req.auth.user.id)});}));

  async function playlists(p,uid,language='en'){if(p==='spotify'){const lists=[];let next='me/playlists?limit=50';while(next&&lists.length<1000){const r=await call(p,next,uid);lists.push(...(r.items||[]).map(x=>({id:x.id,name:x.name,description:x.description,artwork:x.images?.[0]?.url||'',trackCount:x.items?.total??x.tracks?.total??0})));next=r.next;}let liked={id:'liked',name:systemText('likedTracks',language),trackCount:0};const r=await call(p,'me/tracks?limit=1',uid);liked.trackCount=r.total;return {playlists:lists,liked};}if(p==='soundcloud'){const lists=[];let next='me/playlists?limit=50&linked_partitioning=true';while(next&&lists.length<1000){const r=await call(p,next,uid);lists.push(...(r.collection||r||[]).map(x=>({id:x.urn||String(x.id),name:x.title,description:x.description,artwork:x.artwork_url||'',trackCount:x.track_count||0})));next=r.next_href;}return {playlists:lists,liked:{id:'liked',name:systemText('likedTracks',language),trackCount:0}};}if(p==='youtube'){const lists=[];let page='';do{const r=await call(p,`playlists?${new URLSearchParams({part:'snippet,contentDetails',mine:'true',maxResults:'50',pageToken:page})}`,uid);lists.push(...(r.items||[]).map(x=>({id:x.id,name:x.snippet.title,description:x.snippet.description,artwork:x.snippet.thumbnails?.medium?.url||'',trackCount:x.contentDetails.itemCount})));page=r.nextPageToken||'';}while(page&&lists.length<1000);return {playlists:lists,liked:{id:'liked',name:systemText('likedVideos',language),trackCount:0}};}fail(503,'PROVIDER_UNAVAILABLE','Для этой площадки доступен импорт экспортированного CSV/JSON.');}
  async function playlistTracks(p,uid,pid,cursor=''){if(pid.length>200||cursor.length>300)fail(400,'INVALID_CURSOR','Неверная страница.');if(p==='spotify'){const r=await call(p,pid==='liked'?`me/tracks?limit=50&offset=${Number(cursor)||0}`:`playlists/${encodeURIComponent(pid)}/items?limit=50&offset=${Number(cursor)||0}`,uid);return {tracks:await persist((r.items||[]).map(x=>x.item||x.track).filter(t=>t?.id&&t.type!=='episode').map(normalizeSpotify)),nextCursor:r.next?String((Number(cursor)||0)+r.items.length):null};}if(p==='soundcloud'){const route=pid==='liked'?'me/likes/tracks':`playlists/${encodeURIComponent(pid)}/tracks`;const r=await call(p,`${route}?limit=50&linked_partitioning=true&offset=${Number(cursor)||0}`,uid);return {tracks:await persist((r.collection||r||[]).map(x=>x.track||x).filter(t=>t?.title).map(normalizeSoundcloud),{ownerId:uid}),nextCursor:r.next_href?String((Number(cursor)||0)+50):null};}if(p==='youtube'){let playlistId=pid;if(pid==='liked'){const r=await call(p,'channels?part=contentDetails&mine=true',uid);playlistId=r.items?.[0]?.contentDetails?.relatedPlaylists?.likes;if(!playlistId)fail(404,'LIKES_UNAVAILABLE','YouTube не открыл список понравившихся видео.');}const r=await call(p,`playlistItems?${new URLSearchParams({part:'snippet,contentDetails',playlistId,maxResults:'50',pageToken:cursor})}`,uid);return {tracks:await persist((r.items||[]).filter(t=>t.snippet?.resourceId?.videoId&&!['Private video','Deleted video'].includes(t.snippet.title)).map(x=>normalizeYoutube({...x,id:x.snippet.resourceId.videoId}))),nextCursor:r.nextPageToken||null};}fail(503,'PROVIDER_UNAVAILABLE','Этот источник не предоставляет подключённую библиотеку.');}
  app.get('/api/integrations/:provider/playlists',requireAuth,asyncRoute(async(req,res)=>res.json(await playlists(req.params.provider,req.auth.user.id,req.language))));
  app.get('/api/integrations/:provider/playlists/:id/tracks',requireAuth,asyncRoute(async(req,res)=>res.json(await playlistTracks(req.params.provider,req.auth.user.id,req.params.id,String(req.query.cursor||'')))));
  app.post('/api/integrations/:provider/import',requireAuth,asyncRoute(async(req,res)=>{if(!planLimits(req.auth.user).libraryImport)fail(403,'PLAN_LIMIT','Импорт доступен в Unbound.');const b=parse(z.object({playlistId:text(200),name:text(120).optional(),trackIds:z.array(text(200)).max(10000).optional()}).strict(),req.body),tracks=[];let cursor='',pages=0;do{const page=await playlistTracks(req.params.provider,req.auth.user.id,b.playlistId,cursor);tracks.push(...page.tracks);cursor=page.nextCursor;pages++;}while(cursor&&pages<200);if(cursor)fail(413,'IMPORT_TOO_LARGE','Плейлист слишком большой: выбери часть треков.');const selected=b.trackIds?tracks.filter(t=>b.trackIds.includes(t.id)):tracks;const playlist=await ctx.createPlaylist(req.auth.user.id,{name:b.name||systemText('importedTracks',req.language),trackIds:[...new Set(selected.map(t=>t.id))]});await ctx.audit('library.import',req.auth.user.id,{provider:req.params.provider,count:selected.length});res.status(201).json({playlist,imported:selected.length});}));
}
