import {Server} from 'socket.io';
import {z} from 'zod';
import {parse,text,fail,asyncRoute} from './util.js';
import {stateSchema,commandSchema,initialState,liveState} from './rooms.js';
import {languageCodes,browserLanguage} from './locale.js';
import {localizedError} from './messages.js';

export function setupRealtime(server,app,ctx){const {store,config,requireAuth}=ctx;
  const io=new Server(server,{cors:{origin:config.origins,credentials:true},maxHttpBufferSize:64*1024,allowRequest:(req,cb)=>cb(null,!req.headers.origin||config.origins.includes(req.headers.origin))});ctx.io=io;
  const live=new Map();
  const tokenFrom=socket=>{if(socket.handshake.auth.token)return socket.handshake.auth.token;const raw=socket.handshake.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('gw_session='));try{return raw?decodeURIComponent(raw.slice(11)):null;}catch{return null;}};
  io.use(async(socket,next)=>{const language=languageCodes.includes(socket.handshake.auth.language)?socket.handshake.auth.language:browserLanguage(socket.handshake.headers['accept-language'])||'en';try{const rawToken=tokenFrom(socket),auth=await ctx.authenticate(rawToken);if(!auth)fail(401,'AUTH_REQUIRED','Войди в GlukWave.');const d=parse(z.object({deviceId:text(100),name:text(100),kind:z.enum(['web','windows','android','ios','macos','linux']).default('web'),token:z.string().optional(),language:z.enum(languageCodes).optional()}),socket.handshake.auth);socket.data={userId:auth.user.id,rawToken,device:d,sessionId:auth.session.id,language};next();}catch(err){const body=localizedError({code:err.code||'AUTH_REQUIRED',message:err.message},language),error=new Error(body.message);error.data={code:body.code};next(error);}});
  const changes=uid=>io.to(`user:${uid}`).emit('devices:changed',{});
  async function ensure(socket){const auth=await ctx.authenticate(socket.data.rawToken);if(!auth){socket.disconnect(true);fail(401,'AUTH_REQUIRED','Сессия завершена.');}return auth;}
  io.on('connection',async socket=>{const {userId,device,sessionId}=socket.data,key=`${userId}:${device.deviceId}`;const old=live.get(key);if(old&&old!==socket.id)io.sockets.sockets.get(old)?.disconnect(true);live.set(key,socket.id);socket.join(`user:${userId}`);socket.join(`session:${sessionId}`);try{await store.update('devices',key,v=>({id:key,deviceId:device.deviceId,userId,name:device.name,kind:device.kind,lastSeen:Date.now(),online:true,state:v?.state||initialState()}));changes(userId);}catch(err){ctx.log.error({err},'Device registration failed');socket.disconnect();return;}
    let bucketTime=Date.now(),count=0;
    const on=(event,fn)=>socket.on(event,async(payload,ack)=>{try{if(Date.now()-bucketTime>1000){bucketTime=Date.now();count=0;}if(++count>30)fail(429,'REALTIME_LIMIT','Слишком много команд.');const auth=await ensure(socket);const result=await fn(payload,auth);if(typeof ack==='function')ack({ok:true,...result});}catch(err){const error=localizedError({code:err.code||'REALTIME_ERROR',message:err.status?err.message:'Не удалось выполнить команду.'},socket.data.language);if(typeof ack==='function')ack({error});else socket.emit('command:error',error);}});
    on('locale:change',async payload=>{const {language}=parse(z.object({language:z.enum(languageCodes)}).strict(),payload);socket.data.language=language;return {language};});
    on('device:state',async p=>{const state=parse(stateSchema,p);if(state.trackId)await ctx.requireTrack(state.trackId,(await ctx.authenticate(socket.data.rawToken)).user);await store.update('devices',key,v=>({...v,state:{...state,updatedAt:Date.now()},lastSeen:Date.now(),online:true}));changes(userId);return {};});
    on('room:join',async p=>{const {roomId}=parse(z.object({roomId:text(100)}).strict(),p),room=await ctx.requireRoom(roomId,userId),serverTime=Date.now(),state={...liveState(room.state,serverTime),updatedAt:serverTime};socket.join(`room:${roomId}`);socket.emit('room:state',{roomId,state,serverTime});socket.emit('room:members',{roomId,members:room.members});return {room:{...room,state}};});
    on('room:leave',async p=>{const {roomId}=parse(z.object({roomId:text(100)}).strict(),p);socket.leave(`room:${roomId}`);return {};});
    on('room:command',async p=>{const {roomId,...command}=parse(commandSchema.safeExtend({roomId:text(100)}),p);return ctx.roomCommand(userId,roomId,command);});
    socket.on('disconnect',async()=>{if(live.get(key)===socket.id){live.delete(key);try{await store.update('devices',key,v=>({...v,online:false,lastSeen:Date.now()}));changes(userId);}catch{}}});
  });
  app.get('/api/devices',requireAuth,asyncRoute(async(req,res)=>{const records=await store.list('devices',d=>d.userId===req.auth.user.id);res.json({devices:records.map(d=>({id:d.deviceId,name:d.name,kind:d.kind,online:live.has(d.id),lastSeen:d.lastSeen,state:d.state}))});}));
  async function dispatch(socketId,cmd){const socket=io.sockets.sockets.get(socketId);if(!socket)fail(409,'DEVICE_OFFLINE','Устройство отключено.');try{const result=await socket.timeout(10000).emitWithAck('device:command',cmd);if(result?.error)fail(409,result.error.code||'PLAYBACK_FAILED',result.error.message||'Устройство не начало воспроизведение.');return result;}catch(err){if(err.status)throw err;fail(504,'DEVICE_TIMEOUT','Устройство не подтвердило команду. Открой приложение и разреши воспроизведение.');}}
  app.post('/api/devices/command',requireAuth,asyncRoute(async(req,res)=>{const {deviceId,...cmd}=parse(commandSchema.safeExtend({deviceId:text(100)}),req.body),uid=req.auth.user.id,key=`${uid}:${deviceId}`,target=live.get(key);if(!target)fail(409,'DEVICE_OFFLINE','Устройство сейчас отключено.');for(const tid of [...(cmd.queue||[]),...(cmd.trackId?[cmd.trackId]:[])])await ctx.requireTrack(tid,req.auth.user);if(cmd.command==='transfer'){if(!cmd.fromDeviceId||cmd.fromDeviceId===deviceId)fail(400,'SOURCE_DEVICE','Выбери другое устройство.');const sourceKey=`${uid}:${cmd.fromDeviceId}`,sourceId=live.get(sourceKey),source=await store.get('devices',sourceKey);if(!source||!sourceId||!source.state.trackId)fail(409,'SOURCE_OFFLINE','На исходном устройстве нет активного трека.');const state=source.state,position=state.position+(state.playing?Math.max(0,Date.now()-state.updatedAt)/1000:0);await dispatch(sourceId,{command:'pause',localOnly:true,outputActive:false});try{await dispatch(target,{command:'track',trackId:state.trackId,position,queue:state.queue,volume:state.volume,localOnly:true,outputActive:true});if(!state.playing)await dispatch(target,{command:'pause',localOnly:true});}catch(err){if(state.playing)await dispatch(sourceId,{command:'play',localOnly:true,outputActive:true}).catch(()=>{});throw err;}}else {if(cmd.command==='ended')fail(400,'INVALID_COMMAND','Неверная команда устройства.');await dispatch(target,cmd);}res.json({ok:true});}));
  ctx.closeRealtime=()=>new Promise(resolve=>io.close(resolve));
}
