import {z} from 'zod';
import {id,now,secret,parse,text,fail,asyncRoute} from './util.js';

export const stateSchema=z.object({trackId:z.string().max(200).nullable(),position:z.number().finite().min(0).max(86400),playing:z.boolean(),volume:z.number().finite().min(0).max(1),queue:z.array(text(200)).max(1000),updatedAt:z.number().optional(),revision:z.number().int().optional()}).strict();
export const commandSchema=z.object({command:z.enum(['play','pause','seek','volume','track','next','previous','transfer','ended']),trackId:text(200).optional(),position:z.number().finite().min(0).max(86400).optional(),volume:z.number().finite().min(0).max(1).optional(),queue:z.array(text(200)).max(1000).optional(),fromDeviceId:text(100).optional(),expectedRevision:z.number().int().nonnegative().optional(),repeat:z.enum(['off','all','one']).optional()}).strict().refine(value=>value.command!=='ended'||(value.trackId!==undefined&&value.expectedRevision!==undefined),{message:'Ended requires track identity and room revision.'});
export const initialState=()=>({trackId:null,position:0,playing:false,volume:0.8,queue:[],updatedAt:Date.now(),revision:0});
export function liveState(state,time=Date.now()){return {...state,position:state.position+(state.playing?Math.max(0,time-state.updatedAt)/1000:0)};}
/** End notifications can arrive from several controllers; only one can consume this revision. */
export function applyTrackEnded(previous,command,duration=0,time=Date.now()){
  if(previous.trackId!==command.trackId||previous.revision!==command.expectedRevision||!previous.playing)return previous;
  const state=liveState(previous,time);
  if(duration>0&&state.position<duration-2)return previous;
  const index=state.queue.indexOf(state.trackId),repeat=command.repeat||'off';
  if(repeat==='one')state.position=0;
  else if(index>=0&&(index<state.queue.length-1||repeat==='all')){state.trackId=state.queue[(index+1)%state.queue.length];state.position=0;}
  else {state.playing=false;state.position=duration||state.position;}
  return {...state,updatedAt:time,revision:previous.revision+1};
}
export function applyCommand(previous,command,time=Date.now()){const state=liveState(previous,time);if(command.queue)state.queue=[...new Set(command.queue)];switch(command.command){case 'play':if(!state.trackId)fail(400,'NO_TRACK','Сначала выбери трек.');state.playing=true;break;case 'pause':state.playing=false;break;case 'seek':if(command.position===undefined)fail(400,'POSITION_REQUIRED','Укажи позицию.');state.position=command.position;break;case 'volume':if(command.volume===undefined)fail(400,'VOLUME_REQUIRED','Укажи громкость.');state.volume=command.volume;break;case 'track':if(!command.trackId)fail(400,'TRACK_REQUIRED','Выбери трек.');state.trackId=command.trackId;state.position=command.position||0;state.playing=true;if(!state.queue.includes(command.trackId))state.queue.push(command.trackId);break;case 'next':case 'previous':{if(!state.queue.length)fail(400,'EMPTY_QUEUE','Очередь пуста.');const index=state.queue.indexOf(state.trackId);if(command.command==='previous'&&state.position>3){state.position=0;break;}const next=command.command==='next'?(index+1)%state.queue.length:(Math.max(index,0)-1+state.queue.length)%state.queue.length;state.trackId=state.queue[next];state.position=0;state.playing=true;break;}default:fail(400,'INVALID_COMMAND','Неверная команда комнаты.');}state.updatedAt=time;state.revision=(previous.revision||0)+1;return state;}

export function setupRooms(app,ctx){const {store,config,requireAuth}=ctx;
  async function requireRoom(rid,uid){const r=await store.get('rooms',rid);if(!r||!r.members.some(m=>m.userId===uid))fail(404,'ROOM_NOT_FOUND','Комната не найдена.');return r;}
  const visibleRoom=(r,uid)=>{const serverTime=Date.now();return {...r,...(r.ownerId!==uid?{inviteCode:undefined}:{}),state:{...liveState(r.state,serverTime),updatedAt:serverTime}};};
  ctx.requireRoom=requireRoom;
  ctx.roomCommand=async(uid,rid,cmd)=>ctx.withLock('room:'+rid,async()=>{const user=await store.get('users',uid);const room=await requireRoom(rid,uid);if(!room.members.find(m=>m.userId===uid)?.canControl)fail(403,'ROOM_PERMISSION','Владелец комнаты ещё не дал доступ к управлению.');for(const tid of [...(cmd.queue||[]),...(cmd.trackId?[cmd.trackId]:[])])await ctx.requireTrack(tid,user);const finished=cmd.command==='ended'?await store.get('tracks',cmd.trackId):null;const result=await store.update('rooms',rid,r=>{if(!r?.members.find(m=>m.userId===uid)?.canControl)fail(403,'ROOM_PERMISSION','Право управления изменилось.');return {...r,state:cmd.command==='ended'?applyTrackEnded(r.state,cmd,finished?.duration||0):applyCommand(r.state,cmd)};});ctx.io?.to(`room:${rid}`).emit('room:state',{roomId:rid,state:result.state,serverTime:Date.now()});return {state:result.state};});
  app.get('/api/rooms',requireAuth,asyncRoute(async(req,res)=>res.json({rooms:(await store.list('rooms',r=>r.members.some(m=>m.userId===req.auth.user.id))).map(r=>visibleRoom(r,req.auth.user.id))})));
  app.post('/api/rooms',requireAuth,asyncRoute(ctx.quotaRoute('rooms',async(req,res)=>{const b=parse(z.object({name:text(80)}).strict(),req.body),u=req.auth.user,owned=await store.list('rooms',r=>r.ownerId===u.id);if(owned.length>=(u.plan==='free'?2:100))fail(403,'PLAN_LIMIT','Лимит комнат достигнут.');const r={id:id(),name:b.name,ownerId:u.id,members:[{userId:u.id,displayName:u.displayName,avatarUrl:u.avatarUrl,role:'owner',canControl:true}],state:initialState(),inviteCode:secret().slice(0,24),createdAt:now()};await store.create('rooms',r.id,r);res.status(201).json({room:r,inviteUrl:`${config.appUrl}/?room=${r.inviteCode}`});})));
  app.post('/api/rooms/join',requireAuth,asyncRoute(async(req,res)=>{const b=parse(z.object({inviteCode:text(100)}).strict(),req.body),room=(await store.list('rooms',r=>r.inviteCode===b.inviteCode))[0];if(!room)fail(404,'INVITE_NOT_FOUND','Приглашение не найдено или комната удалена.');const u=req.auth.user;const r=await store.update('rooms',room.id,v=>{if(v.members.some(m=>m.userId===u.id))return v;if(v.members.length>=50)fail(403,'ROOM_FULL','В комнате уже 50 участников.');return {...v,members:[...v.members,{userId:u.id,displayName:u.displayName,avatarUrl:u.avatarUrl,role:'member',canControl:false}]};});ctx.io?.to(`room:${r.id}`).emit('room:members',{roomId:r.id,members:r.members});ctx.notifyUser?.(r.ownerId,{title:r.name,kind:'room.join',values:{name:u.displayName},url:`/app/?roomId=${r.id}`}).catch(err=>ctx.log.warn({message:err.message},'Room notification failed'));res.json({room:visibleRoom(r,u.id)});}));
  app.get('/api/rooms/:id',requireAuth,asyncRoute(async(req,res)=>res.json({room:visibleRoom(await requireRoom(req.params.id,req.auth.user.id),req.auth.user.id)})));
  app.post('/api/rooms/:id/command',requireAuth,asyncRoute(async(req,res)=>res.json(await ctx.roomCommand(req.auth.user.id,req.params.id,parse(commandSchema,req.body)))));
  app.patch('/api/rooms/:id/members/:userId',requireAuth,asyncRoute(async(req,res)=>{const b=parse(z.object({canControl:z.boolean(),role:z.enum(['member','moderator']).optional()}).strict(),req.body);const r=await store.update('rooms',req.params.id,v=>{if(!v||v.ownerId!==req.auth.user.id)fail(403,'OWNER_REQUIRED','Права меняет владелец комнаты.');if(req.params.userId===v.ownerId)fail(400,'OWNER_ROLE','Владелец сохраняет управление.');if(!v.members.some(m=>m.userId===req.params.userId))fail(404,'MEMBER_NOT_FOUND','Участник не найден.');return {...v,members:v.members.map(m=>m.userId===req.params.userId?{...m,...b}:m)};});ctx.io?.to(`room:${r.id}`).emit('room:members',{roomId:r.id,members:r.members});res.json({room:r});}));
  app.post('/api/rooms/:id/leave',requireAuth,asyncRoute(async(req,res)=>{const r=await requireRoom(req.params.id,req.auth.user.id);if(r.ownerId===req.auth.user.id)fail(400,'OWNER_LEAVE','Перед уходом удали свою комнату.');const next=await store.update('rooms',r.id,v=>({...v,members:v.members.filter(m=>m.userId!==req.auth.user.id)}));ctx.io?.in(`user:${req.auth.user.id}`).socketsLeave(`room:${r.id}`);ctx.io?.to(`room:${r.id}`).emit('room:members',{roomId:r.id,members:next.members});res.json({ok:true});}));
  app.delete('/api/rooms/:id',requireAuth,asyncRoute(async(req,res)=>{const r=await requireRoom(req.params.id,req.auth.user.id);if(r.ownerId!==req.auth.user.id)fail(403,'OWNER_REQUIRED','Комнату удаляет владелец.');await store.remove('rooms',r.id);ctx.io?.to(`room:${r.id}`).emit('room:closed',{roomId:r.id});ctx.io?.in(`room:${r.id}`).socketsLeave(`room:${r.id}`);for(const m of await store.list('messages',m=>m.roomId===r.id))await store.remove('messages',m.id);res.json({ok:true});}));
  app.get('/api/rooms/:id/messages',requireAuth,asyncRoute(async(req,res)=>{await requireRoom(req.params.id,req.auth.user.id);res.json({messages:(await store.list('messages',m=>m.roomId===req.params.id)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).slice(-200)});}));
  app.post('/api/rooms/:id/messages',requireAuth,asyncRoute(ctx.quotaRoute('chat',async(req,res)=>{await requireRoom(req.params.id,req.auth.user.id);const b=parse(z.object({text:text(1000)}).strict(),req.body),u=req.auth.user;const recent=await store.list('messages',m=>m.userId===u.id&&Date.now()-Date.parse(m.createdAt)<60000);if(recent.length>=20)fail(429,'CHAT_LIMIT','Слишком много сообщений. Подожди минуту.');const message={id:id(),roomId:req.params.id,userId:u.id,displayName:u.displayName,text:b.text,createdAt:now()};await store.create('messages',message.id,message);ctx.io?.to(`room:${message.roomId}`).emit('room:message',{roomId:message.roomId,message});res.status(201).json({message});})));
}
