import {useCallback,useEffect,useRef,useState} from 'react';
import {LogOut,RefreshCw,ShieldCheck} from 'lucide-react';
import {api,ApiError,errorText} from './api';
import {useStore} from './store';
import {usePlayer} from './player';
import {DevicePlatformIcon,platformLabel} from './device-platform';
import {t,useLocale,getLanguage} from './locale';
import {Empty,Loading,Modal} from './ui';
import type {AccountSession} from './types';

function date(value:string|number){const parsed=new Date(value);return Number.isFinite(parsed.getTime())?parsed.toLocaleString(getLanguage(),{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';}
export function AccountSessions(){
  useLocale();const store=useStore(),player=usePlayer(),[sessions,setSessions]=useState<AccountSession[]>([]),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState(''),[unsupported,setUnsupported]=useState(false),[confirm,setConfirm]=useState<AccountSession|'others'|null>(null),generation=useRef(0);
  const refresh=useCallback(async()=>{const version=++generation.current;setLoading(true);try{const result=await api<{sessions:AccountSession[]}>('/account/sessions');if(version!==generation.current)return;if(!Array.isArray(result.sessions))throw new ApiError('SESSIONS_UNAVAILABLE',t('ecosystem.sessionsUnavailable'));setSessions(result.sessions);setError('');setUnsupported(false);}catch(error){if(version!==generation.current)return;setUnsupported(error instanceof ApiError&&['HTTP_404','NOT_FOUND','SESSIONS_UNAVAILABLE'].includes(error.code));setError(errorText(error));}finally{if(version===generation.current)setLoading(false);}},[store.user?.id]);
  useEffect(()=>{if(!store.user){setSessions([]);setLoading(false);return;}void refresh();return()=>{generation.current++;};},[store.user?.id,refresh]);
  useEffect(()=>{const changed=()=>void refresh();player.socket?.on('sessions:changed',changed);player.socket?.on('connect',changed);if(player.socket?.connected)changed();return()=>{player.socket?.off('sessions:changed',changed);player.socket?.off('connect',changed);};},[player.socket,refresh]);
  const revoke=async()=>{if(!confirm)return;setPending(true);setError('');try{await api(confirm==='others'?'/account/sessions':`/account/sessions/${encodeURIComponent(confirm.id)}`,{method:'DELETE'});const current=confirm!=='others'&&confirm.current;setConfirm(null);store.notify(t(confirm==='others'?'ecosystem.otherSessionsRemoved':'ecosystem.sessionRemoved'));if(current){store.setUser(null);store.setAuthOpen(true);}else await refresh();}catch(error){setError(errorText(error));}finally{setPending(false);}};
  const others=sessions.filter(session=>!session.current),ordered=[...sessions].sort((a,b)=>Number(b.current)-Number(a.current)||Number(new Date(b.lastActiveAt))-Number(new Date(a.lastActiveAt)));
  if(!store.user)return <Empty title={t('copy.043')} action={<button className="primary-button" onClick={()=>store.setAuthOpen(true)}>{t('copy.044')}</button>}/>;
  return <section className="settings-section sessions-section"><div className="settings-title"><ShieldCheck size={20}/><h2>{t('ecosystem.security')}</h2><button className="text-button sessions-refresh" disabled={loading||pending} onClick={()=>void refresh()}><RefreshCw size={15}/>{t('copy.129')}</button></div><p className="settings-note">{t('ecosystem.sessionsCaption')}</p>{error&&!confirm&&<div className="ecosystem-inline-error" role="alert"><p>{unsupported?t('ecosystem.sessionsUnavailable'):error}</p><button className="text-button" disabled={loading} onClick={()=>void refresh()}>{t('copy.129')}</button></div>}{loading&&!sessions.length?<Loading label={t('ecosystem.sessionsLoading')}/>:ordered.length?<div className="account-session-list">{ordered.map(session=><article className={`account-session ${session.current?'current':''}`} key={session.id}><span className="device-icon"><DevicePlatformIcon kind={session.kind}/></span><div className="session-details"><div className="session-title"><b>{session.deviceName||platformLabel(session.kind)}</b>{session.current&&<span className="session-current">{t('ecosystem.currentSession')}</span>}</div><span className="platform-tag">{platformLabel(session.kind)}</span><small><i className={`status-dot ${session.online?'':'offline'}`}/>{session.online?t('connect.online'):t('connect.offline')} · {t('ecosystem.activeAt',{date:date(session.lastActiveAt)})}</small><small>{t('ecosystem.signedInAt',{date:date(session.createdAt)})}</small></div><button className="icon-btn session-revoke" disabled={pending} title={t('ecosystem.signOutSession')} aria-label={t('ecosystem.signOutSession')} onClick={()=>setConfirm(session)}><LogOut size={17}/></button></article>)}</div>:!error&&<Empty title={t('ecosystem.noSessions')}/>}<div className="sessions-footer"><span><b>{t('ecosystem.otherSessions')}</b><small>{t('ecosystem.otherSessionsCaption')}</small></span><button className="subtle-button" disabled={loading||pending||!others.length} onClick={()=>setConfirm('others')}><LogOut size={16}/>{t('ecosystem.signOutOthers')}</button></div>{confirm&&<Modal title={t(confirm==='others'?'ecosystem.signOutOthers':'ecosystem.signOutSession')} onClose={()=>{if(!pending)setConfirm(null);}}><p className="settings-note">{confirm==='others'?t('ecosystem.confirmOthers',{count:others.length}):t(confirm.current?'ecosystem.confirmCurrent':'ecosystem.confirmSession',{device:confirm.deviceName})}</p>{error&&<p className="ecosystem-inline-error" role="alert">{error}</p>}<div className="session-confirm-actions"><button className="danger-button" disabled={pending} onClick={()=>void revoke()}>{pending?t('ecosystem.signingOut'):t('ecosystem.confirmSignOut')}</button><button className="subtle-button" disabled={pending} onClick={()=>setConfirm(null)}>{t('connect.cancel')}</button></div></Modal>}</section>;
}
