import {useEffect,useState} from 'react';
import {t,useLocale,getLanguage} from './locale';
import {api,patch,errorText} from './api';
import {useStore} from './store';
import {Loading} from './ui';
type ErrorRecord={id:string;platform:string;kind:string;message:string;stack:string;code:string;version:string;count:number;state:string;firstSeen:string;lastSeen:string;samples:{at:string;stack:string;route:string;userId?:string}[]};
type ErrorPage={errors:ErrorRecord[];total:number;page:number;counts:{open:number;resolved:number;ignored:number}};
export function AdminErrors(){
 useLocale();const store=useStore(),[platform,setPlatform]=useState(''),[state,setState]=useState('open'),[query,setQuery]=useState(''),[page,setPage]=useState(1),[result,setResult]=useState<ErrorPage|null>(null),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);const params=new URLSearchParams({page:String(page),...(platform?{platform}:{}),...(state?{state}:{}),...(query.trim()?{q:query.trim()}:{})});const timer=setTimeout(()=>{void api<ErrorPage>('/admin/errors?'+params,{signal:controller.signal}).then(setResult).catch(error=>{if(!controller.signal.aborted)store.notify(errorText(error),true);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},250);return()=>{clearTimeout(timer);controller.abort();};},[platform,state,query,page,revision]);
 return <section className="admin-section"><div className="section-heading"><div><h2>{t('errors.title')}</h2><p className="muted">{t('errors.description')}</p></div><button className="subtle-button" onClick={()=>setRevision(value=>value+1)}>{t('copy.129')}</button></div><div className="admin-error-filters"><label className="field">{t('errors.platform')}<select value={platform} onChange={event=>{setPlatform(event.target.value);setPage(1);}}><option value="">{t('errors.all')}</option>{['web','android','windows','ios','server'].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label className="field">{t('errors.state')}<select value={state} onChange={event=>{setState(event.target.value);setPage(1);}}><option value="">{t('errors.all')}</option>{['open','resolved','ignored'].map(value=><option key={value} value={value}>{t('errors.'+value)}</option>)}</select></label><label className="field">{t('errors.search')}<input type="search" value={query} maxLength={100} onChange={event=>{setQuery(event.target.value);setPage(1);}}/></label></div>{loading?<Loading/>:result&&<><p className="muted">{t('errors.open')}: {result.counts.open} · {t('errors.resolved')}: {result.counts.resolved} · {t('errors.ignored')}: {result.counts.ignored}</p><div className="admin-error-list">{result.errors.length?result.errors.map(error=><article key={error.id} className="admin-error-record"><div className="section-heading"><div><small>{error.platform} · {error.kind} · {error.version} · ×{error.count}</small><h3>{error.message}</h3></div><select aria-label={t('errors.state')} value={error.state} onChange={event=>void store.run(async()=>{await patch('/admin/errors/'+error.id,{state:event.target.value});setRevision(value=>value+1);})}>{['open','resolved','ignored'].map(value=><option key={value} value={value}>{t('errors.'+value)}</option>)}</select></div><time>{new Date(error.lastSeen).toLocaleString(getLanguage())}</time>{error.code&&<p>{error.code}</p>}<details><summary>{t('copy.148')}</summary>{error.stack&&<pre>{error.stack}</pre>}{error.samples.map((sample,index)=><p key={index}><time>{new Date(sample.at).toLocaleString(getLanguage())}</time> · {sample.route} {sample.userId?`· ${sample.userId}`:''}</p>)}</details></article>):<p className="muted">{t('errors.empty')}</p>}</div><div className="admin-error-pagination"><button className="subtle-button" disabled={page===1} onClick={()=>setPage(value=>value-1)}>←</button><span>{page} / {Math.max(1,Math.ceil(result.total/50))}</span><button className="subtle-button" disabled={page*50>=result.total} onClick={()=>setPage(value=>value+1)}>→</button></div></>}</section>;
}
