import {useEffect,useRef,useState} from 'react';
import {RefreshCw,Activity,ShieldCheck} from 'lucide-react';
import {api,errorText} from './api';
import {t,useLocale,number} from './locale';
import {Loading,Toggle,SourceMark} from './ui';
import {sourceNames,type Track} from './types';

type Extractors={adapters:{id:string;available:boolean}[];versions:Record<string,Record<string,string>>;queue:{active:number;queued:number;completed:number;failed:number;limit:number};streaming:number;metadataEntries:number;pending:number;conversion:string;ffmpeg:boolean};
type Resources={scope:string;cpuOneCorePercent:number;rssMB:number;heapUsedMB:number;heapTotalMB:number;eventLoopP99Ms:number;sampledAt:string;intervalMs:number};
type Permission={stream:boolean;download:boolean;convert:boolean;basis:'owner-permission'|'license-agreement';evidenceUrl:string;audioSourceUrl?:string;expiresAt?:number};
const blank:Permission={stream:false,download:false,convert:false,basis:'owner-permission',evidenceUrl:''};
export function ExtractorDiagnostics(){
 useLocale();const [extractors,setExtractors]=useState<Extractors|null>(null),[resources,setResources]=useState<Resources|null>(null),[tracks,setTracks]=useState<Track[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(''),[permission,setPermission]=useState<Permission>(blank),[existing,setExisting]=useState(false),[permissionLoading,setPermissionLoading]=useState(false),[pending,setPending]=useState(false),[permissionError,setPermissionError]=useState(''),[permissionUnavailable,setPermissionUnavailable]=useState(false),[permissionRevision,setPermissionRevision]=useState(0),[success,setSuccess]=useState(false),refreshRequest=useRef<AbortController|null>(null);
 const refresh=async()=>{
  refreshRequest.current?.abort();const request=new AbortController();refreshRequest.current=request;setLoading(true);setError('');
  const results=await Promise.allSettled([api<Extractors>('/admin/extractors',{signal:request.signal}),api<{resources:Resources}>('/admin/resources',{signal:request.signal}),api<{tracks:Track[]}>('/tracks',{signal:request.signal})]);if(request.signal.aborted)return;
  if(results[0].status==='fulfilled')setExtractors(results[0].value);if(results[1].status==='fulfilled')setResources(results[1].value.resources);if(results[2].status==='fulfilled')setTracks(results[2].value.tracks.filter(track=>track.source!=='local'));
  const failed=results.find(result=>result.status==='rejected');if(failed?.status==='rejected')setError(errorText(failed.reason));setLoading(false);
 };
 useEffect(()=>{void refresh();return()=>refreshRequest.current?.abort();},[]);
 useEffect(()=>{
  setPermission(blank);setExisting(false);setSuccess(false);setPermissionError('');setPermissionUnavailable(false);if(!selected){setPermissionLoading(false);return;}
  const request=new AbortController();setPermissionLoading(true);void api<{permission:Permission|null}>(`/admin/tracks/${encodeURIComponent(selected)}/audio-permission`,{signal:request.signal}).then(result=>{if(!request.signal.aborted&&result.permission){const value=result.permission;setPermission({stream:value.stream,download:value.download,convert:value.convert,basis:value.basis,evidenceUrl:value.evidenceUrl,...(value.audioSourceUrl?{audioSourceUrl:value.audioSourceUrl}:{}),...(value.expiresAt?{expiresAt:value.expiresAt}:{})});setExisting(true);}}).catch(error=>{if(!request.signal.aborted){setPermissionError(errorText(error));setPermissionUnavailable(true);}}).finally(()=>{if(!request.signal.aborted)setPermissionLoading(false);});return()=>request.abort();
 },[selected,permissionRevision]);
 const save=async(remove=false)=>{
  setPending(true);setSuccess(false);setPermissionError('');try{await api(`/admin/tracks/${encodeURIComponent(selected)}/audio-permission`,{method:remove?'DELETE':'PUT',...(remove?{}:{body:JSON.stringify(permission)})});setExisting(!remove);if(remove)setPermission(blank);setSuccess(true);}catch(error){setPermissionError(errorText(error));}finally{setPending(false);}
 };
 const selectedTrack=tracks.find(track=>track.id===selected),metric=(value:number|undefined,suffix='')=>Number.isFinite(value)?number(value!,{maximumFractionDigits:1})+suffix:'—';
 return <section className="admin-section extractor-section"><div className="section-heading"><h2><Activity size={18}/>{t('extractors.title')}</h2><button className="subtle-button" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={15}/>{t('copy.129')}</button></div><p className="settings-note">{t('extractors.resourcesCaption')}</p>{error&&<p className="ecosystem-inline-error" role="alert">{error}</p>}{loading&&!extractors?<Loading/>:<>
  {resources&&<dl className="resource-metrics"><div><dt>CPU</dt><dd>{metric(resources.cpuOneCorePercent,'%')}</dd></div><div><dt>RAM</dt><dd>{metric(resources.rssMB,' MB')}</dd></div><div><dt>{t('extractors.heap')}</dt><dd>{metric(resources.heapUsedMB,' MB')}</dd></div><div><dt>{t('extractors.latency')}</dt><dd>{metric(resources.eventLoopP99Ms,' ms')}</dd></div></dl>}
  {extractors&&<><div className="extractor-adapters">{extractors.adapters.map(adapter=><div key={adapter.id}><b>{sourceNames[adapter.id as keyof typeof sourceNames]||adapter.id}</b><span><i className={`status-dot ${adapter.available?'':'offline'}`}/>{t(adapter.available?'extractors.available':'extractors.unavailable')}</span></div>)}</div><dl className="resource-metrics queue-metrics"><div><dt>{t('extractors.active')}</dt><dd>{extractors.queue.active} / {extractors.queue.limit}</dd></div><div><dt>{t('extractors.queued')}</dt><dd>{extractors.queue.queued}</dd></div><div><dt>{t('extractors.completed')}</dt><dd>{extractors.queue.completed}</dd></div><div><dt>{t('extractors.failed')}</dt><dd>{extractors.queue.failed}</dd></div></dl><details className="extractor-versions"><summary>{t('extractors.versions')}</summary>{Object.entries(extractors.versions||{}).map(([source,versions])=><div key={source}><b>{sourceNames[source as keyof typeof sourceNames]||source}</b>{Object.entries(versions).map(([name,version])=><code key={name}>{name}: {String(version)}</code>)}</div>)}</details></>}
  <form className="permission-form" onSubmit={event=>{event.preventDefault();void save();}}><h3><ShieldCheck size={17}/>{t('extractors.permission')}</h3><p className="settings-note">{t('extractors.permissionCaption')}</p><label className="field">{t('extractors.track')}<select value={selected} disabled={pending||loading} onChange={event=>setSelected(event.target.value)}><option value="">{t('extractors.chooseTrack')}</option>{tracks.map(track=><option key={track.id} value={track.id}>{track.artist} — {track.title}</option>)}</select></label>
  {selected&&<><div className="permission-track"><SourceMark source={selectedTrack?.source||'soundcloud'} label/><span>{selectedTrack?.title}</span></div>{permissionLoading?<Loading/>:<fieldset disabled={pending||permissionUnavailable}>
   <Toggle checked={permission.stream} onChange={stream=>setPermission(value=>({...value,stream,...(!stream?{download:false,convert:false}:{})}))} label={t('extractors.stream')}/>
   <Toggle checked={permission.download} disabled={!permission.stream} onChange={download=>setPermission(value=>({...value,download,...(!download?{convert:false}:{})}))} label={t('extractors.download')}/>
   <Toggle checked={permission.convert} disabled={!permission.download} onChange={convert=>setPermission(value=>({...value,convert}))} label={t('extractors.convert')}/>
   <label className="field">{t('extractors.basis')}<select value={permission.basis} onChange={event=>setPermission(value=>({...value,basis:event.target.value as Permission['basis']}))}><option value="owner-permission">{t('extractors.owner')}</option><option value="license-agreement">{t('extractors.license')}</option></select></label>
   <label className="field">{t('extractors.evidence')}<input type="url" required pattern="https://.+" value={permission.evidenceUrl} placeholder="https://" onChange={event=>setPermission(value=>({...value,evidenceUrl:event.target.value}))}/></label>
   <label className="field">{t('extractors.audioSource')}<input type="url" required={selectedTrack?.source==='spotify'} pattern="https://.+" value={permission.audioSourceUrl||''} placeholder="https://soundcloud.com/…" onChange={event=>setPermission(value=>{const next={...value};if(event.target.value)next.audioSourceUrl=event.target.value;else delete next.audioSourceUrl;return next;})}/></label>
   <label className="field">{t('extractors.expiry')}<input type="datetime-local" value={permission.expiresAt?new Date(permission.expiresAt-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={event=>setPermission(value=>{const next={...value};if(event.target.value)next.expiresAt=new Date(event.target.value).getTime();else delete next.expiresAt;return next;})}/></label>
   <div className="permission-actions"><button className="primary-button" type="submit">{pending?t('extractors.saving'):t('extractors.save')}</button>{existing&&<button className="danger-button" type="button" onClick={()=>{if(window.confirm(t('extractors.revokeCaption')))void save(true);}}>{t('extractors.revoke')}</button>}</div>
  </fieldset>}{permissionError&&<div className="ecosystem-inline-error" role="alert"><p>{permissionError}</p>{permissionUnavailable&&<button type="button" className="text-button" onClick={()=>setPermissionRevision(value=>value+1)}>{t('copy.129')}</button>}</div>}{success&&<p className="permission-success" role="status">{t('extractors.saved')}</p>}</>}
  </form></>}
 </section>;
}
