import {useEffect,useRef,useState} from 'react';
import {t,useLocale} from './locale';
import {api,errorText} from './api';
import {useStore} from './store';
import {Modal,Loading} from './ui';
import {time,type Track} from './types';
import {geniusLyricsUrl,LyricsRequest} from './lyrics-model';
export type Lyrics={lines:{time:number|null;text:string}[];synchronized:boolean;source:string|null;raw?:string;providerId?:number;instrumental?:boolean;attribution?:string;sourceUrl?:string};
type Candidate=Lyrics&{providerId:number;title:string;artist:string;album:string;duration:number};
function lrc(lyrics:Lyrics){return lyrics.raw||lyrics.lines.map(line=>line.time===null?line.text:`[${String(Math.floor(line.time/60)).padStart(2,'0')}:${(line.time%60).toFixed(2).padStart(5,'0')}]${line.text}`).join('\n');}
export function LyricsImport({track,lyrics,onClose,onSaved}:{track:Track;lyrics:Lyrics;onClose:()=>void;onSaved:(lyrics:Lyrics)=>void}){
 useLocale();const store=useStore(),[text,setText]=useState(()=>lrc(lyrics)),[title,setTitle]=useState(track.title),[artist,setArtist]=useState(track.artist),[candidates,setCandidates]=useState<Candidate[]|null>(null),[selected,setSelected]=useState<Candidate|null>(null),[source,setSource]=useState<'lrclib'|'genius'>('lrclib'),[url,setUrl]=useState(''),[genius,setGenius]=useState<Lyrics|null>(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const request=useRef(new LyricsRequest()),saveRequest=useRef(new LyricsRequest()),scope=useRef(''),identity=`${track.id}:${store.user?.id||'guest'}`;scope.current=identity;
 useEffect(()=>{const preview=request.current,save=saveRequest.current;setLoading(false);setSaving(false);return()=>{preview.cancel();save.cancel();};},[identity]);
 const close=()=>{request.current.cancel();saveRequest.current.cancel();onClose();};
 const switchSource=(next:'lrclib'|'genius')=>{request.current.cancel();setLoading(false);setError('');setSource(next);};
 const search=async()=>{const controller=request.current.start(),owner=identity;setLoading(true);setError('');try{const result=await api<{candidates:Candidate[]}>(`/tracks/${encodeURIComponent(track.id)}/lyrics/search?`+new URLSearchParams({title,artist}),{signal:controller.signal});if(request.current.current(controller)&&scope.current===owner)setCandidates(result.candidates);}catch(error){if(request.current.current(controller)&&scope.current===owner)setError(errorText(error));}finally{if(request.current.current(controller)&&scope.current===owner)setLoading(false);}};
 const preview=async()=>{const valid=geniusLyricsUrl(url);if(!valid){setError(t('lyrics.geniusInvalid'));return;}const controller=request.current.start(),owner=identity;setLoading(true);setError('');try{const result=await api<Lyrics>(`/tracks/${encodeURIComponent(track.id)}/lyrics/genius/preview`,{method:'POST',body:JSON.stringify({url:valid}),signal:controller.signal});if(request.current.current(controller)&&scope.current===owner){setGenius(result);setSelected(null);setText(lrc(result));}}catch(error){if(request.current.current(controller)&&scope.current===owner)setError(errorText(error));}finally{if(request.current.current(controller)&&scope.current===owner)setLoading(false);}};
 const save=async()=>{if(saving||loading)return;const controller=saveRequest.current.start(),owner=identity;setSaving(true);setError('');const unchangedGenius=genius&&text===lrc(genius),unchangedLrclib=selected&&text===lrc(selected),path=`/tracks/${encodeURIComponent(track.id)}/lyrics`;try{const result=await api<Lyrics>(unchangedGenius?`${path}/genius`:unchangedLrclib?`${path}/lrclib`:path,{method:unchangedGenius||unchangedLrclib?'POST':'PUT',body:JSON.stringify(unchangedGenius?{url:genius.sourceUrl}:unchangedLrclib?{providerId:selected.providerId}:{text}),signal:controller.signal});if(saveRequest.current.current(controller)&&scope.current===owner){onSaved(result);store.notify(t('copy.682'));close();}}catch(error){if(saveRequest.current.current(controller)&&scope.current===owner)setError(errorText(error));}finally{if(saveRequest.current.current(controller)&&scope.current===owner)setSaving(false);}};
 return <Modal title={t('copy.681')} onClose={close}><form className="lyrics-editor" onSubmit={event=>{event.preventDefault();void save();}}>
  <div className="lyrics-source-tabs" aria-label={t('lyrics.source')}><button type="button" aria-pressed={source==='lrclib'} disabled={saving} onClick={()=>switchSource('lrclib')}>LRCLIB</button><button type="button" aria-pressed={source==='genius'} disabled={saving} onClick={()=>switchSource('genius')}>Genius</button></div>
  {source==='lrclib'?<><div className="lyrics-search-fields"><label className="field">{t('lyrics.title')}<input value={title} maxLength={200} onChange={event=>setTitle(event.target.value)} disabled={saving}/></label><label className="field">{t('lyrics.artist')}<input value={artist} maxLength={200} onChange={event=>setArtist(event.target.value)} disabled={saving}/></label><button type="button" className="subtle-button" disabled={loading||saving||!title.trim()||!artist.trim()} onClick={()=>void search()}>{t('lyrics.search')}</button></div>{!loading&&candidates&&<div className="lyrics-candidates">{candidates.length?candidates.map(candidate=><button type="button" disabled={saving} className={`subtle-button ${selected?.providerId===candidate.providerId?'selected':''}`} key={candidate.providerId} onClick={()=>{setSelected(candidate);setGenius(null);setText(lrc(candidate));}}><span><b>{candidate.title}</b><small>{candidate.artist} · {time(candidate.duration)} · {candidate.synchronized?t('lyrics.synced'):candidate.instrumental?t('lyrics.instrumental'):t('lyrics.plain')}</small></span></button>):<p className="muted">{t('lyrics.none')}</p>}</div>}</>:<section className="lyrics-genius-source"><div className="lyrics-genius-url"><label className="field">{t('lyrics.geniusUrl')}<input type="text" value={url} onChange={event=>{request.current.cancel();setLoading(false);setError('');setUrl(event.target.value);}} placeholder="https://genius.com/artist-song-lyrics" maxLength={2000} disabled={saving} autoComplete="off" inputMode="url"/></label><button type="button" className="subtle-button" disabled={loading||saving||!url.trim()} onClick={()=>void preview()}>{loading?t('lyrics.geniusLoading'):t('lyrics.geniusPreview')}</button></div><p className="lyrics-source-help">{t('lyrics.geniusHelp')}</p></section>}
  {loading&&<Loading label={source==='genius'?t('lyrics.geniusLoading'):undefined}/>}{error&&<p className="lyrics-source-error" role="alert">{error}</p>}
  {genius&&text===lrc(genius)&&<p className="lyrics-preview-credit"><span>{t('lyrics.geniusCredit')}</span>{geniusLyricsUrl(genius.sourceUrl||'')&&<a href={genius.sourceUrl} target="_blank" rel="noreferrer">{t('lyrics.geniusOriginal')}</a>}</p>}
  <label className="field">{t('copy.683')}<textarea name="text" value={text} onChange={event=>setText(event.target.value)} maxLength={100000} rows={10} placeholder={t('copy.684')} required={!selected?.instrumental} disabled={saving}/></label>
  <label className="file-link">{t('copy.685')}<input type="file" accept=".lrc,.txt,text/plain" disabled={saving} onChange={event=>{const input=event.currentTarget,file=input.files?.[0],owner=identity;if(!file)return;if(file.size>200000){store.notify(t('copy.686'),true);input.value='';return;}const controller=request.current.start();setLoading(false);void file.text().then(value=>{if(request.current.current(controller)&&scope.current===owner){setSelected(null);setGenius(null);setText(value.slice(0,100000));}input.value='';}).catch(error=>{if(request.current.current(controller)&&scope.current===owner)setError(errorText(error));});}}/></label>
  <div className="lyrics-editor-footer"><p className="muted lyric-import-note">{t(selected&&text===lrc(selected)?'lyrics.attribution':'lyrics.draftHelp')}</p><button className="primary-button" type="submit" disabled={saving||loading||!text.trim()&&!selected?.instrumental}>{saving?t('lyrics.saving'):t('copy.690')}</button></div>
 </form></Modal>;
}
