import {useRef,useState} from 'react';
import {t,useLocale} from './locale';
import {api,errorText,post} from './api';
import {useStore} from './store';
import {Modal,Loading} from './ui';
import {time,type Track} from './types';
export type Lyrics={lines:{time:number|null;text:string}[];synchronized:boolean;source:string|null;raw?:string;providerId?:number;instrumental?:boolean;attribution?:string;sourceUrl?:string};
type Candidate=Lyrics&{providerId:number;title:string;artist:string;album:string;duration:number};
function lrc(lyrics:Lyrics){return lyrics.raw||lyrics.lines.map(line=>line.time===null?line.text:`[${String(Math.floor(line.time/60)).padStart(2,'0')}:${(line.time%60).toFixed(2).padStart(5,'0')}]${line.text}`).join('\n');}
export function LyricsImport({track,lyrics,onClose,onSaved}:{track:Track;lyrics:Lyrics;onClose:()=>void;onSaved:(lyrics:Lyrics)=>void}){
 useLocale();const store=useStore(),[text,setText]=useState(()=>lrc(lyrics)),[title,setTitle]=useState(track.title),[artist,setArtist]=useState(track.artist),[candidates,setCandidates]=useState<Candidate[]|null>(null),[selected,setSelected]=useState<Candidate|null>(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false);const generation=useRef(0);
 const search=async()=>{const request=++generation.current;setLoading(true);try{const result=await api<{candidates:Candidate[]}>(`/tracks/${encodeURIComponent(track.id)}/lyrics/search?`+new URLSearchParams({title,artist}));if(request===generation.current)setCandidates(result.candidates);}catch(error){store.notify(errorText(error),true);}finally{if(request===generation.current)setLoading(false);}};
 return <Modal title={t('copy.681')} onClose={()=>{generation.current++;onClose();}}><form className="lyrics-editor" onSubmit={event=>{event.preventDefault();if(saving)return;setSaving(true);void store.run(async()=>{const result=selected&&text===selected.raw?await post<Lyrics>(`/tracks/${encodeURIComponent(track.id)}/lyrics/lrclib`,{providerId:selected.providerId}):await api<Lyrics>(`/tracks/${encodeURIComponent(track.id)}/lyrics`,{method:'PUT',body:JSON.stringify({text})});onSaved(result);onClose();},t('copy.682')).finally(()=>setSaving(false));}}><div className="lyrics-search-fields"><label className="field">{t('lyrics.title')}<input value={title} maxLength={200} onChange={event=>setTitle(event.target.value)}/></label><label className="field">{t('lyrics.artist')}<input value={artist} maxLength={200} onChange={event=>setArtist(event.target.value)}/></label><button type="button" className="subtle-button" disabled={loading||!title.trim()||!artist.trim()} onClick={()=>void search()}>{t('lyrics.search')}</button></div>{loading?<Loading/>:candidates&&<div className="lyrics-candidates">{candidates.length?candidates.map(candidate=><button type="button" className={`subtle-button ${selected?.providerId===candidate.providerId?'selected':''}`} key={candidate.providerId} onClick={()=>{setSelected(candidate);setText(candidate.raw||'');}}><span><b>{candidate.title}</b><small>{candidate.artist} · {time(candidate.duration)} · {candidate.synchronized?t('lyrics.synced'):candidate.instrumental?t('lyrics.instrumental'):t('lyrics.plain')}</small></span></button>):<p className="muted">{t('lyrics.none')}</p>}</div>}<label className="field">{t('copy.683')}<textarea name="text" value={text} onChange={event=>setText(event.target.value)} maxLength={100000} rows={10} placeholder={t('copy.684')} required={!selected?.instrumental}/></label><label className="file-link">{t('copy.685')}<input type="file" accept=".lrc,.txt,text/plain" onChange={event=>{const input=event.currentTarget,file=input.files?.[0];if(!file)return;if(file.size>200000){store.notify(t('copy.686'),true);input.value='';return;}void file.text().then(value=>{setSelected(null);setText(value.slice(0,100000));input.value='';}).catch(error=>store.notify(errorText(error),true));}}/></label><p className="muted lyric-import-note">{t('lyrics.attribution')}</p><button className="primary-button" type="submit" disabled={saving||!text.trim()&&!selected?.instrumental}>{t('copy.690')}</button></form></Modal>;
}
