import { useEffect, useState } from 'react';
import { ArrowRight, Globe, ImagePlus, LockKeyhole, Music2, Search, Trash2 } from 'lucide-react';
import { api, errorText } from './api';
import { t, useLocale, countLabel } from './locale';
import { useStore } from './store';
import { Empty, Loading, Modal, TrackList } from './ui';
import { playlistCovers } from './parity-model';
import type { Playlist, Track } from './types';
export function PlaylistArt({playlist}:{playlist:Playlist}){const covers=playlistCovers(playlist);return <span className={`playlist-collage covers-${playlist.artwork?1:covers.length}`}>{playlist.artwork?<img src={playlist.artwork} alt=""/>:covers.length?covers.map((src,index)=><img key={`${src}:${index}`} src={src} alt="" loading="lazy"/>):<Music2 size={32}/>}</span>;}
export function PlaylistCoverEditor({playlist}:{playlist:Playlist}){
 useLocale();const store=useStore(),[pending,setPending]=useState(false),[current,setCurrent]=useState(playlist),[error,setError]=useState('');useEffect(()=>setCurrent(playlist),[playlist]);
 const save=async(file?:File)=>{setPending(true);setError('');try{const form=new FormData();if(file)form.set('file',file);const result=await api<{playlist:Playlist}>(`/playlists/${playlist.id}/cover`,{method:file?'POST':'DELETE',...(file?{body:form}:{})});setCurrent(result.playlist);await store.refreshLibrary();}catch(reason){setError(errorText(reason));}finally{setPending(false);}};
 return <div className="playlist-cover-editor"><PlaylistArt playlist={current}/><div><label className="subtle-button file-link"><ImagePlus size={16}/>{pending?t('copy.085'):t('parity.customCover')}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={pending} onChange={event=>{const file=event.target.files?.[0];if(file)void save(file);event.target.value='';}}/></label>{current.artwork&&<button className="text-button" type="button" disabled={pending} onClick={()=>void save()}><Trash2 size={14}/>{t('parity.restoreCollage')}</button>}<small>{t('parity.coverCaption')}</small></div>{error&&<p className="error-banner" role="alert">{error}</p>}</div>;
}
export function PlaylistPublicField({playlist}:{playlist?:Playlist|null}){useLocale();return <label className="playlist-public-field"><input type="checkbox" name="public" defaultChecked={playlist?.public===true}/><Globe size={18}/><span><b>{t('parity.publicPlaylist')}</b><small>{t('parity.publicPlaylistCaption')}</small></span></label>;}
export function PlaylistDirectory(){
 useLocale();const store=useStore(),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[playlists,setPlaylists]=useState<Playlist[]>([]),[selected,setSelected]=useState<Playlist|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!open)return;const controller=new AbortController();setLoading(true);setError('');const timer=setTimeout(()=>void api<{playlists:Playlist[]}>(`/playlists/discover?q=${encodeURIComponent(query)}`,{signal:controller.signal}).then(result=>setPlaylists(result.playlists)).catch(reason=>{if(!controller.signal.aborted)setError(errorText(reason));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);}),250);return()=>{clearTimeout(timer);controller.abort();};},[open,query]);
 return <><button className="subtle-button" onClick={()=>setOpen(true)}><Globe size={16}/>{t('parity.publicPlaylists')}</button>{open&&<Modal title={t('parity.publicPlaylists')} onClose={()=>setOpen(false)} wide><label className="taste-search"><Search size={18}/><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('parity.findPlaylists')} aria-label={t('parity.findPlaylists')}/></label>{loading?<Loading/>:error?<p className="error-banner" role="alert">{error}</p>:playlists.length?<div className="public-playlist-list">{playlists.map(playlist=><button key={playlist.id} onClick={()=>setSelected(playlist)}><PlaylistArt playlist={playlist}/><span><b>{playlist.name}</b><small>{countLabel(playlist.trackIds.length,'tracks')}</small></span><ArrowRight size={17}/></button>)}</div>:<Empty icon={<Globe/>} title={t('parity.noPublicPlaylists')}/>}</Modal>}{selected&&<PublicPlaylist playlist={selected} onClose={()=>setSelected(null)}/>}</>;
}
export function PublicPlaylist({playlist,onClose}:{playlist:Playlist;onClose:()=>void}){useLocale();const [tracks,setTracks]=useState<Track[]|null>(null),[error,setError]=useState('');useEffect(()=>{const controller=new AbortController();void api<{playlist:Playlist;tracks:Track[]}>(`/playlists/${encodeURIComponent(playlist.id)}`,{signal:controller.signal}).then(result=>setTracks(result.tracks)).catch(reason=>{if(!controller.signal.aborted)setError(errorText(reason));});return()=>controller.abort();},[playlist.id]);return <Modal title={playlist.name} onClose={onClose} wide><header className="artist-page-heading"><PlaylistArt playlist={playlist}/><p className="intro">{playlist.description}</p></header>{error?<p className="error-banner" role="alert">{error}</p>:!tracks?<Loading/>:<TrackList tracks={tracks}/>}</Modal>;}
