import { useEffect, useState } from 'react';
import { ArrowRight, Check, Mail, Shield, Trash2 } from 'lucide-react';
import { api, errorText, patch, post } from './api';
import { clearPrivate } from './cache';
import { t, useLocale, number } from './locale';
import { useStore } from './store';
import { Empty, Loading, Modal, Toggle } from './ui';
import type { ListeningStats, User } from './types';
type Privacy={showActivity:boolean;profileStats:boolean;allowFriendRequests:boolean};
export function PrivacySettings(){
 useLocale();const store=useStore(),[reload,setReload]=useState(0),[privacy,setPrivacy]=useState<Privacy|null>(null),[error,setError]=useState(''),[pending,setPending]=useState(false);
 useEffect(()=>{setPrivacy(null);setError('');if(!store.user)return;const controller=new AbortController();void api<{privacy:Privacy}>('/account/privacy',{signal:controller.signal}).then(result=>setPrivacy(result.privacy)).catch(reason=>{if(!controller.signal.aborted)setError(errorText(reason));});return()=>controller.abort();},[store.user?.id,reload]);
 const save=(key:keyof Privacy,value:boolean)=>{setPending(true);setError('');void patch<{privacy:Privacy}>('/account/privacy',{[key]:value}).then(result=>setPrivacy(result.privacy)).catch(reason=>setError(errorText(reason))).finally(()=>setPending(false));};
 if(!store.user)return null;return <section className="settings-section"><div className="settings-title"><Shield size={20}/><h2>{t('parity.privacy')}</h2></div>{error&&<p className="error-banner" role="alert">{error}<button className="text-button" onClick={()=>setReload(value=>value+1)}>{t('copy.129')}</button></p>}{!privacy?!error&&<Loading/>:<>{(['showActivity','profileStats','allowFriendRequests'] as const).map(key=><Toggle key={key} checked={privacy[key]} disabled={pending} onChange={value=>save(key,value)} label={t(`parity.${key}`)} description={t(`parity.${key}Caption`)}/>)}</>}</section>;
}
export function AccountActions(){
 useLocale();const store=useStore(),[mode,setMode]=useState<'email'|'delete'|null>(null),[pending,setPending]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false);if(!store.user)return null;
 return <><div className="account-parity-actions"><button className="subtle-button" onClick={()=>{setError('');setSent(false);setMode('email');}}><Mail size={16}/>{t('parity.changeEmail')}</button><button className="text-button danger" onClick={()=>{setError('');setMode('delete');}}><Trash2 size={16}/>{t('parity.deleteAccount')}</button></div>{mode&&<Modal title={t(mode==='email'?'parity.changeEmail':'parity.deleteAccount')} onClose={()=>setMode(null)}>{sent?<div className="success-state" role="status"><Mail size={32}/><h3>{t('parity.checkEmail')}</h3><p>{t('parity.emailSent')}</p></div>:<form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);setPending(true);setError('');void (async()=>{try{if(mode==='email'){await post('/account/email',{email:form.get('email'),currentPassword:form.get('currentPassword')});setSent(true);}else {const id=store.user!.id;await api('/account',{method:'DELETE',body:JSON.stringify({currentPassword:form.get('currentPassword'),confirmation:form.get('confirmation')})});try{await clearPrivate(id);}finally{store.setUser(null);for(const key of ['gw-settings:'+id,'gw-settings-pending:'+id,'gw-settings-confirmed:'+id,'gw-room-'+id,'gw-mood:'+id])try{localStorage.removeItem(key);}catch{}};store.navigate('home');setMode(null);store.notify(t('parity.accountDeleted'));}}catch(reason){setError(errorText(reason));}finally{setPending(false);}})();}}><p className="intro">{t(mode==='email'?'parity.emailCaption':'parity.deleteCaption')}</p>{mode==='email'?<label className="field">{t('parity.newEmail')}<input name="email" type="email" autoComplete="email" required maxLength={254}/></label>:<label className="field">{t('parity.confirmUsername',{username:store.user.username})}<input name="confirmation" autoComplete="off" required pattern={store.user.username} placeholder={store.user.username}/></label>}<label className="field">{t('connect.currentPassword')}<input name="currentPassword" type="password" autoComplete="current-password" required/></label>{error&&<p className="error-banner" role="alert">{error}</p>}<button className={mode==='email'?'primary-button':'danger-button'} disabled={pending} type="submit">{pending?t('copy.085'):t(mode==='email'?'parity.sendConfirmation':'parity.deleteAccount')}<ArrowRight size={16}/></button></form>}</Modal>}</>;
}
export function EmailConfirmation(){useLocale();const store=useStore(),token=new URLSearchParams(location.search).get('emailConfirm'),[pending,setPending]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(''),[dismissed,setDismissed]=useState(false);if(!token||dismissed)return null;const close=()=>{setDismissed(true);const url=new URL(location.href);url.searchParams.delete('emailConfirm');history.replaceState(null,'',url);};return <Modal title={t('parity.confirmEmail')} onClose={close}>{done?<div className="success-state" role="status"><Check size={32}/><h3>{t('parity.emailChanged')}</h3><button className="primary-button" onClick={close}>{t('copy.736')}</button></div>:<><p className="intro">{t('parity.confirmEmailCaption')}</p>{error&&<p className="error-banner" role="alert">{error}</p>}<button className="primary-button" disabled={pending} onClick={()=>{setPending(true);void post<{ok:true;user:User}>('/account/email/confirm',{token}).then(result=>{if(store.user?.id===result.user.id)store.setUser(result.user);setDone(true);}).catch(reason=>setError(errorText(reason))).finally(()=>setPending(false));}}>{pending?t('copy.085'):t('parity.confirmEmail')}</button></>}</Modal>;}
export function ListeningStatistics(){
 useLocale();const store=useStore(),[stats,setStats]=useState<ListeningStats|null>(null),[error,setError]=useState('');
 useEffect(()=>{setStats(null);setError('');if(!store.user)return;const controller=new AbortController();void api<{stats:ListeningStats}>('/account/stats',{signal:controller.signal}).then(result=>setStats(result.stats)).catch(reason=>{if(!controller.signal.aborted)setError(errorText(reason));});return()=>controller.abort();},[store.user?.id]);
 if(!store.user)return null;return <section className="profile-listening"><div className="section-heading"><div><h2>{t('parity.statistics')}</h2><p className="section-caption">{t('parity.statisticsCaption')}</p></div></div>{error?<p className="error-banner" role="alert">{error}</p>:!stats?<Loading/>:<><div className="listening-stats"><span><b>{number(stats.plays)}</b>{t('parity.plays')}</span><span><b>{number(Math.floor(stats.listeningSeconds/60))}</b>{t('parity.minutes')}</span><span><b>{number(stats.artistCount)}</b>{t('search.artists')}</span><span><b>{number(stats.trackCount)}</b>{t('copy.132')}</span></div>{stats.topArtists.length>0&&<div className="top-artists"><h3>{t('parity.topArtists')}</h3>{stats.topArtists.map((artist,index)=><div key={artist.name}><span>{String(index+1).padStart(2,'0')}</span><b>{artist.name}</b><small>{number(artist.plays)} {t('parity.plays')}</small></div>)}</div>}{!stats.plays&&<p className="settings-note">{t('parity.statisticsEmpty')}</p>}</>}</section>;
}
