import { useEffect, useState } from 'react';
import { Download, Shield, Trash2, Upload } from 'lucide-react';
import { api, errorText, patch } from './api';
import { t, useLocale } from './locale';
import { useStore } from './store';
import { Loading, Modal, Toggle } from './ui';
import { bytes, type User } from './types';
type Release={platform:string;version:string;channel:string;signature:string;url:string;available:boolean;bytes:number;sha256:string;format?:string};
export function AdminListeningSummary({listening,plans,deviceCount}:{listening?:{plays:number;listeningSeconds:number;listeners:number;trackCount:number};plans?:Record<string,number>;deviceCount?:number}){useLocale();if(!listening&&!plans&&deviceCount===undefined)return null;return <section className="admin-section admin-listening"><h2>{t('parity.serviceListening')}</h2><div className="admin-stats">{listening&&<><div><small>{t('parity.plays')}</small><b>{listening.plays}</b></div><div><small>{t('parity.minutes')}</small><b>{Math.floor(listening.listeningSeconds/60)}</b></div><div><small>{t('parity.listeners')}</small><b>{listening.listeners}</b></div><div><small>{t('copy.132')}</small><b>{listening.trackCount}</b></div></>}{deviceCount!==undefined&&<div><small>{t('copy.135')}</small><b>{deviceCount}</b></div>}{plans&&Object.entries(plans).map(([plan,count])=><div key={plan}><small>{plan.toUpperCase()}</small><b>{count}</b></div>)}</div><p className="settings-note">{t('parity.statisticsCaption')}</p></section>;}
export function AdminDeleteUser({user,onDeleted}:{user:User;onDeleted:()=>void}){
 useLocale();const store=useStore(),[open,setOpen]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState('');return <><button className="text-button danger" disabled={user.id===store.user?.id} title={t('parity.deleteUser')} onClick={()=>setOpen(true)}><Trash2 size={16}/><span className="sr-only">{t('parity.deleteUser')}</span></button>{open&&<Modal title={t('parity.deleteUser')} onClose={()=>setOpen(false)}><form onSubmit={event=>{event.preventDefault();const confirmation=new FormData(event.currentTarget).get('confirmation');setPending(true);setError('');void api(`/admin/users/${user.id}`,{method:'DELETE',body:JSON.stringify({confirmation})}).then(()=>{setOpen(false);onDeleted();}).catch(reason=>setError(errorText(reason))).finally(()=>setPending(false));}}><p className="intro">{t('parity.adminDeleteCaption',{name:user.displayName})}</p><label className="field">{t('parity.confirmUsername',{username:user.username})}<input name="confirmation" required autoComplete="off" pattern={user.username} placeholder={user.username}/></label>{error&&<p className="error-banner" role="alert">{error}</p>}<button className="danger-button" type="submit" disabled={pending}>{pending?t('copy.085'):t('parity.deleteUser')}</button></form></Modal>}</>;
}
export function AdminRegistration(){useLocale();const [owner,setOwner]=useState(false),[enabled,setEnabled]=useState<boolean|null>(null),[error,setError]=useState(''),[pending,setPending]=useState(false);useEffect(()=>{const controller=new AbortController();void api<{registration:{enabled:boolean};owner?:boolean}>('/admin/registration',{signal:controller.signal}).then(result=>{setEnabled(result.registration.enabled);setOwner(result.owner===true);}).catch(reason=>{if(!controller.signal.aborted)setError(errorText(reason));});return()=>controller.abort();},[]);return <section className="admin-section admin-registration"><div className="settings-title"><Shield size={20}/><h2>{t('parity.registration')}</h2></div>{error&&<p className="error-banner" role="alert">{error}</p>}{enabled===null?!error&&<Loading/>:<Toggle checked={enabled} disabled={pending||!owner} label={t('parity.allowRegistration')} description={t('parity.registrationCaption')} onChange={value=>{setPending(true);setError('');void patch<{registration:{enabled:boolean}}>('/admin/registration',{enabled:value}).then(result=>setEnabled(result.registration.enabled)).catch(reason=>setError(errorText(reason))).finally(()=>setPending(false));}}/>}</section>;}
export function AdminReleases(){
 useLocale();const [owner,setOwner]=useState(false),[releases,setReleases]=useState<Release[]|null>(null),[error,setError]=useState(''),[pending,setPending]=useState(false),[success,setSuccess]=useState(false),[platform,setPlatform]=useState<'android'|'windows'>('android');
 const refresh=async()=>{const result=await api<{releases:Release[]}>('/releases');setReleases(result.releases);};useEffect(()=>{void refresh().catch(reason=>setError(errorText(reason)));void api<{owner?:boolean}>('/admin/registration').then(result=>setOwner(result.owner===true)).catch(()=>{});},[]);
 return <section className="admin-section admin-releases"><div className="settings-title"><Upload size={20}/><h2>{t('parity.releases')}</h2></div><p className="settings-note">{t('parity.releaseCaption')}</p><div className="release-list">{releases?.map(release=><article key={release.platform}><span><b>{release.platform} · {release.version}</b><small>{release.channel} · {release.signature} · {bytes(release.bytes)}{release.format?` · ${release.format}`:''}</small><code>{release.sha256}</code></span>{release.available&&<a className="subtle-button" href={release.url} download><Download size={16}/>{t('copy.749')}</a>}</article>)}{releases?.length===0&&<p className="muted">{t('parity.noReleases')}</p>}</div>{owner?<form onSubmit={event=>{event.preventDefault();const element=event.currentTarget,form=new FormData(element);setPending(true);setError('');setSuccess(false);void api(`/admin/releases/${platform}`,{method:'POST',body:form}).then(async()=>{await refresh();setSuccess(true);element.reset();}).catch(reason=>setError(errorText(reason))).finally(()=>setPending(false));}}><div className="release-form-grid"><label className="field">{t('parity.platform')}<select value={platform} onChange={event=>setPlatform(event.target.value as 'android'|'windows')}><option value="android">Android</option><option value="windows">Windows</option></select></label><label className="field">{t('parity.version')}<input name="version" placeholder="1.0.0" pattern="[0-9]+\.[0-9]+\.[0-9]+([+-][a-zA-Z0-9.-]+)?" required/></label><label className="field">{t('parity.channel')}<select name="channel" defaultValue="beta"><option value="beta">Beta</option><option value="stable">Stable</option></select></label><label className="field">{t('parity.signature')}<select name="signature" defaultValue="debug"><option value="debug">Debug</option><option value="release">Release</option></select></label></div><label className="field">{t('parity.package')}<input name="file" type="file" accept={platform==='android'?'.apk':'.exe,.zip'} required/></label>{error&&<p className="error-banner" role="alert">{error}</p>}{success&&<p className="settings-note" role="status">{t('parity.releaseSaved')}</p>}<button className="primary-button" type="submit" disabled={pending}><Upload size={16}/>{pending?t('copy.085'):t('parity.uploadRelease')}</button></form>:<p className="settings-note">{t('parity.ownerOnly')}</p>}</section>;
}
