import {LyricsImport,type Lyrics} from './lyrics-import';
import { t, useLocale, getLanguage } from './locale';
import { AlbumCover } from './album';
import type { Device } from './types';
import { trackCount } from './types';
import { useEffect, useId, useLayoutEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { ChevronDown, Download, Heart, ListMusic, Maximize2, MessageCircle, Monitor, PictureInPicture2, Play, Pause, Repeat, Repeat1, Send, Shuffle, SkipBack, SkipForward, Smartphone, Trash2, Volume2, VolumeX, X, SlidersHorizontal, Headphones, LogOut, Radio } from 'lucide-react';
import { PlaybackSettings } from './playback-settings';
import { usePlayerGestures } from './player-gestures';
import { usePlayer, localDeviceId } from './player';
import { surfaceId } from './device-identity';
import {DevicePlatformIcon,platformLabel} from './device-platform';
import { useStore } from './store';
import { api, errorText, post } from './api';
import { AnimatedIcon } from './morph-icon';
import { ContinuousRange } from './continuous-range';
import { useVisualVisibility } from './visual-lifecycle';
import { Art, DownloadButton, Empty, IconButton, Loading, Modal, SourceMark, TrackList, TrackSkeleton } from './ui';
import { time, type Comment } from './types';
function Transport({large=false}:{large?:boolean}){useLocale();const player=usePlayer(),store=useStore(),canControl=!player.room||player.room.ownerId===store.user?.id||!!player.room.members.find(member=>member.userId===store.user?.id)?.canControl;return <div className={`transport ${large?'large':''}`}>
 <IconButton title={player.room?t('copy.625'):t('copy.626')} disabled={!!player.room} aria-pressed={player.shuffle} className={`icon-btn shuffle ${player.shuffle?'selected':''}`} onClick={()=>player.setShuffle(!player.shuffle)}><AnimatedIcon name="shuffle" size={18}/></IconButton>
 <IconButton title={t('copy.627')} className="icon-btn previous" onClick={()=>void player.command({command:'previous'})} disabled={!player.track||!canControl}><AnimatedIcon name="previous" size={21}/></IconButton>
 <button className="main-play" disabled={!player.track||!canControl&&player.room?.type!=='jam'} aria-label={player.state.playing?t('copy.628'):t('copy.629')} onClick={()=>void player.command({command:player.state.playing?'pause':'play'})}><AnimatedIcon name={player.state.playing?'pause':'play'} size={23}/></button>
 <IconButton title={t('copy.630')} className="icon-btn next" onClick={()=>void player.command({command:'next'})} disabled={!player.track||!canControl}><AnimatedIcon name="next" size={21}/></IconButton>
 <IconButton disabled={!!player.room} title={player.repeat==='off'?t('copy.631'):player.repeat==='all'?t('copy.632'):t('copy.633')} aria-pressed={player.repeat!=='off'} className={`icon-btn repeat ${player.repeat!=='off'?'selected':''}`} onClick={()=>player.setRepeat(player.repeat==='off'?'all':player.repeat==='all'?'one':'off')}><AnimatedIcon name={player.repeat==='one'?'repeatOne':'repeat'} size={18}/></IconButton>
 </div>;}
function Seek({full=false}:{full?:boolean}){useLocale();const player=usePlayer(),store=useStore(),canControl=!player.room||player.room.ownerId===store.user?.id||!!player.room.members.find(member=>member.userId===store.user?.id)?.canControl;return <div className={`progress-line ${full?'full-seek':''}`}><span>{time(player.state.position)}</span><ContinuousRange value={player.state.position} max={Math.max(1,player.duration)} step={.1} style={{'--progress':`${player.duration?player.state.position/player.duration*100:0}%`} as React.CSSProperties} label={t('copy.634')} onCommit={position=>void player.command({command:'seek',position})} disabled={!player.track||!canControl} resetKey={player.track?.id}/><span>{time(player.duration)}</span></div>;}
function TrackLike({className=''}:{className?:string}) {
 useLocale();const player=usePlayer(),store=useStore(),track=player.track;if(!track)return null;
 const liked=store.library.likedIds.includes(track.id);
 return <IconButton title={liked?t('copy.637'):t('copy.638')} aria-pressed={liked} className={`icon-btn ${className} ${liked?'liked':''}`} onClick={()=>void store.run(()=>store.like(track))}><AnimatedIcon name={liked?'heartFull':'heart'} size={19}/></IconButton>;
}
function WheelVolume({children,className='',value,onChange}:{children:ReactNode;className?:string;value:number;onChange:(volume:number)=>void}) {
 const box=useRef<HTMLDivElement>(null),current=useRef({value,onChange});current.current={value,onChange};
 useEffect(()=>{const node=box.current;if(!node)return;const wheel=(event:WheelEvent)=>{if(event.ctrlKey||!event.deltaY)return;event.preventDefault();const next=Math.round(Math.max(0,Math.min(1,current.current.value+(event.deltaY<0?.04:-.04)))*100)/100;current.current.value=next;current.current.onChange(next);};node.addEventListener('wheel',wheel,{passive:false});return()=>node.removeEventListener('wheel',wheel);},[]);
 return <div className={className} ref={box}>{children}</div>;
}
function EqualizerDialog({onClose}:{onClose:()=>void}){return <Modal title={t('v7.eq.title')} onClose={onClose} wide><div className="player-equalizer"><PlaybackSettings/></div></Modal>;}
export function PlayerBar(){
 useLocale();const player=usePlayer(),store=useStore(),[equalizer,setEqualizer]=useState(false),track=player.track,gesture=usePlayerGestures('mini');
 return <><footer {...gesture.handlers} className={`player ${track?'has-track':''} ${!player.outputHere&&track&&player.connectState?.activeDeviceId?'remote-output':''}`} aria-label={t('copy.635')}>
  <div className="player-track" style={{transform:gesture.shift?`translateX(${gesture.shift}px)`:undefined}}><Art track={track||undefined} className="player-art" onClick={()=>track?player.setFull(true):store.navigate('library')}/><button className="player-track-info" onClick={()=>track?player.setFull(true):store.navigate('library')}><b>{track?.title||t('copy.370')}</b><small>{track?.artist||t('copy.636')}</small></button></div>
  <div className="player-center"><Transport/><Seek/></div><TrackLike className="player-heart"/>
  <div className="player-tools"><IconButton title={t('v7.eq.title')} onClick={()=>setEqualizer(true)}><SlidersHorizontal size={18}/></IconButton><IconButton title={t('copy.639')} onClick={()=>player.setFull(true)} disabled={!track}><Maximize2 size={17}/></IconButton><IconButton title={t('copy.640')} onClick={()=>player.setFull(true,'queue')} disabled={!track}><AnimatedIcon name="queue" size={19}/></IconButton><IconButton title={t('copy.013')} className={`icon-btn ${!player.outputHere&&track&&player.connectState?.activeDeviceId?'selected':''}`} onClick={()=>store.requireAuth()&&player.setDevicesOpen(true)}><AnimatedIcon name="devices" size={20}/></IconButton>
   <WheelVolume className="volume-control" value={player.state.volume} onChange={volume=>void player.command({command:'volume',volume})}><IconButton title={player.state.volume?t('copy.641'):t('copy.642')} onClick={()=>void player.command({command:'volume',volume:player.state.volume?0:.8})}><AnimatedIcon name={player.state.volume?'volume':'muted'} size={19}/></IconButton><ContinuousRange value={player.state.volume} max={1} step={.01} label={t('copy.643')} onCommit={volume=>void player.command({command:'volume',volume})}/></WheelVolume>
  </div>{!player.outputHere&&track&&player.connectState?.activeDeviceId&&<button className="player-output-caption" onClick={()=>player.setDevicesOpen(true)}><Monitor size={11}/>{player.devices.find(device=>device.id===player.connectState?.activeDeviceId)?.name||t('connect.anotherDevice')}</button>}
  {player.autoplayBlocked&&<button className="autoplay-notice" onClick={()=>void player.command({command:'play'})}>{t('copy.644')}</button>}
 </footer>{equalizer&&<EqualizerDialog onClose={()=>setEqualizer(false)}/>}</>;
}
function LyricSkeleton(){return <div className="lyric-skeleton" role="status" aria-label={t('copy.658')}><span className="sr-only">{t('copy.658')}</span>{[82,64,92,74,58].map((width,index)=><i key={index} className="skeleton" style={{width:`${width}%`}}/>)}</div>;}
export function FullPlayer(){
 const locale=useLocale(),player=usePlayer(),store=useStore(),track=player.track,[tab,setTab]=useState<string>(player.fullTab),[lyrics,setLyrics]=useState<Lyrics>({lines:[],synchronized:false,source:''}),[comments,setComments]=useState<Comment[]>([]),[loading,setLoading]=useState(false),[lyricImport,setLyricImport]=useState(false),[equalizer,setEqualizer]=useState(false),[commentsError,setCommentsError]=useState(false),[reload,setReload]=useState(0);
 const dialog=useRef<HTMLDivElement>(null),cover=useRef<HTMLDivElement>(null),[coverOrigin,setCoverOrigin]=useState({x:0,y:0,scale:.15}),gesture=usePlayerGestures('full'),lyricsBox=useRef<HTMLDivElement>(null),lyricScrollUntil=useRef(0);
 useEffect(()=>setTab(player.fullTab),[player.fullTab,player.full]);
 useEffect(()=>{if(!player.full)return;const previous=document.activeElement as HTMLElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';document.body.classList.add('player-is-open');history.pushState({...history.state,gwPlayer:true},'',location.href);dialog.current?.querySelector<HTMLButtonElement>('.np-header button')?.focus();const back=()=>player.setFull(false);window.addEventListener('popstate',back);const focus=(event:KeyboardEvent)=>{if(event.key!=='Tab'||document.querySelector('dialog[open]'))return;const nodes=Array.from(document.querySelectorAll<HTMLElement>('.full-player button,.full-player input,.full-player [tabindex="0"],.persistent-provider button,.persistent-provider a,.persistent-provider iframe,.device-panel button,.device-panel input,.device-panel [tabindex="0"]')).filter(item=>item.getBoundingClientRect().width>0&&!item.closest('[inert]')&&!item.hasAttribute('disabled')),index=nodes.indexOf(document.activeElement as HTMLElement);if(!nodes.length)return;if(event.shiftKey&&index<=0){event.preventDefault();nodes.at(-1)?.focus();}else if(!event.shiftKey&&index===nodes.length-1){event.preventDefault();nodes[0].focus();}};window.addEventListener('keydown',focus);return()=>{window.removeEventListener('popstate',back);window.removeEventListener('keydown',focus);document.body.style.overflow=overflow;document.body.classList.remove('player-is-open');if(history.state?.gwPlayer)history.back();if(previous?.isConnected)previous.focus();};},[player.full]);
 useLayoutEffect(()=>{const measure=()=>{const mini=document.querySelector('.player-art')?.getBoundingClientRect(),holder=cover.current;if(!mini||!holder)return;const previous=holder.style.transform,transition=holder.style.transition;holder.style.transition='none';holder.style.transform='none';const stage=holder.querySelector('.album-stage')?.getBoundingClientRect(),album=holder.querySelector<HTMLElement>('.album-object');holder.style.transform=previous;holder.style.transition=transition;if(!stage||!album)return;const height=window.visualViewport?.height||window.innerHeight,progress=player.revealProgress??(player.full?1:0),sheet=(1-progress)*height;setCoverOrigin({x:mini.left+mini.width/2-(stage.left+stage.width/2),y:mini.top+mini.height/2-(stage.top+stage.height/2-sheet)-height,scale:mini.width/Math.max(1,album.offsetWidth)});};measure();window.addEventListener('resize',measure);return()=>window.removeEventListener('resize',measure);},[track?.id,player.full,tab,locale.language]);
 // Fetch once for the active track, including while the full player is closed.
 useEffect(()=>{if(!track){setLyrics({lines:[],synchronized:false,source:''});setComments([]);return;}const controller=new AbortController();setLoading(true);setCommentsError(false);setLyrics({lines:[],synchronized:false,source:''});setComments([]);Promise.allSettled([store.settings.lyrics?api<Lyrics>(`/tracks/${encodeURIComponent(track.id)}/lyrics`,{signal:controller.signal}):Promise.resolve({lines:[],synchronized:false,source:''}),store.settings.comments?api<{comments:Comment[]}>(`/tracks/${encodeURIComponent(track.id)}/comments`,{signal:controller.signal}):Promise.resolve({comments:[]})]).then(results=>{if(controller.signal.aborted)return;setLyrics(results[0].status==='fulfilled'?results[0].value:{lines:[],synchronized:false,source:''});setComments(results[1].status==='fulfilled'?results[1].value.comments:[]);setCommentsError(results[1].status==='rejected');setLoading(false);});return()=>controller.abort();},[track?.id,store.user?.id,reload,store.settings.lyrics,store.settings.comments]);
 useEffect(()=>{if(tab==='comments'&&!store.settings.comments||tab==='lyrics'&&!store.settings.lyrics)setTab('player');},[store.settings.comments,store.settings.lyrics,tab]);
 const activeLine=lyrics.synchronized?lyrics.lines.reduce((index,line,next)=>line.time!==null&&line.time<=player.state.position?next:index,-1):-1;
 useEffect(()=>{if(tab!=='lyrics'||!player.full||Date.now()<lyricScrollUntil.current)return;const box=lyricsBox.current,line=box?.querySelector<HTMLElement>(`[data-line="${activeLine}"]`);if(!box||!line)return;box.scrollTo({top:box.scrollTop+line.getBoundingClientRect().top-box.getBoundingClientRect().top-box.clientHeight/2+line.offsetHeight/2,behavior:store.motion?'smooth':'instant'});},[activeLine,tab,store.motion,player.full]);
 if(!track)return null;
 const seekLine=(line:Lyrics['lines'][number])=>{if(!lyrics.synchronized||line.time===null)return;lyricScrollUntil.current=0;void player.command({command:'seek',position:line.time});};
 const progress=player.revealProgress??(player.full?1:0),dragging=player.revealProgress!==null,coverStyle=matchMedia('(max-width:850px)').matches?{transform:progress<1?`translate(${coverOrigin.x*(1-progress)+gesture.shift}px,${coverOrigin.y*(1-progress)}px) scale(${coverOrigin.scale+(1-coverOrigin.scale)*progress})`:gesture.shift?`translateX(${gesture.shift}px)`:undefined} as CSSProperties:undefined;
 const lyricsPane=<section className="np-lyrics"><div className="section-heading"><div><p className="eyebrow">{lyrics.synchronized?t('copy.665'):t('copy.666')}</p><h2>{t('copy.652')}</h2></div><button className="subtle-button" onClick={()=>store.requireAuth()&&setLyricImport(true)}>{t('copy.667')}</button></div>{loading?<LyricSkeleton/>:lyrics.lines.length?<div ref={lyricsBox} className="lyrics-lines" onWheel={()=>{lyricScrollUntil.current=Date.now()+5000;}} onTouchStart={()=>{lyricScrollUntil.current=Date.now()+5000;}}>{lyrics.lines.map((line,index)=><button key={`${track.id}:${index}`} data-line={index} aria-current={activeLine===index?'true':undefined} className={activeLine===index?'active':''} disabled={!lyrics.synchronized||line.time===null} onClick={()=>seekLine(line)}>{line.text||'♪'}</button>)}</div>:<Empty title={t('copy.668')} action={<button className="text-button" onClick={()=>setReload(value=>value+1)}>{t('copy.129')}</button>}>{t('copy.669')}</Empty>}{lyrics.source&&<p className="lyric-source">{lyrics.source}</p>}</section>;
 const queuePane=<section className="np-queue"><div className="section-heading"><h2>{t('copy.670')}</h2><span className="muted">{trackCount(player.queue.length)}</span></div>{player.queue.map(item=><div className="queue-row" key={item.id}><Art track={item}/><button className="track-main" onClick={()=>void player.playTrack(item,player.queue)}><b>{item.title}</b><small>{item.artist}</small></button><IconButton title={t('copy.671')} onClick={()=>player.removeQueue(item.id)}><X size={17}/></IconButton></div>)}</section>;
 const commentsPane=<section className="np-comments"><div className="section-heading"><h2>{t('copy.672')}</h2><span className="muted">{t('copy.673')}</span></div><form className="comment-form" onSubmit={event=>{event.preventDefault();if(!store.requireAuth())return;const form=event.currentTarget,text=new FormData(form).get('text');void store.run(async()=>{await post(`/tracks/${track.id}/comments`,{text,position:player.state.position});setComments((await api<{comments:Comment[]}>(`/tracks/${track.id}/comments`)).comments);form.reset();});}}><input name="text" placeholder={t('copy.674')} maxLength={1000} required aria-label={t('copy.675')}/><span>{time(player.state.position)}</span><IconButton title={t('copy.676')} type="submit"><Send size={17}/></IconButton></form>{loading?<TrackSkeleton rows={3} label={t('copy.677')}/>:commentsError?<Empty title={t('connect.commentsUnavailable')} action={<button className="subtle-button" onClick={()=>setReload(value=>value+1)}>{t('copy.129')}</button>}/>:comments.length?<div className="comments-list">{comments.map(comment=><article key={comment.id} className="comment"><span className="comment-avatar">{comment.avatarUrl?<img src={comment.avatarUrl} alt=""/>:comment.displayName.slice(0,1)}</span><div><header><b>{comment.displayName}</b><button onClick={()=>void player.command({command:'seek',position:comment.position})}>{time(comment.position)}</button><small>{new Date(comment.createdAt).toLocaleDateString(getLanguage())}</small></header><p>{comment.text}</p></div>{(comment.userId===store.user?.id||store.user?.role==='admin')&&<IconButton title={t('copy.678')} onClick={()=>void store.run(async()=>{await api(`/comments/${comment.id}`,{method:'DELETE'});setComments(current=>current.filter(item=>item.id!==comment.id));})}><Trash2 size={15}/></IconButton>}</article>)}</div>:<Empty icon={<MessageCircle/>} title={t('copy.679')}>{t('copy.680')}</Empty>}</section>;
 return <div ref={dialog} {...gesture.handlers} role="dialog" aria-modal={player.full} aria-hidden={!player.full&&!dragging} inert={!player.full&&!dragging} aria-label={t('copy.645')} className={`full-player connected-player ${player.full?'is-open':''} ${dragging?'is-dragging':''} ${player.playback?.kind!=='audio'?'has-provider':''} details-${tab}`} style={{'--reveal':progress,'--details-opacity':Math.min(1,progress*2.4),transform:`translateY(${(1-progress)*100}dvh)`} as CSSProperties}>
 <div className="np-backdrop" aria-hidden="true" style={track.artwork?{backgroundImage:`url(${JSON.stringify(track.artwork)})`}:undefined}/><div className="full-player-inner"><div className="np-drag-handle" aria-hidden="true"><i/></div><header className="np-header"><IconButton title={t('copy.646')} onClick={()=>player.setFull(false)}><ChevronDown/></IconButton><div><span className="eyebrow">{t('copy.647')}</span><b>{player.room?.name||t('copy.648')}</b></div><IconButton title={t('copy.649')} onClick={()=>void store.run(player.mini)}><PictureInPicture2 size={20}/></IconButton></header><nav className="np-tabs" aria-label={t('copy.650')}>{[['player',t('copy.651')],...(store.settings.lyrics?[['lyrics',t('copy.652')]]:[]),['queue',t('copy.653')],...(store.settings.comments?[['comments',t('copy.654')]]:[])].map(([id,name])=><button key={id} aria-pressed={tab===id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{name}{id==='comments'&&comments.length>0&&<small>{comments.length}</small>}</button>)}</nav>
 <div className="np-layout"><section className="np-listening"><div ref={cover} className="np-cover-growth" style={coverStyle}><AlbumCover track={track} playing={player.state.playing} gestureOwned active={player.full||dragging}/></div><div className="np-controls"><PlayingOutput/><div className="np-track-heading"><div><h1>{track.title}</h1><p>{track.artist}</p><SourceMark source={track.source} label/></div></div><Seek full/><div className="np-transport-row"><TrackLike className="np-like"/><Transport large/><IconButton title={t('v7.eq.title')} className={`icon-btn np-eq ${store.settings.equalizer.enabled?'selected':''}`} onClick={()=>setEqualizer(true)}><SlidersHorizontal size={20}/></IconButton></div><WheelVolume className="np-volume" value={player.state.volume} onChange={volume=>void player.command({command:'volume',volume})}><AnimatedIcon name={player.state.volume?'volume':'muted'} size={18}/><ContinuousRange value={player.state.volume} max={1} step={.01} label={t('copy.643')} onCommit={volume=>void player.command({command:'volume',volume})}/><output>{Math.round(player.state.volume*100)}%</output></WheelVolume><div className="np-bottom-actions"><button onClick={()=>store.requireAuth()&&player.setDevicesOpen(true)}><Monitor size={17}/>{t('copy.013')}</button><DownloadButton track={track}/><button onClick={()=>store.requireAuth()&&player.setAddTrack(track)}><ListMusic size={17}/>{t('copy.655')}</button></div>{store.settings.lyrics&&store.settings.lyricsUnderCover&&<div className="lyrics-under-art" aria-live="off">{loading?<div className="under-lyrics-loading"><i className="skeleton"/><i className="skeleton"/><i className="skeleton"/></div>:lyrics.lines.length?lyrics.lines.slice(Math.max(0,activeLine),Math.max(0,activeLine)+3).map((line,index)=><button onClick={()=>seekLine(line)} disabled={!lyrics.synchronized||line.time===null} className={index===0?'active':''} key={`${track.id}:${Math.max(0,activeLine)+index}`}>{line.text}</button>):<button className="text-button" onClick={()=>setTab('lyrics')}>{t('copy.656')}</button>}</div>}</div></section>
 <aside className="np-side">{tab==='lyrics'?lyricsPane:tab==='comments'?commentsPane:tab==='queue'?queuePane:<><div className="np-side-heading"><Headphones size={18}/><p className="eyebrow">{t('copy.660')}</p></div>{store.settings.lyrics&&<div className="np-desktop-lyrics"><div className="section-heading"><h2>{t('copy.652')}</h2><button className="text-button" onClick={()=>setTab('lyrics')}>{t('copy.657')}</button></div>{loading?<LyricSkeleton/>:lyrics.lines.length?<div className="np-lyric-preview">{lyrics.lines.slice(Math.max(0,activeLine-1),Math.max(0,activeLine-1)+5).map((line,index)=><button onClick={()=>seekLine(line)} disabled={!lyrics.synchronized||line.time===null} className={index===(activeLine>0?1:0)?'active':''} key={`${track.id}:${Math.max(0,activeLine-1)+index}`}>{line.text}</button>)}</div>:<p className="muted">{t('copy.659')}</p>}</div>}<div className="section-heading np-up-next"><h2>{t('copy.661')}</h2><button className="text-button" onClick={()=>setTab('queue')}>{t('copy.640')}</button></div><TrackList tracks={player.queue.slice(Math.max(0,player.queue.findIndex(item=>item.id===track.id)+1),6)} compact empty={t('copy.369')}/>{store.settings.comments&&<button className="np-comments-shortcut" onClick={()=>setTab('comments')}><MessageCircle size={19}/><span>{t('copy.654')}<small>{t('copy.673')}</small></span><b>{comments.length||'+'}</b></button>}</>}</aside></div></div>{lyricImport&&<LyricsImport key={track.id} track={track} lyrics={lyrics} onClose={()=>setLyricImport(false)} onSaved={setLyrics}/>} {equalizer&&<EqualizerDialog onClose={()=>setEqualizer(false)}/>}</div>;
}
export function DevicesModal(){useLocale();const player=usePlayer(),panel=useRef<HTMLElement>(null),title=useId(),[mobile,setMobile]=useState(()=>matchMedia('(max-width:850px)').matches);
 useEffect(()=>{const media=matchMedia('(max-width:850px)'),update=()=>setMobile(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;document.body.classList.add('devices-is-open');panel.current?.querySelector<HTMLButtonElement>('.device-panel-header button')?.focus();return()=>{document.body.classList.remove('devices-is-open');if(previous?.isConnected)previous.focus();};},[]);
 useEffect(()=>{if(!mobile)return;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';const key=(event:KeyboardEvent)=>{if(event.key!=='Tab'||document.querySelector('dialog[open]'))return;const nodes=Array.from(panel.current?.querySelectorAll<HTMLElement>('button,input,a,[tabindex="0"]')||[]).filter(node=>!node.hasAttribute('disabled')&&node.getBoundingClientRect().width>0);if(!nodes.length)return;const index=nodes.indexOf(document.activeElement as HTMLElement);if(event.shiftKey&&index<=0){event.preventDefault();nodes.at(-1)?.focus();}else if(!event.shiftKey&&(index===nodes.length-1||index<0)){event.preventDefault();nodes[0].focus();}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;window.removeEventListener('keydown',key);};},[mobile]);
 return <>{mobile&&<div className="device-panel-scrim" aria-hidden="true" onClick={()=>player.setDevicesOpen(false)}/>}<aside ref={panel} className={`device-panel ${player.full?'in-full-player':''}`} role="dialog" aria-modal={mobile} aria-labelledby={title}><div className="device-sheet-handle" aria-hidden="true"/><header className="device-panel-header"><div><span className="eyebrow">GlukWave Connect</span><h2 id={title}>{t('copy.013')}</h2></div><IconButton title={t('copy.736')} onClick={()=>player.setDevicesOpen(false)}><X size={20}/></IconButton></header><div className="device-panel-content"><DevicesCatalog/></div></aside></>;
}
export function DevicesCatalog(){
 useLocale();const player=usePlayer(),store=useStore(),ordered=[...player.devices].sort((a,b)=>Number(b.id===player.connectState?.activeDeviceId)-Number(a.id===player.connectState?.activeDeviceId)||Number(b.id===localDeviceId)-Number(a.id===localDeviceId)||Number(b.online)-Number(a.online));
 if(!store.user)return <Empty icon={<Monitor/>} title={t('copy.043')} action={<button className="primary-button" onClick={()=>store.setAuthOpen(true)}>{t('copy.044')}</button>}/>;
 return <><ConnectPreferences showTrack={false}/><div className="device-catalog-heading"><p>{t('connect.devicesCaption')}</p><button className="text-button" disabled={player.devicesLoading} onClick={()=>void player.refreshDevices()}>{t('copy.129')}</button></div>{player.devicesError&&<p className="ecosystem-inline-error" role="alert">{player.devicesError}</p>}{player.devicesLoading&&!ordered.length?<Loading label={t('ecosystem.devicesLoading')}/>:<div className="device-list">{ordered.length?ordered.map(device=><DeviceCard key={device.id} device={device}/>):!player.devicesError&&<Empty icon={<Monitor/>} title={t('copy.701')}>{t('copy.702')}</Empty>}</div>}<button className="device-security-link text-button" onClick={()=>{player.setDevicesOpen(false);store.navigate('settings');location.hash='settings?section=security';}}><LogOut size={14}/>{t('ecosystem.manageSessions')}</button></>;
}
export function ConnectPreferences({showTrack=true}:{showTrack?:boolean}={}){
 useLocale();const player=usePlayer(),store=useStore(),[pending,setPending]=useState(false),independent=player.connectState?.independent||false,active=player.devices.find(device=>device.id===player.connectState?.activeDeviceId);
 return <div className="connect-preferences"><div className={`connect-status ${player.connectionStatus}`} role="status"><span className={`status-dot ${player.connectionStatus==='online'?'':'offline'}`}/><span>{player.connectionStatus==='online'?t('connect.online'):player.connectionStatus==='connecting'?t('connect.reconnecting'):t('connect.offline')}</span></div>{showTrack&&!independent&&player.track&&<button className="connect-playing" onClick={()=>player.setDevicesOpen(true)}><Art track={player.track}/><span><b>{player.track.title}</b><small>{active?t(player.state.playing?'connect.playingOn':'connect.pausedOn',{device:active.name}):t('connect.chooseOutput')}</small></span><Radio size={17}/></button>}<label className="settings-row connect-independent"><span><b>{t('connect.independent')}</b><small>{t('connect.independentCaption')}</small></span><span className="switch"><input type="checkbox" checked={independent} disabled={pending||!!player.room||player.connectionStatus!=='online'} onChange={event=>{setPending(true);void store.run(()=>Promise.resolve(player.setIndependent(event.target.checked))).finally(()=>setPending(false));}}/><span/></span></label></div>;
}
export function PlayingOutput({className=''}:{className?:string}){
 useLocale();const player=usePlayer(),active=player.devices.find(device=>device.id===player.connectState?.activeDeviceId),element=useRef<HTMLButtonElement>(null),visible=useVisualVisibility(element,!!player.track&&!!active);if(!player.track||!active)return null;
 return <button ref={element} data-visual-visible={visible} className={`playing-output-indicator ${className}`} onClick={()=>player.setDevicesOpen(true)}><DevicePlatformIcon kind={active.kind} size={14}/><span>{t(player.state.playing?'connect.playingOn':'connect.pausedOn',{device:active.name})}</span>{player.state.playing&&<span className="wave-live" aria-hidden="true"><i/><i/><i/></span>}</button>;
}
function DeviceCard({device}:{device:Device}){
 useLocale();const player=usePlayer(),store=useStore(),current=device.id===localDeviceId,active=device.id===player.connectState?.activeDeviceId,known=store.library.tracks.find(track=>track.id===device.state.trackId),[resolved,setResolved]=useState<import('./types').Track|null>(null),[pending,setPending]=useState(false),[confirmRemove,setConfirmRemove]=useState(false),[actionError,setActionError]=useState('');const track=active?player.track:device.track||known||resolved,element=useRef<HTMLElement>(null),visible=useVisualVisibility(element);
 useEffect(()=>{setResolved(null);if(active||device.track||known||!device.state.trackId)return;const controller=new AbortController();void api<{track:import('./types').Track}>(`/tracks/${encodeURIComponent(device.state.trackId)}`,{signal:controller.signal}).then(result=>{if(!controller.signal.aborted)setResolved(result.track);}).catch(()=>{});return()=>controller.abort();},[active,known?.id,device.state.trackId]);
 const action=async(operation:()=>Promise<unknown>,success?:string)=>{setPending(true);setActionError('');try{await operation();if(success)store.notify(success);await player.refreshDevices();}catch(error){setActionError(errorText(error));}finally{setPending(false);}};const send=(command:string)=>void action(()=>post('/devices/command',{deviceId:device.id,surfaceId:device.surfaceId,command}));
 const transferring=()=>{if(!player.track)return;void action(()=>current&&player.room&&!player.connectState?.activeDeviceId?player.joinRoom(player.room):post('/devices/command',{deviceId:device.id,command:'transfer',fromDeviceId:player.connectState?.activeDeviceId||localDeviceId,surfaceId:current?surfaceId:device.surfaceId}),t('copy.699'));};
 return <article ref={element} data-visual-visible={visible} className={`device-card ${current?'current':''} ${active?'active-output':''} ${device.online?'online':'offline'}`}>
 <header><span className="device-icon"><DevicePlatformIcon kind={device.kind}/></span><div className="device-identity"><b>{device.name}</b><span className="device-kind-line"><span className="platform-tag">{platformLabel(device.kind)}</span>{active&&<span className="device-current-badge">{t('connect.output')}</span>}</span><small><i className={`status-dot ${device.online?'':'offline'}`}/>{current&&player.connectionStatus==='connecting'?t('connect.reconnecting'):device.online?t('copy.064'):t('copy.065')}{current&&` · ${t('ecosystem.thisBrowser')}`}</small></div><IconButton title={t('connect.signOutDevice')} className="icon-btn device-remove" disabled={pending} onClick={()=>setConfirmRemove(value=>!value)}><LogOut size={16}/></IconButton></header>
 {device.surfaceCount!==undefined&&<p className="device-session-count">{t('ecosystem.deviceSessions',{sessions:device.sessions||0,surfaces:device.surfaceCount})}</p>}{device.roomId&&<p className="device-room-caption"><Headphones size={12}/>{device.roomId===player.room?.id?player.room.name:t('ecosystem.roomListening')}</p>}{track&&<div className="device-track"><Art track={track}/><span><b>{track.title}</b><small>{track.artist}</small></span>{(active?player.state.playing:device.state.playing)&&<span className="wave-live" aria-hidden="true"><i/><i/><i/><i/><i/></span>}</div>}
 {active&&player.track&&<div className="device-local-controls"><Transport/><Seek/><WheelVolume className="remote-device-controls" value={player.state.volume} onChange={volume=>void player.command({command:'volume',volume})}><label><AnimatedIcon name={player.state.volume?'volume':'muted'} size={16}/><ContinuousRange value={player.state.volume} max={1} step={.01} label={t('copy.643')} onCommit={volume=>void player.command({command:'volume',volume})}/><output>{Math.round(player.state.volume*100)}%</output></label></WheelVolume></div>}
 {(player.connectState?.activeDeviceId||current&&player.room)&&(!active||current&&player.connectState?.activeSurfaceId!==surfaceId)&&<><div className="device-actions"><div>{!active&&player.connectState?.independent&&<><IconButton disabled={pending||!device.online||!device.state.trackId} title={t('copy.695')} onClick={()=>send('previous')}><AnimatedIcon name="previous" size={19}/></IconButton><IconButton disabled={pending||!device.online||!device.state.trackId} title={device.state.playing?t('copy.696'):t('copy.697')} onClick={()=>send(device.state.playing?'pause':'play')}><AnimatedIcon name={device.state.playing?'pause':'play'} size={22}/></IconButton><IconButton disabled={pending||!device.online||!device.state.trackId} title={t('copy.698')} onClick={()=>send('next')}><AnimatedIcon name="next" size={19}/></IconButton></>}</div>{player.track&&<button className="subtle-button" disabled={pending||!device.online||player.connectionStatus!=='online'} onClick={transferring}>{pending?t('v7.devices.transferring'):current?t('connect.listenHere'):t('connect.transferHere')}</button>}</div>{!active&&player.connectState?.independent&&<RemoteDeviceControls device={device} duration={track?.duration||0}/>}</>}
 {!device.online&&<p className="device-last-seen">{t('connect.lastSeen',{date:new Date(device.lastSeen).toLocaleString(getLanguage(),{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})})}</p>}
 {actionError&&<p className="ecosystem-inline-error" role="alert">{actionError}</p>}{confirmRemove&&<div className="device-remove-confirm"><p>{t(current?'connect.signOutCurrentCaption':'connect.signOutCaption')}</p><button className="danger-button" disabled={pending} onClick={()=>void action(()=>player.removeDevice(device.id),t('connect.deviceRemoved'))}>{t('connect.signOutDevice')}</button><button className="text-button" onClick={()=>setConfirmRemove(false)}>{t('connect.cancel')}</button></div>}
 </article>;
}
function RemoteDeviceControls({device,duration}:{device:Device;duration:number}){
 useLocale();const store=useStore();return <div className="remote-device-controls"><WheelVolume className="remote-volume-row" value={device.state.volume} onChange={volume=>void store.run(()=>post('/devices/command',{deviceId:device.id,command:'volume',volume}))}><label><AnimatedIcon name={device.state.volume?'volume':'muted'} size={16}/><ContinuousRange value={device.state.volume} max={1} step={.01} resetKey={device.id} label={t('template.009',{v0:device.name})} onCommit={volume=>void store.run(()=>post('/devices/command',{deviceId:device.id,command:'volume',volume}))}/><output>{Math.round(device.state.volume*100)}%</output></label></WheelVolume>{duration>0&&<label><span>{time(device.state.position)}</span><ContinuousRange value={device.state.position} max={duration} resetKey={`${device.id}:${device.state.trackId}`} label={t('template.010',{v0:device.name})} onCommit={position=>void store.run(()=>post('/devices/command',{deviceId:device.id,command:'seek',position}))}/><span>{time(duration)}</span></label>}</div>;
}
