import {useEffect,useRef} from 'react';
import {t,useLocale} from './locale';
import {useStore} from './store';
import {useDocumentVisible} from './visual-lifecycle';
import {Toggle} from './ui';
import type {SeasonalEffects} from './types';
import {Snowflake,CloudRain,Leaf,Sun,CalendarDays} from 'lucide-react';
export function seasonForMonth(month:number):Exclude<SeasonalEffects['mode'],'auto'> {return month===12||month<=2?'snow':month<=5?'rain':month<=8?'sun':'leaves';}
function SeasonCanvas({mode,intensity,animate,preview=false}:{mode:Exclude<SeasonalEffects['mode'],'auto'>;intensity:SeasonalEffects['intensity'];animate:boolean;preview?:boolean}) {
 const canvas=useRef<HTMLCanvasElement>(null),store=useStore();
 useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;let frame=0,width=0,height=0,elapsed=0,last=0;const seed=(i:number,n:number)=>{const x=Math.sin(i*128.13+n*37.77)*43758.5453;return x-Math.floor(x);};
 const paint=(now:number)=>{if(animate&&last&&now-last<33){frame=requestAnimationFrame(paint);return;}if(last)elapsed+=Math.min(100,now-last)/1000;last=now;ctx.clearRect(0,0,width,height);const count=preview?16:width<600?24:40;const dark=store.resolvedTheme!=='light',amount=intensity==='normal'?.76:.37;ctx.lineWidth=1.45;
  if(mode==='sun'){
   const warm=dark?'237,200,144':'217,169,118',radius=Math.max(width,height)*.6;
   for(let i=0;i<3;i++){const phase=elapsed*Math.PI/30+i*2.1,x=width*([.12,.82,.56][i]+Math.sin(phase)*.025),y=height*([.14,.32,.94][i]+Math.cos(phase)*.03),glow=ctx.createRadialGradient(x,y,0,x,y,radius);glow.addColorStop(0,`rgba(${warm},${amount*.08})`);glow.addColorStop(.45,`rgba(${warm},${amount*.036})`);glow.addColorStop(1,`rgba(${warm},0)`);ctx.fillStyle=glow;ctx.fillRect(0,0,width,height);}
  }else for(let i=0;i<count;i++){const x=seed(i,1)*width,y=((seed(i,2)*height+elapsed*(mode==='rain'?34:mode==='leaves'?10:8))%(height+28))-14,phase=elapsed*.35+seed(i,3)*6.28,size=2.2+seed(i,4)*2.6;ctx.save();ctx.globalAlpha=amount*(.5+seed(i,5)*.35);if(mode==='snow'){ctx.fillStyle=dark?'#edf6ff':'#536e83';ctx.beginPath();ctx.arc(x+Math.sin(phase)*12,y,size,0,Math.PI*2);ctx.fill();}else if(mode==='rain'){ctx.strokeStyle=dark?'#a9d8ee':'#486f88';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-3,y+11+size*2.4);ctx.stroke();}else if(mode==='leaves'){ctx.fillStyle=(dark?['#e0ad70','#c4bd85','#db986e']:['#99622e','#6f7b42','#af6944'])[i%3];ctx.translate(x+Math.sin(phase)*18,y);ctx.rotate(phase);ctx.beginPath();ctx.ellipse(0,0,size*1.8,size*.8,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=dark?'#f4d1a5':'#69462d';ctx.lineWidth=.8;ctx.beginPath();ctx.moveTo(-size*1.6,0);ctx.lineTo(size*1.7,0);ctx.stroke();}ctx.restore();}
  if(animate)frame=requestAnimationFrame(paint);
 };const resize=()=>{const rect=el.getBoundingClientRect();width=rect.width;height=rect.height;const ratio=Math.min(1.5,devicePixelRatio||1);el.width=Math.ceil(width*ratio);el.height=Math.ceil(height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);if(!animate)paint(0);};const observer=new ResizeObserver(resize);observer.observe(el);resize();if(animate)frame=requestAnimationFrame(paint);return()=>{cancelAnimationFrame(frame);observer.disconnect();};},[mode,intensity,animate,preview,store.resolvedTheme]);
 return <canvas ref={canvas} className="season-canvas" data-season={mode} data-moving={animate} aria-hidden="true"/>;
}
export function SeasonalAtmosphere({active=true}:{active?:boolean}){const store=useStore(),visible=useDocumentVisible(),season=store.settings.seasonalEffects;if(!active||!season.enabled||!visible||!store.motion)return null;return <div className="season-atmosphere"><SeasonCanvas mode={season.mode==='auto'?seasonForMonth(new Date().getMonth()+1):season.mode} intensity={season.intensity} animate/></div>;}
const modes=[['auto',CalendarDays],['snow',Snowflake],['rain',CloudRain],['leaves',Leaf],['sun',Sun]] as const;
export function SeasonalSettings(){useLocale();const store=useStore(),visible=useDocumentVisible(),season=store.settings.seasonalEffects,mode=season.mode==='auto'?seasonForMonth(new Date().getMonth()+1):season.mode;const change=(patch:Partial<SeasonalEffects>)=>void store.saveSettings({seasonalEffects:patch});return <section className="season-settings" aria-label={t('season.title')}><Toggle checked={season.enabled} onChange={enabled=>change({enabled})} label={t('season.title')} description={t('season.caption')}/><div className="season-preview" aria-label={t('season.preview')}><SeasonCanvas mode={mode} intensity={season.intensity} animate={season.enabled&&store.motion&&visible} preview/><div><span>{t('season.preview')}</span><b>{t('season.'+mode)}</b></div></div><div className="season-options" role="group" aria-label={t('season.mode')}>{modes.map(([id,Icon])=><button key={id} type="button" aria-pressed={season.mode===id} onClick={()=>change({mode:id})}><Icon size={17}/><span>{t('season.'+id)}</span></button>)}</div><label className="settings-row"><span><b>{t('season.intensity')}</b><small>{t('season.motionHint')}</small></span><select aria-label={t('season.intensity')} value={season.intensity} onChange={e=>change({intensity:e.target.value as SeasonalEffects['intensity']})}><option value="subtle">{t('season.subtle')}</option><option value="normal">{t('season.normal')}</option></select></label></section>;}
