import { t, useLocale } from './locale';
import { AnimatedIcon } from './morph-icon';
import { trackCount } from './types';
import { useEffect, useId, useRef, useState, type ButtonHTMLAttributes, type ReactNode } from 'react';
import { ArrowRight, Check, Cloud, Disc3, Download, Heart, Music2, Play, Plus, Radio, Waves, X, Youtube } from 'lucide-react';
import { useStore } from './store';
import { sourceNames, time, type Source, type Track } from './types';
import { usePlayer } from './player';
import { post, patch } from './api';
import { cached, pinDownload, saveTrack } from './cache';
export function IconButton({title,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{title:string}){useLocale();return <button className="icon-btn" aria-label={title} title={title} {...props}>{children}</button>;}
export function BrandGraphic({animated=false}:{animated?:boolean}){return <span className="brand"><span className="logo-window"><img src={animated?'/brand/logo.gif':'/brand/logo.png'} alt="" width="80" height="45"/></span><span>gluk<span className="brand-light">wave</span><i/></span></span>;}
export function Brand({animated=true}:{animated?:boolean}){useLocale();const{motion}=useStore(),[visible,setVisible]=useState(!document.hidden);useEffect(()=>{const update=()=>setVisible(!document.hidden);document.addEventListener('visibilitychange',update);return()=>document.removeEventListener('visibilitychange',update);},[]);return <BrandGraphic animated={animated&&visible&&motion}/>;}
export function SourceMark({source,label=false}:{source:Source|string;label?:boolean}){useLocale();const Icon=source==='youtube'?Youtube:source==='soundcloud'?Cloud:Music2;return <span className={`source-badge ${source}`}>{source==='spotify'?<svg viewBox="0 0 24 24" aria-hidden="true" fill="none"><path d="M4.5 8.2c4.7-1.4 10.4-1.1 15 1.6M5.5 12.1c4-1.1 8.9-.8 12.5 1.5M6.4 15.8c3.3-.7 7-.5 10 1.3" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>:source==='yandex'?<svg viewBox="0 0 24 24" aria-hidden="true" fill="currentColor"><path d="m12 2 2.5 6.1L21 10l-5.7 4.1.8 6.9-5.2-4.5L4.5 20l2.6-6.4L2 9l6.7-.5L12 2Z" stroke="none"/></svg>:<Icon size={15}/>}{label&&(sourceNames[source as Source]||source)}</span>;}
function largeArtwork(value:string|undefined){if(!value)return value;try{const url=new URL(value);if(url.hostname.endsWith('.sndcdn.com'))url.pathname=url.pathname.replace(/-(?:large|t\d+x\d+)\.(jpg|jpeg|png)$/i,'-t500x500.$1');return url.href;}catch{return value;}}
export function Art({track,className='',onClick,highResolution=false}:{track?:Track;className?:string;onClick?:()=>void;highResolution?:boolean}){useLocale();const original=track?.artwork,[fallback,setFallback]=useState(false),artwork=highResolution&&!fallback?largeArtwork(original):original,[status,setStatus]=useState<'pending'|'ready'|'error'>(artwork?'pending':'error');useEffect(()=>{setFallback(false);},[original,highResolution]);useEffect(()=>setStatus(artwork?'pending':'error'),[artwork]);const content=<>{artwork&&status!=='error'&&<img key={artwork} src={artwork} alt="" loading="lazy" onLoad={()=>setStatus('ready')} onError={()=>{if(artwork!==original){setFallback(true);setStatus('pending');}else setStatus('error');}}/>} {status==='pending'?<span className="skeleton art-skeleton" aria-hidden="true"/>:status==='error'?<Disc3 aria-hidden="true"/>:null}</>;return onClick?<button className={`art ${className} ${status==='pending'?'art-pending':''}`} onClick={onClick} aria-label={t('template.023', {v0: track?.title||t('copy.733')})}>{content}</button>:<span className={`art ${className} ${status==='pending'?'art-pending':''}`}>{content}</span>;}
export function TrackSkeleton({rows=5,label=t('copy.734')}:{rows?:number;label?:string}){useLocale();return <div className="track-skeleton-list" role="status" aria-label={label}><span className="sr-only">{label}</span>{Array.from({length:rows},(_,index)=><div className="track-skeleton-row" aria-hidden="true" key={index}><i className="skeleton skeleton-cover"/><div><i className="skeleton skeleton-title"/><i className="skeleton skeleton-subtitle"/></div><i className="skeleton skeleton-action"/></div>)}</div>;}
export function PageSkeleton(){useLocale();return <section className="page-skeleton" role="status" aria-label={t('copy.735')}><span className="sr-only">{t('copy.735')}</span><i className="skeleton page-skeleton-title"/><i className="skeleton page-skeleton-caption"/><i className="skeleton page-skeleton-hero"/><TrackSkeleton rows={4}/></section>;}
export function Heading({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:ReactNode}){useLocale();return <div className="view-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}<span className="accent-period">.</span></h1>{description&&<p className="intro">{description}</p>}</div>{action}</div>;}
export function Empty({icon=<Music2/>,title,children,action}:{icon?:ReactNode;title:string;children?:ReactNode;action?:ReactNode}){useLocale();return <div className="empty-state"><span className="empty-icon">{icon}</span><h3>{title}</h3><p>{children}</p>{action}</div>;}
export function Loading({label=t('copy.735')}:{label?:string}){useLocale();return <div className="loading-state" role="status"><span className="loader"/>{label}</div>;}
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){useLocale();const titleId=useId(),ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);return <dialog ref={ref} aria-labelledby={titleId} className={`modal ${wide?'wide':''}`} onCancel={onClose} onClick={event=>{if(event.target===event.currentTarget)onClose();}}><div className="modal-content"><header><h2 id={titleId}>{title}</h2><IconButton title={t('copy.736')} onClick={onClose}><X/></IconButton></header>{children}</div></dialog>;}
export function Toggle({checked,onChange,label,description,disabled=false}:{checked:boolean;onChange:(checked:boolean)=>void;label:string;description?:string;disabled?:boolean}){useLocale();return <label className="settings-row"><span><b>{label}</b>{description&&<small>{description}</small>}</span><span className="switch"><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)} disabled={disabled}/><span/></span></label>;}
export function TrackList({tracks,empty=t('copy.737'),onPlaylist,compact=false}:{tracks:Track[];empty?:string;onPlaylist?:(track:Track)=>void;compact?:boolean}){useLocale();const store=useStore(),player=usePlayer();const saved=player.savedIds;return tracks.length?<div className={`track-list ${compact?'compact':''}`}>{tracks.map((track,index)=><div className={`track-row ${player.track?.id===track.id?'current':''}`} key={track.id}><span className="track-number">{String(index+1).padStart(2,'0')}</span><div className="track-cover-wrap"><Art track={track} className="track-cover" onClick={()=>void player.playTrack(track,tracks)}/><Play className="art-play" size={14}/></div><button className="track-main" onClick={()=>void player.playTrack(track,tracks)}><b>{track.title}</b><small>{track.artist||t('copy.738')}</small></button><span className="track-source"><SourceMark source={track.source} label/></span>{saved.has(track.id)&&<span className="downloaded-mark" title={t('copy.739')}><Download size={13}/></span>}<span className="track-duration">{track.duration?time(track.duration):'—'}</span><IconButton title={store.library.likedIds.includes(track.id)?t('copy.637'):t('copy.638')} className={`icon-btn track-like ${store.library.likedIds.includes(track.id)?'liked':''}`} aria-pressed={store.library.likedIds.includes(track.id)} onClick={()=>void store.run(()=>store.like(track))}><AnimatedIcon name={store.library.likedIds.includes(track.id)?'heartFull':'heart'} size={17}/></IconButton>{!compact&&<IconButton title={t('copy.740')} onClick={()=>onPlaylist?onPlaylist(track):player.setAddTrack(track)}><Plus size={17}/></IconButton>}</div>)}</div>:<Empty title={empty}>{t('copy.741')}</Empty>;}
export function AddPlaylistModal({track,onClose}:{track:Track;onClose:()=>void}){useLocale();const store=useStore();return <Modal title={t('copy.740')} onClose={onClose}><p className="intro">{track.title} · {track.artist}</p><div className="playlist-picker">{store.library.playlists.map(playlist=><button className="list-button" key={playlist.id} onClick={()=>void store.run(async()=>{await patch(`/playlists/${playlist.id}`,{trackIds:[...new Set([...playlist.trackIds,track.id])]});await store.refreshLibrary();onClose();},t('copy.742'))}><Music2/><span>{playlist.name}<small>{trackCount(playlist.trackIds.length)}</small></span><ArrowRight size={16}/></button>)}</div><form onSubmit={event=>{event.preventDefault();const name=new FormData(event.currentTarget).get('name');void store.run(async()=>{await post('/playlists',{name,trackIds:[track.id]});await store.refreshLibrary();onClose();},t('copy.536'));}}><label className="field">{t('copy.743')}<input name="name" placeholder={t('copy.744')} maxLength={120} required/></label><button className="primary-button" type="submit"><Plus size={16}/>{t('copy.745')}</button></form></Modal>;}
export function DownloadButton({track}:{track:Track}){useLocale();const store=useStore(),player=usePlayer();return <button className="subtle-button" disabled={!track.playback.offline||player.manualIds.has(track.id)} onClick={()=>{if(!store.requireAuth())return;void store.run(async()=>{if(await cached(store.user!.id,track.id)){await pinDownload(store.user!.id,track.id);return;}await saveTrack(store.user!.id,track,store.settings.cacheLimitMB,true);},t('copy.746'));}}>{player.manualIds.has(track.id)?<Check size={16}/>:<Download size={16}/>} {player.manualIds.has(track.id)?t('copy.747'):track.playback.offline?(player.savedIds.has(track.id)?t('copy.748'):t('copy.749')):t('copy.750')}</button>;}

