import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {open,evaluate,run,useSession,snapshot,screenshot,click,ref} from './browser.mjs';
process.env.AGENT_BROWSER_ARGS='--mute-audio,--autoplay-policy=no-user-gesture-required';useSession('gluk-ambient-lyrics-'+Date.now());
const origin='http://127.0.0.1:5186',proof={passed:false,steps:[],screenshots:[]};
const control=async body=>(await fetch(origin+'/api/qa/ambient',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})).json();
const wait=expression=>{const end=Date.now()+16000;while(Date.now()<end){if(evaluate(expression))return snapshot();Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,120);}throw Error('Wait: '+expression);};
const helper=`window.__gw=function(key){const host=document.getElementById('root'),root=host[Object.keys(host).find(name=>name.startsWith('__reactContainer$'))]?.stateNode?.current,stack=[root];while(stack.length){const fiber=stack.pop();if(!fiber)continue;const value=fiber.memoizedProps?.value;if(value&&typeof value[key]==='function')return value;if(fiber.sibling)stack.push(fiber.sibling);if(fiber.child)stack.push(fiber.child);}throw Error('Missing context '+key);};`;
const shot=name=>{const file='apps/web/qa/ambient-'+name+'.png';screenshot(file);proof.screenshots.push(file);};
const draft=()=>evaluate(`document.querySelector('.lyrics-editor textarea').value`);
const edit=()=>{click('Lyrics');click('Add LRC / text');click('Genius');};
try{
 const initial=(await control({scenario:'normal',reset:true})).mutations.length;open(origin+'/app/#library');wait(`!!document.querySelector('.track-main')`);evaluate(helper);run('set','viewport','1440','1000');snapshot();click('A quiet place Wave verification');click('Expand player');wait(`document.querySelector('.np-backdrop').dataset.ambientMoving==='true'`);
 const moving=evaluate(`getComputedStyle(document.querySelector('.np-backdrop-drift')).transform`);await new Promise(r=>setTimeout(r,600));assert.notEqual(evaluate(`getComputedStyle(document.querySelector('.np-backdrop-drift')).transform`),moving);
 click('Pause');wait(`document.querySelector('.np-backdrop').dataset.ambientMoving==='false'`);const stopped=evaluate(`getComputedStyle(document.querySelector('.np-backdrop-drift')).transform`);await new Promise(r=>setTimeout(r,450));assert.equal(evaluate(`getComputedStyle(document.querySelector('.np-backdrop-drift')).transform`),stopped);click('Play');wait(`document.querySelector('.np-backdrop').dataset.ambientMoving==='true'`);
 evaluate(`__gw('saveSettings').saveSettings({reducedMotion:true})`);wait(`document.querySelector('.np-backdrop').dataset.ambientMoving==='false'`);evaluate(`__gw('saveSettings').saveSettings({reducedMotion:false})`);wait(`document.querySelector('.np-backdrop').dataset.ambientMoving==='true'`);
 // Hidden visibility follows the same observer used by production; no audio mutation.
 evaluate(`Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))`);wait(`document.querySelector('.np-backdrop').dataset.ambientMoving==='false'`);evaluate(`Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))`);wait(`document.querySelector('.np-backdrop').dataset.ambientMoving==='true'`);
 proof.steps.push('Actual audio state drives 32-second transform, freezes on pause, reduced motion and document hidden; resumes without polling');
 for(const theme of ['light','dark','amoled']){evaluate(`__gw('saveSettings').saveSettings({theme:${JSON.stringify(theme)}})`);wait(`document.documentElement.dataset.theme===${JSON.stringify(theme)}`);for(const [label,w,h] of [['desktop',1440,1000],['mobile',390,844]]){run('set','viewport',String(w),String(h));snapshot();assert(!evaluate(`document.documentElement.scrollWidth>innerWidth`));shot(theme+'-'+label);}}
 evaluate(`__gw('saveSettings').saveSettings({appearance:{blur:false}})`);wait(`getComputedStyle(document.querySelector('.np-backdrop')).display==='none'`);evaluate(`__gw('saveSettings').saveSettings({appearance:{blur:true},theme:'light'})`);wait(`document.querySelector('.np-backdrop').dataset.ambientMoving==='true'`);
 run('set','viewport','1440','1000');snapshot();edit();run('fill',ref('textbox','Genius lyrics link'),'https://genius.com/Glukwave-verification-lyrics');click('Load preview');wait(`!!document.querySelector('.lyrics-preview-credit')`);assert.equal(draft(),'The evening moves slowly\nAnd the light follows home');assert.equal((await control({})).mutations.slice(initial).filter(x=>!x.route.endsWith('/preview')).length,0);shot('genius-light-desktop');
 run('set','viewport','390','844');snapshot();shot('genius-light-mobile');
 await control({scenario:'unavailable'});click('Load preview');wait(`!!document.querySelector('.lyrics-source-error')`);assert.equal(draft(),'The evening moves slowly\nAnd the light follows home');shot('genius-error-mobile');
 run('fill',ref('textbox','Genius lyrics link'),'https://genius.com.evil.test/song-lyrics');click('Load preview');wait(`document.querySelector('.lyrics-source-error').innerText.includes('HTTPS')`);assert.equal(draft(),'The evening moves slowly\nAnd the light follows home');
 run('fill',ref('textbox','Genius lyrics link'),'https://genius.com/Glukwave-verification-lyrics');await control({scenario:'normal'});click('Save lyrics');wait(`!document.querySelector('.lyrics-editor')`);assert((await control({})).mutations.at(-1)?.route.endsWith('/lyrics/genius'));proof.steps.push('Genius preview is explicitly loaded and never persisted until Save; invalid/unavailable source preserves draft, unchanged Save retains Genius attribution');
 edit();run('fill',ref('textbox','Genius lyrics link'),'https://genius.com/Glukwave-verification-lyrics');click('Load preview');wait(`!!document.querySelector('.lyrics-preview-credit')`);run('fill','textarea[name=text]','[00:02.00]My original timing');click('Save lyrics');wait(`!document.querySelector('.lyrics-editor')`);assert((await control({})).mutations.at(-1)?.body.text==='[00:02.00]My original timing');proof.steps.push('Editing imported plain text saves personal user lyrics with explicit original timestamps');
 edit();for(const lang of ['en','ru','kk','uk','de','es']){evaluate(`__gw('saveSettings').saveSettings({language:${JSON.stringify(lang)},fontScale:1.25})`);wait(`document.documentElement.lang===${JSON.stringify(lang)}`);assert(!evaluate(`document.querySelector('dialog').innerText.includes('lyrics.genius')`));assert(!evaluate(`document.documentElement.scrollWidth>innerWidth`));}shot('genius-es-125-mobile');evaluate(`__gw('saveSettings').saveSettings({language:'en',fontScale:1})`);wait(`document.documentElement.lang==='en'`);
 const retained=draft();await control({scenario:'delayed'});run('fill',ref('textbox','Genius lyrics link'),'https://genius.com/Glukwave-verification-lyrics');click('Load preview');click('LRCLIB');await new Promise(r=>setTimeout(r,1500));assert.equal(draft(),retained);proof.steps.push('Switching sources aborts and ignores a delayed preview; six languages remain readable at 125 percent on phone');
 run('click',ref('button','Close'));snapshot();click('Collapse player');assert.equal(evaluate(`document.querySelector('.np-backdrop').dataset.ambientMoving`),'false');proof.steps.push('Closing player freezes cover light');proof.browserErrors=run('errors');proof.passed=true;
}catch(error){proof.error=String(error);try{proof.snapshot=snapshot().snapshot;}catch{}throw error;}finally{await fs.writeFile('apps/web/qa/ambient-browser-proof.json',JSON.stringify(proof,null,2));run('close');}

