import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {open,evaluate,run,useSession,wait,snapshot,screenshot,click} from './browser.mjs';

useSession(process.env.GLUKWAVE_QA_SESSION||('gluk-v8-sync-'+Date.now()));
const origin=process.env.GLUKWAVE_QA_ORIGIN||'http://127.0.0.1:5175',proof={passed:false,samples:[]},suffix=String(Date.now()).slice(-9),roomName='V7 listening verification';
const helpers=`window.__gwContext=function(key){const host=document.getElementById('root'),containerKey=Object.keys(host).find(name=>name.startsWith('__reactContainer$')),root=host[containerKey]?.stateNode?.current,stack=[root];while(stack.length){const fiber=stack.pop();if(!fiber)continue;const value=fiber.memoizedProps?.value;if(value&&typeof value[key]==='function')return value;if(fiber.sibling)stack.push(fiber.sibling);if(fiber.child)stack.push(fiber.child);}throw new Error('Application context missing: '+key);};window.__qaApi=async function(route,body,method=body?'POST':'GET'){const response=await fetch('/api'+route,{method,headers:{'Content-Type':'application/json','Accept-Language':'en'},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(JSON.stringify(data));return data;};`;
const player=()=>evaluate(`(()=>{const p=__gwContext('playTrack');return {track:p.track?.id,position:p.state.position,playing:p.state.playing,queue:p.queue.map(t=>t.id),socket:p.socket?.connected,socketId:p.socket?.id,deviceId:p.socket?.auth.deviceId,room:p.room?{id:p.room.id,state:p.room.state,members:p.room.members}:null,eq:p.equalizerAvailable,devices:p.devices.map(d=>({id:d.id,online:d.online,position:d.state.position}))};})()`);
async function poll(expression){const deadline=Date.now()+15000;while(Date.now()<deadline){if(evaluate(expression))return snapshot();await new Promise(resolve=>setTimeout(resolve,300));}throw new Error('Timed out awaiting '+expression);}
const sample=name=>{const value=player();proof.samples.push({name,...value});console.log(JSON.stringify({step:name,track:value.track,playing:value.playing,position:value.position}));return value;};
try{
 open(origin+'/app/#home');wait(`!!document.querySelector('.app-shell')`);evaluate(helpers);
 evaluate(`(async()=>{await __qaApi('/auth/register',{email:'v7_${suffix}@example.test',username:'v7_${suffix}',displayName:'V7 QA',password:'local-v7-sync-passphrase'});await __gwContext('refresh').refresh();await __gwContext('saveSettings').saveSettings({language:'en',autoCache:false});})()`);
 wait(`!!__gwContext('playTrack').socket?.connected`);snapshot();
 const tracks=evaluate(`(async()=>{const out=[];for(const [index,frequency]of[220,440].entries()){const rate=16000,size=rate*600*2,buffer=new ArrayBuffer(44+size),view=new DataView(buffer),chars=(at,text)=>[...text].forEach((letter,index)=>view.setUint8(at+index,letter.charCodeAt(0)));chars(0,'RIFF');view.setUint32(4,36+size,true);chars(8,'WAVEfmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);chars(36,'data');view.setUint32(40,size,true);for(let i=0;i<rate*600;i++)view.setInt16(44+i*2,Math.round(Math.sin(i*2*Math.PI*frequency/rate)*800),true);const data=new FormData();data.set('file',new Blob([buffer],{type:'audio/wav'}),'qa-'+index+'.wav');data.set('title','QA playback '+(index+1));data.set('artist','GlukWave verification');const response=await fetch('/api/tracks/upload',{method:'POST',body:data});if(!response.ok)throw new Error(await response.text());out.push((await response.json()).track);}window.__qaTracks=out;await __gwContext('refreshLibrary').refreshLibrary();return out;})()`);
 evaluate(`__gwContext('playTrack').playTrack(__qaTracks[0],__qaTracks)`);console.log(JSON.stringify({beforeGesture:player()}));if(!evaluate(`__gwContext('playTrack').state.playing`))click('Play');console.log(JSON.stringify({afterGesture:player()}));wait(`__gwContext('playTrack').state.playing`);const first=sample('first tab plays real PCM');assert(first.eq);
 run('tab','new',origin+'/app/#home');wait(`!!document.querySelector('.app-shell')`);evaluate(helpers);click('Home');wait(`!!__gwContext('playTrack').socket?.connected`);const second=sample('same-profile second tab stays connected');assert.notEqual(second.deviceId,first.deviceId);
 run('tab','0');snapshot();assert(sample('first tab still connected').socket);
 evaluate(`(async()=>{const room=(await __qaApi('/rooms',{name:'${roomName}'})).room;window.__qaRoom=room;await __gwContext('playTrack').joinRoom(room);})()`);wait(`!!__gwContext('playTrack').room`);const empty=sample('joining empty room clears personal track');assert.equal(empty.track,undefined);assert.equal(empty.playing,false);
 evaluate(`__gwContext('playTrack').playTrack(__qaTracks[0],__qaTracks)`);wait(`__gwContext('playTrack').state.playing`);const active=sample('room starts actual track');
 evaluate(`window.__qaOwnerSocket=__gwContext('playTrack').socket.id;window.__qaOwnerTrack=__gwContext('playTrack').track.id;`);
 run('tab','1');snapshot();evaluate(`(async()=>{const room=(await __qaApi('/rooms')).rooms.find(room=>room.name==='${roomName}');await __gwContext('playTrack').joinRoom(room);})()`);wait(`__gwContext('playTrack').state.playing`);sample('second tab synchronizes room');
 const roomId=evaluate(`__gwContext('playTrack').room.id`);
 evaluate(`(async()=>{const p=__gwContext('playTrack');p.socket.io.engine.close();return true;})()`);wait(`__gwContext('playTrack').socket?.connected&&__gwContext('playTrack').state.playing`);sample('reconnect with unchanged room revision');
 // Delay the first upstream metadata request; a newer track must win.
 evaluate(`window.__qaOriginalFetch=window.fetch;window.__qaDelayId=${JSON.stringify(tracks[1].id)};window.fetch=async function(input,init){if(typeof input==='string'&&input==='/api/tracks/'+__qaDelayId)await new Promise(resolve=>setTimeout(resolve,1000));return __qaOriginalFetch.apply(this,arguments);};`);
 run('tab','0');snapshot();evaluate(`(async()=>{const p=__gwContext('playTrack');await p.command({command:'track',trackId:__qaTracks[1].id,queue:__qaTracks.map(t=>t.id)});await p.command({command:'track',trackId:__qaTracks[0].id,queue:__qaTracks.map(t=>t.id)});})()`);
 run('tab','1');snapshot();wait(`__gwContext('playTrack').track?.id===${JSON.stringify(tracks[0].id)}&&__gwContext('playTrack').state.playing`);
 evaluate(`new Promise(resolve=>setTimeout(resolve,1300))`);assert.equal(sample('delayed older metadata cannot replace newer track').track,tracks[0].id);evaluate(`window.fetch=__qaOriginalFetch;`);
 // Transfer uses local output commands; shared room revision must not change.
 run('tab','0');snapshot();const beforeTransfer=sample('source before output transfer');
 evaluate(`__qaApi('/devices/command',{deviceId:${JSON.stringify(second.deviceId)},fromDeviceId:${JSON.stringify(first.deviceId)},command:'transfer'})`);wait(`!__gwContext('playTrack').state.playing`);
 const transferred=sample('source output paused after transfer');assert.equal(transferred.room.state.revision,beforeTransfer.room.state.revision);
 run('tab','1');snapshot();wait(`__gwContext('playTrack').state.playing`);const target=sample('target output active after transfer');assert.equal(target.track,tracks[0].id);
 // Two independent slider lanes preserve seek and volume.
 evaluate(`Promise.all([__gwContext('playTrack').command({command:'seek',position:7}),__gwContext('playTrack').command({command:'volume',volume:.33})])`);
 wait(`Math.abs(__gwContext('playTrack').state.volume-.33)<.01&&__gwContext('playTrack').state.position>=7`);sample('seek and volume both committed');
 run('tab','0');snapshot();assert.equal(sample('room seek does not reactivate transferred source').playing,false);
 evaluate(`window.__qaSettingsStart=performance.now();__gwContext('saveSettings').saveSettings({equalizer:{enabled:true,preamp:-3,bands:[3,3,2,1,0,0,-1,-1,-2,-2]},playbackRate:1.25})`);
 await poll(`__gwContext('saveSettings').settingsSync==='saved'`);run('tab','1');snapshot();await poll(`__gwContext('saveSettings').settings.equalizer.enabled&&__gwContext('saveSettings').settings.equalizer.preamp===-3`);
 run('tab','0');snapshot();proof.settingsRequests=evaluate(`performance.getEntriesByType('resource').filter(entry=>entry.name.endsWith('/api/settings')&&entry.startTime>=__qaSettingsStart).length`);assert(proof.settingsRequests<=10,'Repeated settings requests between tabs: '+proof.settingsRequests);run('tab','1');snapshot();
 proof.settings=evaluate(`__gwContext('saveSettings').settings`);assert.equal(proof.settings.playbackRate,1.25);
 proof.passed=true;proof.origin=origin;proof.roomId=roomId;screenshot('work/qa/web-v7-sync-final.png');
}catch(error){proof.error=String(error);proof.snapshot=snapshot().snapshot;throw error;}
finally{await fs.writeFile('work/qa/web-v7-sync.json',JSON.stringify(proof,null,2));console.log(JSON.stringify({passed:proof.passed,samples:proof.samples.map(({name,track,playing,position,socket})=>({name,track,playing,position,socket})),error:proof.error}));}
