import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {open,evaluate,run,useSession,wait,snapshot,screenshot} from './browser.mjs';
process.env.AGENT_BROWSER_ARGS='--mute-audio,--autoplay-policy=no-user-gesture-required';
useSession('gluk-media-'+Date.now());
const fixture=JSON.parse(await fs.readFile('work/qa/ecosystem-web-functional.json','utf8')),suffix=fixture.samples[0].devices.find(device=>device.kind==='android').id.split('-').at(-1),proof={passed:false};
const helper=`window.__gw=function(key){const host=document.getElementById('root'),root=host[Object.keys(host).find(name=>name.startsWith('__reactContainer$'))]?.stateNode?.current,stack=[root];while(stack.length){const fiber=stack.pop();if(!fiber)continue;const value=fiber.memoizedProps?.value;if(value&&typeof value[key]==='function')return value;if(fiber.sibling)stack.push(fiber.sibling);if(fiber.child)stack.push(fiber.child);}throw Error('Missing context '+key);};window.__qaApi=async(route,body,method=body?'POST':'GET')=>(await import('/src/api.ts')).api(route,{method,...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});`;
try{
 open('http://127.0.0.1:5177/app/#home');wait(`!!document.querySelector('.app-shell')`);evaluate(helper);
 evaluate(`(async()=>{await __qaApi('/auth/login',{email:'ecosystem_${suffix}@example.test',password:'Ecosystem-local-test-2026'});await __gw('refresh').refresh();await __gw('saveSettings').saveSettings({language:'en',theme:'light',reducedMotion:false,autoCache:false});})()`);wait(`!!__gw('playTrack').socket?.connected&&__gw('refresh').library.tracks.some(track=>track.source==='local')`);run('set','viewport','1440','1000');
 proof.cache=evaluate(`(async()=>{const cache=await import('/src/cache.ts'),track=__gw('refresh').library.tracks.find(track=>track.source==='local'),form=new FormData();form.set('file',await(await fetch('/brand/logo.png')).blob(),'verification-cover.png');form.set('kind','avatar');const result=await __qaApi('/profile/media',form);window.__qaCachedTrack={...track,artwork:result.user.avatarUrl};await cache.saveTrack(__gw('refresh').user.id,__qaCachedTrack,100,true);const saved=await cache.cached(__gw('refresh').user.id,track.id);return {audioBytes:saved.blob.size,artworkBytes:saved.artworkBlob?.size||0,total:saved.bytes,persistentArtwork:saved.track.artwork};})()`);assert(proof.cache.audioBytes>0&&proof.cache.artworkBytes>0);assert.equal(proof.cache.total,proof.cache.audioBytes+proof.cache.artworkBytes);assert(!proof.cache.persistentArtwork.startsWith('blob:'));
 evaluate(`window.__qaRevoked=[];const originalRevoke=URL.revokeObjectURL;URL.revokeObjectURL=function(url){__qaRevoked.push(url);return originalRevoke.call(URL,url);};__gw('playTrack').playTrack(__qaCachedTrack);true;`);wait(`__gw('playTrack').state.playing&&__gw('playTrack').track.artwork.startsWith('blob:')`);const coverUrl=evaluate(`__gw('playTrack').track.artwork`);assert(!evaluate(`__gw('refresh').library.tracks.some(track=>track.artwork?.startsWith('blob:'))`));evaluate(`__qaApi('/profile/media/avatar',null,'DELETE')`);wait(`document.querySelector('.player-art img')?.naturalWidth>0`);proof.cachedCoverAfterAssetRemoval=true;screenshot('work/qa/media-web-cached-cover-desktop.png');
 evaluate(`window.__qaMiniCount=0;const originalPost=BroadcastChannel.prototype.postMessage;BroadcastChannel.prototype.postMessage=function(data){if(data?.type==='state')__qaMiniCount++;return originalPost.call(this,data);};true;`);const surface=evaluate(`__gw('playTrack').socket.auth.surfaceId`);run('tab','new','http://127.0.0.1:5177/mini.html?device='+encodeURIComponent(surface));run('set','viewport','380','176');wait(`document.querySelector('header b')?.textContent==='On the same wavelength'`);snapshot();assert.equal(evaluate(`document.querySelectorAll('section button').length`),3);assert(evaluate(`document.querySelector('input[type=range]').classList.contains('wave-range')`));assert.equal(evaluate(`document.documentElement.scrollWidth>innerWidth`),false);screenshot('work/qa/media-web-mini-player.png');run('tab','close');run('tab','0');snapshot();run('wait','300');const count=evaluate(`__qaMiniCount`);run('wait','700');proof.miniStateMessagesAfterClose=evaluate(`__qaMiniCount`)-count;assert.equal(proof.miniStateMessagesAfterClose,0);
 evaluate(`__gw('playTrack').command({command:'pause'})`);wait(`!__gw('playTrack').state.playing`);evaluate(`__gw('playTrack').leaveRoom()`);evaluate(`__gw('refresh').setUser(null);true;`);wait(`!__gw('playTrack').track`);assert(evaluate(`__qaRevoked.includes(${JSON.stringify(coverUrl)})`));proof.cachedArtworkUrlRevoked=true;
 evaluate(`(async()=>{await __qaApi('/auth/login',{email:'ecosystem@example.test',password:'Ecosystem-local-test-2026'});await __gw('refresh').refresh();await __gw('saveSettings').saveSettings({language:'en',theme:'light'});__gw('refresh').navigate('admin');})()`);wait(`!!document.querySelector('.extractor-section')`);wait(`!!document.querySelector('.resource-metrics')&&!!document.querySelector('.extractor-adapters')`);run('set','viewport','1440','1000');run('scrollintoview','.extractor-section');snapshot();proof.admin=evaluate(`({metrics:document.querySelectorAll('.resource-metrics>div').length,adapters:document.querySelectorAll('.extractor-adapters>div').length,tracks:document.querySelectorAll('.permission-form select option').length-1,permissionCaption:document.querySelector('.permission-form .settings-note').textContent})`);assert(proof.admin.metrics>=8&&proof.admin.adapters>=3);screenshot('work/qa/media-web-admin-desktop.png');run('set','viewport','375','812');snapshot();screenshot('work/qa/media-web-admin-mobile.png');assert.equal(evaluate(`document.documentElement.scrollWidth>innerWidth`),false);
 if(proof.admin.tracks){const id=evaluate(`document.querySelector('.permission-form select option:nth-child(2)').value`);run('select','.permission-form select',id);wait(`!!document.querySelector('.permission-form fieldset')`);assert.equal(evaluate(`document.querySelector('.permission-form').checkValidity()`),false);proof.admin.permissionRequiredEvidence=true;}
 proof.passed=true;console.log(JSON.stringify(proof));
}catch(error){proof.error=String(error);try{proof.snapshot=snapshot().snapshot;}catch{}throw error;}
finally{try{evaluate(`__gw('playTrack').command({command:'pause'});true;`);}catch{}await fs.writeFile('work/qa/media-web-functional.json',JSON.stringify(proof,null,2));run('close');}
