import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {open,evaluate,run,useSession,wait,snapshot,screenshot} from './browser.mjs';
process.env.AGENT_BROWSER_ARGS='--mute-audio,--autoplay-policy=no-user-gesture-required';
useSession('gluk-motion-'+Date.now());
const fixture=JSON.parse(await fs.readFile('work/qa/ecosystem-web-functional.json','utf8')),suffix=fixture.samples[0].devices.find(device=>device.kind==='android').id.split('-').at(-1),proof={passed:false,themes:[],languages:[],raf:{}};
const helper=`window.__gw=function(key){const host=document.getElementById('root'),root=host[Object.keys(host).find(name=>name.startsWith('__reactContainer$'))]?.stateNode?.current,stack=[root];while(stack.length){const fiber=stack.pop();if(!fiber)continue;const value=fiber.memoizedProps?.value;if(value&&typeof value[key]==='function')return value;if(fiber.sibling)stack.push(fiber.sibling);if(fiber.child)stack.push(fiber.child);}throw Error('Missing context '+key);};window.__qaApi=async(route,body)=>(await import('/src/api.ts')).api(route,{method:'POST',body:JSON.stringify(body)});`;
try{
 open('http://127.0.0.1:5177/app/#settings?section=playback');wait(`!!document.querySelector('.app-shell')`);evaluate(helper);
 evaluate(`(async()=>{await __qaApi('/auth/login',{email:'ecosystem_${suffix}@example.test',password:'Ecosystem-local-test-2026'});await __gw('refresh').refresh();await __gw('saveSettings').saveSettings({language:'en',autoCache:false,equalizer:{enabled:true,bands:Array(10).fill(0),preamp:0}});})()`);wait(`!!__gw('playTrack').socket?.connected&&!!document.querySelector('.equalizer-bands')`);
 run('set','viewport','1440','1000');
 for(const theme of ['light','dark','amoled']){
  evaluate(`__gw('saveSettings').saveSettings({theme:${JSON.stringify(theme)}})`);wait(`document.documentElement.dataset.theme===${JSON.stringify(theme)}`);snapshot();
  const view=evaluate(`(()=>{const ranges=[...document.querySelectorAll('input[type=range]')];return {allCustom:ranges.every(item=>item.classList.contains('wave-range')),eq:[...document.querySelectorAll('.equalizer-band input')].map(item=>({appearance:getComputedStyle(item).appearance,orientation:getComputedStyle(item).writingMode,fill:item.style.getPropertyValue('--range-progress')})),overflow:document.documentElement.scrollWidth>innerWidth};})()`);
  assert(view.allCustom);assert(view.eq.every(item=>item.appearance==='none'&&item.orientation==='vertical-lr'&&item.fill==='50%'));assert(!view.overflow);proof.themes.push({theme,...view});
  screenshot(`work/qa/motion-web-eq-${theme}-desktop.png`);
 }
 run('set','viewport','375','812');snapshot();screenshot('work/qa/motion-web-eq-amoled-mobile.png');assert.equal(evaluate(`document.documentElement.scrollWidth>innerWidth`),false);
 evaluate(`document.querySelector('.equalizer-band input').focus()`);run('press','ArrowUp');snapshot();proof.eqKeyboard=evaluate(`Number(document.querySelector('.equalizer-band input').value)`);assert(proof.eqKeyboard>0);
 for(const language of ['en','ru','kk','uk','de','es']){evaluate(`__gw('saveSettings').saveSettings({language:${JSON.stringify(language)}})`);wait(`document.documentElement.lang===${JSON.stringify(language)}`);snapshot();assert.equal(evaluate(`document.documentElement.scrollWidth>innerWidth`),false);proof.languages.push(language);}
 evaluate(`__gw('saveSettings').saveSettings({language:'en',theme:'light',reducedMotion:false})`);wait(`document.documentElement.lang==='en'&&document.documentElement.dataset.motion==='full'`);run('set','viewport','1440','1000');
 evaluate(`(()=>{window.__qaRaf={wave:0};const original=requestAnimationFrame;window.requestAnimationFrame=function(callback){if(new Error().stack.includes('/wave.tsx'))__qaRaf.wave++;return original.call(window,callback);};__gw('refresh').navigate('home');})()`);snapshot();run('wait','700');let before=evaluate(`__qaRaf.wave`);run('wait','700');proof.raf.visible=evaluate(`__qaRaf.wave`)-before;assert(proof.raf.visible>0);
 const track=evaluate(`__gw('refresh').library.tracks.find(track=>track.source==='local')`);assert(track);evaluate(`__gw('playTrack').playTrack(${JSON.stringify(track)})`);wait(`__gw('playTrack').state.playing&&__gw('playTrack').playback?.kind==='audio'`);
 evaluate(`__gw('playTrack').setFull(true)`);snapshot();run('wait','400');before=evaluate(`__qaRaf.wave`);run('wait','700');proof.raf.coveredByFullPlayer=evaluate(`__qaRaf.wave`)-before;assert.equal(proof.raf.coveredByFullPlayer,0);
 evaluate(`__gw('playTrack').setFull(false)`);snapshot();run('wait','400');before=evaluate(`__qaRaf.wave`);run('wait','600');proof.raf.returned=evaluate(`__qaRaf.wave`)-before;assert(proof.raf.returned>0);
 evaluate(`Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));true;`);run('wait','150');before=evaluate(`__qaRaf.wave`);run('wait','600');proof.raf.simulatedHidden=evaluate(`__qaRaf.wave`)-before;assert.equal(proof.raf.simulatedHidden,0);assert(evaluate(`__gw('playTrack').state.playing`));assert.equal(evaluate(`document.documentElement.dataset.visuals`),'paused');
 evaluate(`delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));__gw('saveSettings').saveSettings({reducedMotion:true});true;`);wait(`document.documentElement.dataset.motion==='reduce'`);run('wait','150');before=evaluate(`__qaRaf.wave`);run('wait','600');proof.raf.reduced=evaluate(`__qaRaf.wave`)-before;assert.equal(proof.raf.reduced,0);
 evaluate(`__gw('playTrack').setDevicesOpen(true)`);run('set','viewport','375','812');snapshot();proof.touchTargets=evaluate(`[...document.querySelectorAll('.device-panel-header>.icon-btn,.device-panel .device-remove,.device-panel .device-local-controls .transport>button')].map(button=>({label:button.getAttribute('aria-label'),width:button.getBoundingClientRect().width,height:button.getBoundingClientRect().height}))`);assert(proof.touchTargets.every(button=>button.width>=44&&button.height>=44));screenshot('work/qa/motion-web-device-panel-mobile.png');assert.equal(evaluate(`document.documentElement.scrollWidth>innerWidth`),false);
 proof.passed=true;console.log(JSON.stringify(proof));
}catch(error){proof.error=String(error);try{proof.snapshot=snapshot().snapshot;}catch{}throw error;}
finally{try{evaluate(`delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));__gw('playTrack').command({command:'pause'});true;`);}catch{}await fs.writeFile('work/qa/motion-web-functional.json',JSON.stringify(proof,null,2));run('close');}
