import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {click,evaluate,fill,open,ref,run,screenshot,select,snapshot,useSession,wait} from './browser.mjs';
useSession('gluk-oct08');
const file='work/qa/web-oct08-regression.json',samples=[],captures=[],auth=[];
const copies=Object.fromEntries(await Promise.all(['en','ru','kk','uk','de','es'].map(async language=>[language,JSON.parse(await fs.readFile(`apps/web/src/locales/${language}.json`,'utf8'))])));
const index=await fs.readFile('apps/web/dist/index.html','utf8'),build=index.match(/src="(\/assets\/main-[^"]+\.js)"/)[1];
const capture=name=>{const path=`outputs/GlukWave-${name}-en.png`;screenshot(path);const state=evaluate(`({url:location.href,language:document.documentElement.lang,viewport:[innerWidth,innerHeight],overflow:document.documentElement.scrollWidth>innerWidth,build:new URL(document.querySelector('script[type="module"]').src).pathname})`);assert.equal(state.build,build);assert(!state.overflow);captures.push({file:path,...state});};
const probe=step=>{const data=evaluate(`new Promise(resolve=>__octWidget.getPosition(position=>__octWidget.isPaused(paused=>resolve({language:document.documentElement.lang,position:position/1000,paused,sameFrame:document.querySelector('.persistent-provider iframe')===__octFrame,sameWidget:SC.Widget(__octFrame)===__octWidget,frames:document.querySelectorAll('.persistent-provider iframe').length,title:document.querySelector('.player-track-info b')?.textContent,artist:document.querySelector('.player-track-info small')?.textContent,events:[...__octEvents]}))))`);samples.push({step,...data});assert.equal(data.paused,false);assert.equal(data.sameFrame,true);assert.equal(data.sameWidget,true);assert.equal(data.frames,1);assert.equal(data.title,'Flickermood');assert.equal(data.artist,'Forss');console.log(JSON.stringify({step,position:data.position,paused:data.paused,language:data.language}));return data;};
try{
 open('http://127.0.0.1:4100/');wait(`!!document.querySelector('.public-site')`);select('en');click(copies.en['landing.open'],'link');wait(`!!document.querySelector('main h1')`);run('set','viewport','1280','900');
 evaluate(`window.__octAuth=[];window.__octFetch=window.fetch;window.fetch=async function(input,init){const url=typeof input==='string'?input:input.url;if(url==='/api/auth/login'){const body=JSON.parse(init?.body||'{}'),response=await __octFetch.apply(this,arguments);__octAuth.push({path:url,status:response.status,language:new Headers(init?.headers).get('accept-language'),captchaEmpty:body.captchaToken==='',code:(await response.clone().json()).error?.code||null});return response;}return __octFetch.apply(this,arguments);};`);
 click(copies.en['copy.204']);fill('textbox',copies.en['copy.249'],'qa@example.test');fill('textbox',copies.en['copy.250'],'Incorrect-test-password');click(copies.en['copy.254']);wait(`!!document.querySelector('.error-banner')`);
 const error=evaluate(`document.querySelector('.error-banner').textContent`);assert(error.length>5);assert(!/[А-Яа-яЁё]/.test(error));assert(!/Mongo|R2|API|OAuth|Turnstile|SMTP|\.env|credentials|SERVER_ERROR|INVALID_CREDENTIALS|stack/i.test(error));auth.push({step:'actual invalid login, empty captcha',language:'en',message:error,request:evaluate(`__octAuth.at(-1)`)});assert.equal(auth[0].request.status,401);assert.equal(auth[0].request.code,'INVALID_CREDENTIALS');assert.equal(auth[0].request.captchaEmpty,true);screenshot('work/qa/web-oct08-auth-error-en.png');click(copies.en['copy.736']);
 click(copies.en['copy.023']);click(/^Language /);select('de');wait(`document.documentElement.lang==='de'`);click(copies.de['copy.204']);fill('textbox',copies.de['copy.249'],'qa@example.test');fill('textbox',copies.de['copy.250'],'Local-qa-passphrase-2026');click(copies.de['copy.254']);wait(`!!localStorage.getItem('gw-user')&&!document.querySelector('.auth-form')`);wait(`document.documentElement.lang==='en'`);
 auth.push({step:'existing account login',guestChoice:'de',resolvedAccountChoice:evaluate(`document.documentElement.lang`),request:evaluate(`__octAuth.at(-1)`)});assert.equal(auth[1].request.status,200);assert.equal(auth[1].request.captchaEmpty,true);assert.equal(auth[1].request.language,'de');evaluate(`window.fetch=__octFetch;`);
 click(copies.en['copy.203']);wait(`!!document.querySelector('.plans-section')`);const profileText=evaluate(`document.querySelector('.plans-section').innerText`);assert(!/администратор|API|SMTP|настроен|настроить|\.env|configured/i.test(profileText));auth.push({step:'consumer profile subscription copy',text:profileText});
 click(copies.en['copy.023']);click(/^Account /);click(copies.en['copy.042']);wait(`!localStorage.getItem('gw-user')`);
 const guestLanguage=evaluate(`document.documentElement.lang`);click(copies[guestLanguage]['copy.023']);click(new RegExp('^'+copies[guestLanguage]['language.title']+' '));select('en');
 open('http://127.0.0.1:4100/app/?track=soundcloud-soundcloud%3Atracks%3A293');wait(`!!document.querySelector('.shared-track')`);click(copies.en['copy.214']);wait(`document.querySelector('.persistent-provider')?.dataset.ready==='true'`);wait(`document.querySelector('.album-cover img')?.naturalWidth===500`);
 evaluate(`window.__octFrame=document.querySelector('.persistent-provider iframe');window.__octWidget=SC.Widget(__octFrame);window.__octEvents=[];__octWidget.bind(SC.Widget.Events.PLAY,()=>__octEvents.push('PLAY'));__octWidget.bind(SC.Widget.Events.PAUSE,()=>__octEvents.push('PAUSE'));window.__octPaused=true;`);
 const start=evaluate(`new Promise(resolve=>__octWidget.isPaused(resolve))`);if(start)click('Play');wait(`(__octWidget.isPaused(value=>window.__octPaused=value),!__octPaused)`);probe('guest shared-track start');run('set','viewport','1280','900');capture('player-desktop');run('set','viewport','390','844');capture('player-mobile');probe('fullscreen resize');
 click(copies.en['copy.646']);run('set','viewport','1280','900');click(copies.en['copy.023']);click(/^Language /);
 for(const language of ['ru','kk','uk','de','es','en']){select(language);wait(`document.documentElement.lang==='${language}'`);const data=probe('language '+language);assert.equal(data.language,language);}
 capture('settings-desktop');run('set','viewport','390','844');capture('settings-mobile');probe('mobile settings');
 run('set','viewport','1280','900');click(copies.en['copy.639']);click(copies.en['copy.652']);click(copies.en['copy.646']);click(copies.en['copy.639']);assert.equal(evaluate(`document.querySelector('.np-tabs .selected')?.textContent`),copies.en['copy.651']);probe('lyrics close and player reopen');click(copies.en['copy.646']);click('Home');capture('app-desktop');run('set','viewport','390','844');capture('app-mobile');probe('guest home mobile');
 assert(samples.at(-1).position>samples[0].position);assert(!samples.at(-1).events.includes('PAUSE'));
 open('http://127.0.0.1:4100/');wait(`!!document.querySelector('.public-site')`);wait(`!!document.querySelector('.platform-list a[download]')`);
 for(const [width,height,name] of [[1280,900,'landing-desktop'],[390,844,'landing-mobile']]){run('set','viewport',String(width),String(height));run('scroll','up','10000');snapshot();capture(name);run('scrollintoview',ref('link','Download for Android'));snapshot();capture(name+'-downloads');}
 const releases=evaluate(`[...document.querySelectorAll('.platform-list article')].map(node=>({text:node.innerText,download:node.querySelector('a[download]')?.getAttribute('href')||null}))`);assert.equal(releases.find(item=>item.text.includes('Android')).download,'/api/downloads/android');assert(releases.filter(item=>/Windows|iOS/.test(item.text)).every(item=>!item.download));
 await fs.writeFile(file,JSON.stringify({passed:true,build,auth,samples,captures,releases},null,2));console.log(JSON.stringify({passed:true,file,build,samples:samples.length,captures:captures.length,auth:auth.map(({step,request,resolvedAccountChoice})=>({step,request,resolvedAccountChoice}))}));
}catch(error){await fs.writeFile(file,JSON.stringify({passed:false,build,error:String(error),auth,samples,captures,snapshot:snapshot().snapshot},null,2));throw error;}
