"""Build committed offline catalogs; no runtime translation service is used."""
import json
from pathlib import Path

BASE = Path('apps/native/tool')
sources = json.loads((BASE/'catalog_source.json').read_text(encoding='utf-8'))
translations = json.loads((BASE/'catalog_translations.json').read_text(encoding='utf-8'))
inventory = Path('apps/web/qa/copy-inventory.json')
web_rows = Path('apps/web/src/locales/copy.tsv')
languages = ['en','ru','kk','uk','de','es']

if inventory.exists() and web_rows.exists():
    web = json.loads(inventory.read_text(encoding='utf-8'))['strings']
    rows = {r.split('|')[0]:r.split('|')[1:] for r in web_rows.read_text(encoding='utf-8').splitlines() if r and not r.startswith('#')}
    matches = {v['text']:rows.get(v['key'][5:]) for v in web}
    for key, value in sources.items():
        if key not in translations and matches.get(value['ru']):
            translations[key] = {'ru':value['ru'], **dict(zip(['en','kk','uk','de','es'],matches[value['ru']]))}

copy = BASE/'native_copy.tsv'
if copy.exists():
    for row in copy.read_text(encoding='utf-8').splitlines():
        if not row or row.startswith('#'):continue
        columns=row.split('|')
        assert len(columns)==6, row
        key = list(sources)[int(columns[0])]
        translations[key] = {'ru':sources[key]['ru'], **dict(zip(['en','kk','uk','de','es'],(v.replace('\\n','\n') for v in columns[1:]))) }

extras = json.loads((BASE/'catalog_extra.json').read_text(encoding='utf-8'))
translations.update(extras)
(BASE/'catalog_translations.json').write_text(json.dumps(translations,ensure_ascii=False,indent=2),encoding='utf-8')
missing = [(i,key,v['ru']) for i,(key,v) in enumerate(sources.items()) if key not in translations]
print('Translated',len(translations),'source',len(sources),'missing',len(missing))
for i,key,phrase in missing:print(str(i).zfill(3)+'|'+phrase.replace('\n',' / '))

def dart_string(value):
    return "'"+value.replace('\\','\\\\').replace("'","\\'").replace('$','\\$').replace('\n','\\n').replace('\r','\\r')+"'"

catalogs={lang:{key:values.get(lang,'') for key,values in translations.items()} for lang in languages}
output='// Six complete local catalogs. Generated by tool/catalog_build.py.\nconst waveCatalogs = <String, Map<String, String>>{\n'
for language, catalog in catalogs.items():
    output+=f"  '{language}': {{\n"
    for key,value in catalog.items():
        output+=f'    {dart_string(key)}: {dart_string(value)},\n'
    output+='  },\n'
output+='};\n'
Path('apps/native/lib/l10n/catalogs.dart').write_text(output,encoding='utf-8')
